import type { OriginalCreator } from "./types";

export const freshStartStudio: OriginalCreator = {
  handle: "fresh-start-studio",
  displayName: "Fresh Start Studio",
  tagline: "Practise the everyday conversations of your first months in Australia, from the GP to the bank to the vet.",
  bio: "Fresh Start Studio is a XINGO Original studio based in Sydney, made for people who have just arrived in Australia and want to get through the first busy months with less stress. Each course follows one real errand: booking a GP, picking up medicine, opening a bank account, taking the dog to the vet, signing a lease or sorting out a phone plan. You play yourself, the newcomer, and talk with friendly, busy and sometimes difficult people behind the counter. The scenarios start slow and predictable, then add the small surprises that happen in real life. Everything is practice, not advice, so you can make mistakes here first.",
  location: "Sydney, NSW",
  accent: "#0369A1",
  visualStyle: "Paper cut-out collage: layered coloured paper with visible torn edges and soft drop shadows, warm neutrals lifted by ocean blue accents.",
  logoBrief: "A torn-paper sunrise over an ocean blue paper wave, with the words Fresh Start cut from cream card, layered with soft shadows.",
  avatarBrief: "A round paper cut-out of an open front door with an ocean blue doormat and a small torn-paper suitcase beside it, softly shadowed.",
  courses: [
    {
      slug: "seeing-a-gp",
      kind: "roleplay",
      title: "Booking and Seeing a GP",
      tagline: "Book an appointment, explain how you feel and agree on a plan with your doctor.",
      description:
        "This course is for newcomers who need to see a general practitioner for the first time in Australia and want to feel ready before they pick up the phone. You practise the whole visit: calling the clinic, giving your details, describing symptoms in plain words and understanding what the doctor asks you to do next. In the first scenario you book an appointment with a patient, friendly receptionist who walks you through each step. In the second you sit with a GP who asks follow-up questions about a cough that will not go away and suggests a referral you need to understand. In the third the doctor does not agree with what you came in asking for, and you have to listen, ask good questions and leave with a plan you are both happy with. The doctors are fictional and nothing here is medical advice; the goal is clear, confident conversation.",
      keywords: ["gp", "doctor", "medical appointment", "symptoms", "health", "new arrivals"],
      whatYouGet: [
        "Three voice conversations, from booking by phone to a tricky consultation",
        "Phrases for describing symptoms, timing and how you feel",
        "Practice asking a doctor to repeat, slow down or explain a word",
      ],
      audience: "New arrivals who are about to book or attend their first GP appointment in Australia.",
      bannerBrief: "A paper cut-out clinic waiting room with a torn-paper reception desk, a cream paper stethoscope and an ocean blue appointment card.",
      scenarios: [
        {
          title: "Booking your first appointment by phone",
          description: "You're calling Northside Medical Centre to book your first appointment as a new patient. Give your details and choose a time that works for you.",
          difficultyLevel: "beginner",
          character: {
            name: "Megan O'Brien",
            role: "receptionist at Northside Medical Centre",
            goal: "You're booking a new patient. You need their full name, date of birth, mobile number and whether they have a Medicare card or travel insurance. Ask briefly why they want to see the doctor. You have Dr Mehta free on Thursday at 9.15am or 2.40pm, or Dr Karalis on Friday at 11am. Tell them new patients should arrive ten minutes early to fill in a form. Standard visits are $85 and part may be claimable, but you can't say how much.",
            demeanor: "warm and patient, speaks slowly, repeats times clearly, cheerful phone manner",
            openingLine: "Good morning, Northside Medical Centre, Megan speaking. How can I help you today?",
            endCondition: "the learner has given their details, chosen a time and repeated the appointment back",
            voice: "marin",
          },
          learnerRole: "new patient calling the clinic",
          taskCard: "- Say you are a new patient and want to book an appointment\n- Spell your name and give your date of birth and mobile number\n- Say briefly why you want to see the doctor\n- Choose a day and time and repeat it back to check",
          learnerOpens: false,
          timeLimitMinutes: 5,
        },
        {
          title: "The cough that won't go away",
          description: "You're seeing a GP about a cough you've had for about three weeks. Describe it clearly and make sure you understand the next steps the doctor suggests.",
          difficultyLevel: "intermediate",
          character: {
            name: "Arjun Mehta",
            role: "GP at Northside Medical Centre",
            goal: "You're seeing a new patient with an ongoing cough. Ask when it started, whether it's worse at night, if there's fever, if they smoke and if anything helps. Ask about allergies and current medicines. You want to send them for a chest X-ray at Harbour Imaging on King Street as a precaution and book a review in a week. If they look confused, explain the referral simply: take the form, call to book, bring results back. Don't diagnose anything firmly.",
            demeanor: "calm, thorough, uses some medical words then explains them if asked",
            openingLine: "Hi, come on in and take a seat. I'm Dr Mehta. So what brings you in today?",
            endCondition: "the learner has described the cough, answered the questions and confirmed what to do with the referral",
            voice: "cedar",
          },
          learnerRole: "patient seeing the GP",
          taskCard: "- Describe your cough: when it started and when it is worse\n- Answer the doctor's questions about fever, medicines and allergies\n- Ask what a referral is and what you need to do with it\n- Confirm when you should come back",
          learnerOpens: false,
          timeLimitMinutes: 7,
        },
        {
          title: "When the doctor says no",
          description: "You're back at the GP with a bad cold and you'd like something strong to get rid of it fast. The doctor doesn't agree, so listen, ask questions and agree on a plan.",
          difficultyLevel: "advanced",
          character: {
            name: "Sophia Karalis",
            role: "GP at Northside Medical Centre",
            goal: "You're seeing a patient who wants antibiotics for what sounds like a cold. You don't think they'll help a virus, and you say so kindly but firmly. Ask about symptoms and how long they've had them. Offer rest, fluids and a review if it's not better in a week or if breathing gets harder. If they need time off work, offer a medical certificate for two days. Only change your mind if they describe something new and serious; then examine them more closely.",
            demeanor: "kind but firm, steady pace, doesn't rush, checks understanding",
            openingLine: "Hello again. Dr Karalis. I see you were in a couple of weeks ago. What's going on this time?",
            endCondition: "the learner has explained their concern, understood the doctor's reasons and agreed on a plan or a certificate",
            voice: "sage",
          },
          learnerRole: "patient who wants fast relief",
          taskCard: "- Explain your symptoms and ask for something to make them go away\n- When the doctor disagrees, ask why politely\n- Explain you need to get back to work and ask what your options are\n- Agree on a clear plan and when to come back",
          learnerOpens: false,
          timeLimitMinutes: 8,
        },
      ],
    },
    {
      slug: "at-the-pharmacy",
      kind: "roleplay",
      title: "At the Pharmacy",
      tagline: "Ask for help at the counter, fill a script and handle the problems that pop up.",
      description:
        "This course is for new arrivals who need to visit a pharmacy and want to ask clear questions about what they are buying. You practise describing what you need, understanding questions from pharmacy staff and handling small problems without panic. The first scenario is a friendly chat with a pharmacy assistant about something for hay fever, where you answer simple questions and choose a product. The second takes you to the dispensary counter to fill a prescription, where the medicine you expected is out of stock and the pharmacist offers a different brand. In the third, you come in for more of a regular medicine but your script has run out, and the pharmacist cannot just hand it over, so you have to understand why and work out what to do next. The pharmacy and staff are fictional and nothing here is health advice.",
      keywords: ["pharmacy", "chemist", "prescription", "medicine", "health", "shopping"],
      whatYouGet: [
        "Three conversations at the pharmacy counter, from easy to tricky",
        "Language for describing symptoms and asking about side effects",
        "Practice understanding generic brands, scripts and repeats",
      ],
      audience: "Newcomers who need to buy medicine or fill a prescription at an Australian pharmacy.",
      bannerBrief: "A torn-paper pharmacy counter with cut-out shelves of cream and ocean blue paper boxes and a small paper prescription slip.",
      scenarios: [
        {
          title: "Something for hay fever",
          description: "You're at Parkview Pharmacy because your eyes are itchy and you keep sneezing. Ask the assistant for help and choose something to try.",
          difficultyLevel: "beginner",
          character: {
            name: "Duc Tran",
            role: "pharmacy assistant at Parkview Pharmacy",
            goal: "You're helping a customer with hay fever symptoms. Ask what symptoms they have, how long, and whether they take any other medicines or have allergies. Suggest a non-drowsy tablet at $14.99 for 30, or a nasal spray at $19.50. Say the pharmacist can help if they have other health conditions. Remind them to read the label. If asked, say the tablets are taken once a day as printed on the box, without giving any dose yourself.",
            demeanor: "friendly, relaxed, simple questions, smiles a lot",
            endCondition: "the learner has described their symptoms, chosen a product and asked how to use it",
            voice: "ash",
          },
          learnerRole: "customer at the pharmacy",
          taskCard: "- Tell the assistant your symptoms\n- Answer questions about other medicines and allergies\n- Ask about the difference between the options\n- Choose one and ask how to use it",
          learnerOpens: true,
          timeLimitMinutes: 5,
        },
        {
          title: "Out of stock at the dispensary",
          description: "You're filling a prescription from your GP, but the pharmacist says the brand on your script is out of stock. Find out your options and decide what to do.",
          difficultyLevel: "intermediate",
          character: {
            name: "Priya Sharma",
            role: "pharmacist at Parkview Pharmacy",
            goal: "You're filling a script. The brand written on it is out of stock until Tuesday. You can offer a generic version with the same active ingredient, which is $6 cheaper and ready in 15 minutes. Explain what generic means simply. Ask if they've taken this medicine before and if they have any allergies. If they'd rather wait, offer to order the brand and text them. Ask for their name, date of birth and Medicare card if they have one.",
            demeanor: "professional, efficient, clear explanations, a bit busy",
            openingLine: "Hi there, are you dropping off a script? Let me have a look for you.",
            endCondition: "the learner has understood the generic option and chosen to take it or wait for the brand",
            voice: "coral",
          },
          learnerRole: "customer filling a prescription",
          taskCard: "- Hand over your script and give your details\n- Ask what a generic medicine is\n- Ask if it is the same as your usual medicine\n- Decide whether to take the generic or wait",
          learnerOpens: false,
          timeLimitMinutes: 6,
        },
        {
          title: "No repeats left",
          description: "You're out of your regular medicine and ask the pharmacist for more, but your script has no repeats left. Stay calm, understand the rules and find a way forward.",
          difficultyLevel: "advanced",
          character: {
            name: "Michael Rossi",
            role: "senior pharmacist at Parkview Pharmacy",
            goal: "You're telling a customer their script has no repeats left, so you can't supply more without a new prescription. Stay polite but don't give in to pressure. Ask how many days they have left and if they've seen a GP recently. Suggest Northside Medical Centre, which has same-day appointments from 4pm, or a telehealth appointment. Only if they have none left and can't see a doctor today, say you'll check whether a small emergency supply is possible after asking more questions.",
            demeanor: "patient but firm, measured, explains rules without lecturing",
            openingLine: "Okay, I've had a look at your file. Unfortunately, there are no repeats left on this one.",
            endCondition: "the learner has understood why the pharmacist can't simply supply it and agreed on a next step",
            voice: "ballad",
          },
          learnerRole: "regular customer who has run out of medicine",
          taskCard: "- Explain that you have nearly run out of your medicine\n- Ask why the pharmacist cannot give you more\n- Push politely for a solution today\n- Agree on a clear next step",
          learnerOpens: false,
          timeLimitMinutes: 8,
        },
      ],
    },
    {
      slug: "opening-a-bank-account",
      kind: "roleplay",
      title: "Opening a Bank Account",
      tagline: "Open an account, sort out your ID and question a fee with confidence.",
      description:
        "This course is for people new to Australia who need an everyday bank account so they can get paid and pay rent. You practise the language of a bank branch: explaining what you need, understanding account features and answering questions about your identity and address. In the first scenario a friendly officer helps you open a basic everyday account step by step. In the second, you return to finish the account but one of your documents is not accepted, and you need to understand what is missing and how to fix it. In the third, you notice a fee on your statement you did not expect, and you have to explain the problem, ask questions and push politely for a refund. The bank, products and fees are invented for practice, and nothing here is financial advice.",
      keywords: ["bank account", "banking", "money", "identity documents", "fees", "new arrivals"],
      whatYouGet: [
        "Three branch conversations, from opening an account to disputing a fee",
        "Words for accounts, cards, statements, transfers and fees",
        "Practice explaining a problem clearly and asking for a fix",
      ],
      audience: "New arrivals opening their first Australian bank account at a branch.",
      bannerBrief: "A paper cut-out bank counter with a torn-paper debit card in ocean blue, stacked cream paper forms and soft shadowed coins.",
      scenarios: [
        {
          title: "Your first everyday account",
          description: "You're at the Coastline Bank branch on George Street to open an everyday account. Explain what you need and answer the officer's questions.",
          difficultyLevel: "beginner",
          character: {
            name: "Grace Santos",
            role: "customer service officer at Coastline Bank",
            goal: "You're opening an everyday account for a new customer. Ask for their passport, Australian address and mobile number. Explain the Everyday Plus account: no monthly fee, a debit card posted in 5 to 7 business days, and an app for transfers. Offer a savings account linked to it. Ask if they have a tax file number yet and say they can add it later. Ask if they want their card sent home or picked up at the branch.",
            demeanor: "bright and welcoming, slow and clear, checks understanding often",
            endCondition: "the learner has given their details, understood the account and chosen how to get their card",
            voice: "shimmer",
          },
          learnerRole: "new customer at the bank",
          taskCard: "- Say you want to open an everyday account\n- Give your ID, address and phone number\n- Ask about fees and when your card will arrive\n- Decide whether you want a savings account too",
          learnerOpens: true,
          timeLimitMinutes: 5,
        },
        {
          title: "A document that doesn't count",
          description: "You're back at Coastline Bank to finish opening your account, but the officer says one of your documents isn't enough. Find out what's missing and how to fix it.",
          difficultyLevel: "intermediate",
          character: {
            name: "Kevin Zhang",
            role: "account officer at Coastline Bank",
            goal: "You're finishing an account application. The customer brought a passport but their proof of address is a handwritten letter from a friend, which you can't accept. Explain what works instead: a lease, a utility bill or an official letter with their name and address. Say the account can open today with limited features and full access once the address is verified. Ask when they can bring a document in. Be helpful, but don't bend the rule.",
            demeanor: "polite, a little formal, apologetic about rules but clear",
            openingLine: "Thanks for coming back. I've looked through what you brought, and there's one thing we'll need to sort out.",
            endCondition: "the learner has understood which document is missing, what they can bring instead and when",
            voice: "verse",
          },
          learnerRole: "customer finishing an account application",
          taskCard: "- Ask which document is the problem and why\n- Find out what documents you can bring instead\n- Ask what you can use the account for until then\n- Say when you can come back",
          learnerOpens: false,
          timeLimitMinutes: 6,
        },
        {
          title: "Questioning a surprise fee",
          description: "You've noticed a $15 fee on your statement that you didn't expect. You're at the branch to find out what it is and ask for it to be refunded.",
          difficultyLevel: "advanced",
          character: {
            name: "Fatima Haddad",
            role: "branch service manager at Coastline Bank",
            goal: "You're handling a fee complaint. The $15 was an overdrawn fee because a $42 phone bill came out when the balance was $30. At first, explain that the fee follows the account terms. If the customer explains clearly and calmly that they're new and didn't understand, offer a one-time refund. Suggest turning on low-balance alerts in the app. If they get rude or vague, stay polite and ask them to explain again.",
            demeanor: "composed, professional, firm at first, softens when treated politely",
            openingLine: "Hi, I'm Fatima, the service manager. I understand you have a question about a fee?",
            endCondition: "the learner has explained the problem, understood why the fee was charged and either secured a refund or agreed on next steps",
            voice: "marin",
          },
          learnerRole: "account holder questioning a fee",
          taskCard: "- Describe the fee you saw and when\n- Ask what caused it\n- Explain your situation and ask politely for a refund\n- Ask how to avoid this happening again",
          learnerOpens: false,
          timeLimitMinutes: 8,
        },
      ],
    },
    {
      slug: "at-the-vet",
      kind: "roleplay",
      title: "At the Vet",
      tagline: "Book a check-up, describe what's wrong with your pet and talk through treatment costs.",
      description:
        "This course is for new arrivals with a pet, whether you brought one with you or adopted one after you landed. You practise booking a vet appointment, describing your animal's behaviour and talking about treatment and money. The first scenario is a simple phone call to book a check-up and vaccinations for a new kitten. In the second, you are in the consult room because your dog has stopped eating, and the vet asks lots of questions you need to answer clearly. In the third, the vet gives you a treatment quote that is more than you expected, and you must ask about options, payment and what matters most for your pet without feeling rushed. The clinic, prices and staff are invented, and nothing here is veterinary advice; it is practice for the conversation.",
      keywords: ["vet", "pets", "animals", "appointments", "costs", "new arrivals"],
      whatYouGet: [
        "Three vet clinic conversations, from booking to a hard money talk",
        "Words for describing an animal's eating, energy and behaviour",
        "Practice asking about quotes, payment plans and options",
      ],
      audience: "Newcomers with a cat, dog or other pet who need to use an Australian vet clinic.",
      bannerBrief: "A torn-paper vet clinic with a cut-out dog and kitten on an ocean blue paper exam table and a cream paper clipboard.",
      scenarios: [
        {
          title: "Booking a check-up for a new kitten",
          description: "You've just adopted a kitten and you're calling Bayside Vet Clinic to book a check-up. Give the details and choose a time.",
          difficultyLevel: "beginner",
          character: {
            name: "Chloe Bennett",
            role: "receptionist at Bayside Vet Clinic",
            goal: "You're booking a new client's kitten. Ask the owner's name and phone number, then the kitten's name, age and if it has had any vaccinations or a microchip. Offer Saturday at 10.30am or Monday at 5.15pm. A check-up with vaccination is $95. Ask them to bring any papers from the shelter and to use a carrier. Ask if they have pet insurance, but say it's fine if not.",
            demeanor: "cheerful, animal lover, gushes a little about kittens, clear with times",
            openingLine: "Bayside Vet Clinic, this is Chloe. How can I help?",
            endCondition: "the learner has given their and the kitten's details and booked a time",
            voice: "coral",
          },
          learnerRole: "new pet owner calling the vet",
          taskCard: "- Say you want to book a check-up for your new kitten\n- Give your details and the kitten's name and age\n- Ask how much it costs\n- Choose a time and ask what to bring",
          learnerOpens: false,
          timeLimitMinutes: 5,
        },
        {
          title: "My dog isn't eating",
          description: "Your dog Biscuit hasn't eaten properly for two days and you're in the consult room at Bayside Vet Clinic. Answer the vet's questions and understand what happens next.",
          difficultyLevel: "intermediate",
          character: {
            name: "Samuel Park",
            role: "vet at Bayside Vet Clinic",
            goal: "You're examining a dog that has barely eaten for two days. Ask when it started, whether Biscuit is drinking, vomiting or has diarrhoea, any change in food, and if he could have eaten something in the yard or on a walk. Say his tummy seems a bit sore. Recommend a blood test today for $180 and a bland diet, with a call tomorrow with results. Explain words like bland diet if asked.",
            demeanor: "gentle, methodical, asks one question at a time, reassuring",
            openingLine: "Hi, I'm Dr Park. And this must be Biscuit. Hello, mate. So he's not eating?",
            endCondition: "the learner has answered the vet's questions and understood the test, the diet and when they'll hear back",
            voice: "cedar",
          },
          learnerRole: "dog owner at the vet",
          taskCard: "- Explain what is wrong with your dog and since when\n- Answer questions about drinking, food and behaviour\n- Ask what the blood test is for and how much it costs\n- Check what to feed him and when you will hear back",
          learnerOpens: false,
          timeLimitMinutes: 7,
        },
        {
          title: "A quote you weren't expecting",
          description: "The vet says your dog needs surgery to remove something he swallowed, and the quote is much higher than you expected. Ask about options and decide what to do.",
          difficultyLevel: "advanced",
          character: {
            name: "Leilani Faleolo",
            role: "senior vet at Bayside Vet Clinic",
            goal: "You're telling an owner their dog has swallowed a sock and needs surgery today. The quote is $2,400 to $2,900 including overnight stay. Be honest that waiting is risky. If asked, explain a payment plan through the clinic: 30% today and the rest over three months. You can't lower the price, but you can skip the second night if he recovers well. Answer questions kindly and give them time to decide.",
            demeanor: "honest, compassionate, steady, doesn't pressure but is clear about risk",
            openingLine: "Thanks for waiting. The X-ray shows something in his stomach, probably a sock. I'd like to talk through options and costs.",
            endCondition: "the learner has asked about the risks, the costs and payment options and made a decision",
            voice: "sage",
          },
          learnerRole: "worried dog owner",
          taskCard: "- Ask what will happen if you wait\n- Say the cost is difficult for you right now\n- Ask about payment plans or ways to lower the cost\n- Make a decision and tell the vet",
          learnerOpens: false,
          timeLimitMinutes: 8,
        },
      ],
    },
    {
      slug: "phone-and-internet-plans",
      kind: "roleplay",
      title: "Phone and Internet Plans",
      tagline: "Choose a mobile plan, chase an internet connection and stand firm when you want to cancel.",
      description:
        "This course is for new arrivals setting up a phone and home internet, usually in the first week when everything feels urgent. You practise comparing plans, understanding data, contracts and connection dates, and saying no to extras you do not need. In the first scenario you visit a phone shop and choose a prepaid or SIM-only plan with a helpful salesperson. In the second you call about your home internet, which was meant to be connected today but has been delayed, and you need to find out why and get a new date. In the third you want to cancel a plan you signed up for in a hurry, while the retention officer offers deal after deal to keep you. The companies and prices are invented so you can focus on the language.",
      keywords: ["phone plan", "internet", "sim card", "contracts", "customer service", "shopping"],
      whatYouGet: [
        "Three conversations about mobile and home internet plans",
        "Words like data, prepaid, contract, connection and cancellation fee",
        "Practice saying no politely and holding your position",
      ],
      audience: "Newcomers getting a mobile number and home internet set up in Australia.",
      bannerBrief: "A paper cut-out phone shop with a torn-paper mobile phone, a cream paper SIM card and ocean blue signal waves layered behind.",
      scenarios: [
        {
          title: "Picking a SIM-only plan",
          description: "You're at the Wavelength Mobile shop in the city to get an Australian number. Tell the salesperson what you need and choose a plan.",
          difficultyLevel: "beginner",
          character: {
            name: "Jayden Smith",
            role: "salesperson at Wavelength Mobile",
            goal: "You're helping a new arrival get a mobile number. Ask how much they use data, whether they call overseas, and if they want a contract. Offer prepaid at $30 for 28 days with 40GB, or a monthly SIM-only plan at $45 with 80GB and some international minutes. You need to see their passport to activate the SIM. Mention the phone number can be ready in about 20 minutes.",
            demeanor: "easygoing, chatty, uses some slang then rephrases it, helpful",
            endCondition: "the learner has explained what they need, chosen a plan and shown ID",
            voice: "ash",
          },
          learnerRole: "customer buying a mobile plan",
          taskCard: "- Say you need an Australian phone number\n- Explain how much data you use and who you call\n- Ask about the difference between prepaid and monthly\n- Choose a plan",
          learnerOpens: true,
          timeLimitMinutes: 5,
        },
        {
          title: "Where's my internet?",
          description: "Your home internet from Homelink Broadband was meant to be connected today, but nothing works. You're calling to find out what's happening and get a new date.",
          difficultyLevel: "intermediate",
          character: {
            name: "Mei Chen",
            role: "support agent at Homelink Broadband",
            goal: "You're helping a customer whose connection didn't happen. First check their account number or name and address. The system shows a technician needs to visit because the wall socket wasn't working. The earliest visit is next Wednesday between 8am and 12pm. You can offer a free 4G modem to use until then, posted in two days. If they ask, offer a $20 credit for the delay. Ask them to confirm someone over 18 will be home.",
            demeanor: "polite, scripted at first, warmer when the customer is clear",
            openingLine: "Thanks for calling Homelink Broadband, you're speaking with Mei. Can I start with your account number?",
            endCondition: "the learner has found out why it was delayed, confirmed a technician time and asked about a temporary option",
            voice: "shimmer",
          },
          learnerRole: "customer waiting for home internet",
          taskCard: "- Explain that your internet was meant to start today\n- Ask why it is not working\n- Confirm a new date and time for the technician\n- Ask if you can have internet until then",
          learnerOpens: false,
          timeLimitMinutes: 6,
        },
        {
          title: "Cancelling without being talked out of it",
          description: "You signed up to a 24-month phone plan in a hurry and now you want to cancel. Hold your ground while the retention officer offers you deals.",
          difficultyLevel: "advanced",
          character: {
            name: "Tom Wilson",
            role: "retention officer at Wavelength Mobile",
            goal: "You're trying to stop a customer from cancelling. First ask why they're leaving. Offer a $10 monthly discount for six months, then double data, then a free month. Only after they say no twice clearly, explain the cancellation fee: the remaining phone cost of $340 and no plan fee. Ask if they're sure. If they stay firm and polite, process it and give a reference number, WM-58213.",
            demeanor: "smooth, persistent, friendly sales voice, keeps offering one more thing",
            openingLine: "Hi, Tom here from the accounts team. I hear you're thinking of leaving us. Can I ask what's going on?",
            endCondition: "the learner has declined the offers, understood the cancellation cost and either cancelled with a reference number or chosen to stay",
            voice: "ballad",
          },
          learnerRole: "customer who wants to cancel a plan",
          taskCard: "- Say clearly that you want to cancel your plan\n- Give a short reason\n- Say no politely to each offer\n- Ask exactly what you will need to pay and get a reference number",
          learnerOpens: false,
          timeLimitMinutes: 8,
        },
      ],
    },
    {
      slug: "renting-your-first-place",
      kind: "roleplay",
      title: "Renting Your First Place",
      tagline: "Ask the right questions at an inspection, fix a weak application and negotiate a lease.",
      description:
        "This course is for new arrivals looking for a rental home, often without a rental history in Australia. You practise speaking with property managers and leasing agents, asking useful questions and presenting yourself as a good tenant. In the first scenario you attend an open inspection and ask about rent, bills and the lease with a friendly property manager. In the second the agent calls to say your application is incomplete because you have no local references, and you need to offer something else. In the third you are offered the place but the terms are not quite right, and you try to negotiate the rent, the start date and keeping a pet. The agencies and properties are invented, and nothing here is legal advice about tenancy.",
      keywords: ["renting", "lease", "rental inspection", "property manager", "housing", "new arrivals"],
      whatYouGet: [
        "Three conversations from open inspection to lease negotiation",
        "Words for bond, rent in advance, lease length and references",
        "Practice making a polite counter-offer",
      ],
      audience: "Newcomers searching for and applying for their first rental in Australia.",
      bannerBrief: "A torn-paper terrace house with an ocean blue paper door, a cut-out For Lease sign and a cream paper key with a soft shadow.",
      scenarios: [
        {
          title: "Questions at the open inspection",
          description: "You're at an open inspection for a one-bedroom unit in Marrickville. Ask the property manager about the rent, the lease and how to apply.",
          difficultyLevel: "beginner",
          character: {
            name: "Rachel Kim",
            role: "property manager at Harbourline Realty",
            goal: "You're running an open inspection for a one-bedroom unit at $520 a week. The lease is 12 months, available from the 15th. Water usage is charged to the tenant, but not water rates. There's one car space and a shared laundry. Pets are considered case by case. Applications are online and need ID, proof of income and references. Answer questions clearly and ask the visitor if they're interested.",
            demeanor: "friendly, upbeat, organised, used to many visitors",
            endCondition: "the learner has asked about the rent, lease and bills and found out how to apply",
            voice: "marin",
          },
          learnerRole: "person looking for a rental",
          taskCard: "- Introduce yourself to the property manager\n- Ask about the weekly rent and the lease length\n- Ask which bills you would pay\n- Find out how to apply",
          learnerOpens: true,
          timeLimitMinutes: 5,
        },
        {
          title: "My application has a gap",
          description: "The leasing agent calls about your application for a unit in Ashfield. You don't have Australian rental references, so you need to offer something else.",
          difficultyLevel: "intermediate",
          character: {
            name: "George Antoniou",
            role: "leasing agent at Westside Property Group",
            goal: "You're calling about a rental application at $480 a week. It's missing rental references because the applicant is new to Australia. The owner is careful. Ask about their job, how long they've worked there and if they have savings. Say a letter from their employer, a reference from an overseas landlord, or paying two weeks of extra rent in advance could help. Don't promise approval; say you'll take it to the owner by Friday.",
            demeanor: "brisk, businesslike, fair, speaks quickly but repeats if asked",
            openingLine: "Hi, it's George from Westside Property Group, calling about your application for the Ashfield unit. Got a minute?",
            endCondition: "the learner has explained their situation and agreed on what extra documents they will send",
            voice: "verse",
          },
          learnerRole: "rental applicant",
          taskCard: "- Explain why you do not have Australian references\n- Talk about your job and how you will pay the rent\n- Ask what extra documents would help\n- Agree on when you will send them",
          learnerOpens: false,
          timeLimitMinutes: 6,
        },
        {
          title: "Negotiating the lease",
          description: "You've been offered a two-bedroom flat in Parramatta, but the rent, start date and no-pets rule don't suit you. Negotiate with the property manager before you sign.",
          difficultyLevel: "advanced",
          character: {
            name: "Danielle Murray",
            role: "senior property manager at Harbourline Realty",
            goal: "You're offering a flat at $610 a week from Monday. The owner prefers no pets. You want a quick yes. If the tenant offers an 18-month lease, you can drop the rent to $590. You can move the start date by up to a week, not more. For a pet, you'll ask the owner only if they describe the pet and offer a pet agreement. If they push too hard or are vague, say another applicant is keen.",
            demeanor: "confident, direct, a bit impatient, respects clear offers",
            openingLine: "Good news, the owner's happy to offer you the place. Can we get the lease signed this week?",
            endCondition: "the learner has made clear counter-offers on rent, start date or pet and reached an agreement or decided to walk away",
            voice: "coral",
          },
          learnerRole: "applicant offered a lease",
          taskCard: "- Thank the manager and say you are interested\n- Ask for a lower rent and offer something in return\n- Ask to move the start date\n- Ask about keeping your small dog, then agree or decline",
          learnerOpens: false,
          timeLimitMinutes: 8,
        },
      ],
    },
    {
      slug: "at-the-service-counter",
      kind: "roleplay",
      title: "At the Government Service Counter",
      tagline: "Update your details, fix a form problem and ask for help with a confusing letter.",
      description:
        "This course is for new arrivals who need to visit a government service centre, for Medicare enrolment or another everyday service, and want to be ready for the counter. You practise explaining what you need, giving personal details and understanding instructions. In the first scenario a friendly officer helps you update your address. In the second you bring a form but it is the wrong version and a document is missing, so you need to find out exactly what to do. In the third you arrive with a letter you do not understand, the queue is long and the officer is busy, and you must explain clearly and ask for the help you need. The centre and officers are invented, and the scenarios describe no real policies, payments or rules; they focus on the conversation.",
      keywords: ["government services", "medicare", "forms", "customer service", "paperwork", "new arrivals"],
      whatYouGet: [
        "Three counter conversations with a government service officer",
        "Language for forms, documents, reference numbers and letters",
        "Practice asking an officer to explain step by step",
      ],
      audience: "Newcomers visiting a government service centre for the first time.",
      bannerBrief: "A paper cut-out service counter with a torn-paper queue ticket, cream paper forms and an ocean blue number display above.",
      scenarios: [
        {
          title: "Updating your address",
          description: "You've moved into a new flat and you're at the service centre to update your address. Give your details and check what happens next.",
          difficultyLevel: "beginner",
          character: {
            name: "Anthony Russo",
            role: "customer service officer at the Burwood Service Centre",
            goal: "You're helping someone update their address. Ask for their full name, date of birth and card or customer number. Ask for the old address and the new one, including postcode, and spell back the street name. Say the change takes effect today and any new card will be posted within two weeks. Ask if they want to update their phone number too. Give them a receipt number, BSC-4471.",
            demeanor: "relaxed, friendly, methodical, repeats details back",
            endCondition: "the learner has given their old and new address, checked the spelling and received a receipt number",
            voice: "cedar",
          },
          learnerRole: "customer at a service centre",
          taskCard: "- Say you want to update your address\n- Give your name, date of birth and customer number\n- Spell your new street name and give the postcode\n- Ask when the change will happen",
          learnerOpens: true,
          timeLimitMinutes: 5,
        },
        {
          title: "Wrong form, missing document",
          description: "You've filled in a form for an enrolment, but the officer says it's an old version and a document is missing. Find out exactly what you need to do.",
          difficultyLevel: "intermediate",
          character: {
            name: "Jasmine Reyes",
            role: "customer service officer at the Burwood Service Centre",
            goal: "You're telling a customer their form is an old version and won't be accepted. Give them the current form and say most answers are the same, but page 3 is new. They also need a copy of their visa grant letter, which is missing. Say they can print it at the library next door, or show it on their phone and you'll scan it. Offer to hold their place so they don't queue again.",
            demeanor: "helpful, practical, quick, apologetic about the old form",
            openingLine: "Thanks for waiting. I've had a look at this, and I'm sorry, but it's an older version of the form.",
            endCondition: "the learner has understood what is wrong, what to fill in again and how to provide the missing document",
            voice: "shimmer",
          },
          learnerRole: "customer submitting a form",
          taskCard: "- Ask what is wrong with your form\n- Ask which parts you need to fill in again\n- Find out which document is missing and how to give it\n- Ask whether you need to queue again",
          learnerOpens: false,
          timeLimitMinutes: 6,
        },
        {
          title: "A letter you don't understand",
          description: "You've received an official letter asking you to respond by Friday, and you don't understand it. The centre is busy, so explain clearly and get the help you need.",
          difficultyLevel: "advanced",
          character: {
            name: "Wei Liu",
            role: "senior officer at the Burwood Service Centre",
            goal: "You're very busy. At first, suggest the customer calls the number on the letter. If they explain clearly that they don't understand it and the deadline is Friday, help them. The letter asks them to confirm their identity because two records have different spellings. They can bring their passport to the counter or upload it online. Explain using reference number LTR-90532. If they're vague, ask them to read the first line.",
            demeanor: "rushed, short sentences at first, becomes patient once the problem is clear",
            openingLine: "Next, please. Yes, what can I do for you? It's quite busy today, so let's be quick.",
            endCondition: "the learner has explained the letter, understood what it asks and agreed how they will respond before the deadline",
            voice: "ash",
          },
          learnerRole: "customer with a confusing letter",
          taskCard: "- Explain that you received a letter you do not understand\n- Ask the officer to explain it in simple words\n- When asked to call instead, explain why you need help now\n- Confirm what you need to do and by when",
          learnerOpens: false,
          timeLimitMinutes: 8,
        },
      ],
    },
    {
      slug: "getting-around-by-public-transport",
      kind: "roleplay",
      title: "Getting Around by Public Transport",
      tagline: "Get a travel card, ask for directions and sort out a fare problem.",
      description:
        "This course is for new arrivals learning to use buses, trains and ferries in an Australian city. You practise the everyday language of getting around: buying and topping up a travel card, asking for directions, and dealing with problems when things go wrong. In the first scenario you buy a travel card at a station and ask the staff how it works. In the second you are at a bus stop where your bus is not coming because of roadworks, and a local helps you find another way. In the third a transport officer checks your card and finds you did not tap on properly, so you need to stay calm, explain what happened and understand what to do. The network, stations and staff are invented for practice, and no real fares or fines are described.",
      keywords: ["public transport", "travel card", "directions", "trains", "buses", "getting around"],
      whatYouGet: [
        "Three conversations on the way to work, school or the shops",
        "Words for tapping on, top-ups, platforms, stops and changes",
        "Practice asking for directions and explaining a mistake",
      ],
      audience: "Newcomers getting used to public transport in an Australian city.",
      bannerBrief: "A paper cut-out train and bus on torn-paper tracks and roads, with an ocean blue harbour ferry and a cream paper travel card.",
      scenarios: [
        {
          title: "Getting your first travel card",
          description: "You're at Central Station and want a travel card for buses and trains. Ask the staff member how to get one and how it works.",
          difficultyLevel: "beginner",
          character: {
            name: "Patrick Doyle",
            role: "customer service attendant at Central Station",
            goal: "You're helping a newcomer get a travel card. Explain they can buy the Tapline card here for $10 with $10 of credit. They tap on when they get on and tap off when they get off, on trains, buses and ferries. They can top up at machines, shops or online. Offer to show them which platform goes to Strathfield: platform 16. Ask if they're a student, as there may be a concession card.",
            demeanor: "cheerful, patient, slow speech, likes giving tips",
            endCondition: "the learner has bought a card, understood tapping on and off and knows how to top up",
            voice: "ballad",
          },
          learnerRole: "new commuter at the station",
          taskCard: "- Ask how to get a travel card\n- Find out how much it costs\n- Ask how to use it on trains and buses\n- Ask where to top it up",
          learnerOpens: true,
          timeLimitMinutes: 5,
        },
        {
          title: "Your bus isn't coming",
          description: "You're waiting for the 412 bus to a job interview, but a sign says the stop has moved because of roadworks. Ask a local at the stop for help.",
          difficultyLevel: "intermediate",
          character: {
            name: "Joyce Walker",
            role: "local resident waiting at the bus stop",
            goal: "You're a friendly local who knows the area. The 412 stop has moved 200 metres down Liverpool Road, past the bakery and across at the lights. Or they can walk 10 minutes to Croydon Station and catch a train two stops. Ask where they're going and what time they need to be there. If they say 10am and it's 9.20, suggest the train is safer. Chat a bit about the roadworks.",
            demeanor: "warm, chatty, motherly, gives landmarks rather than street names",
            openingLine: "You look a bit lost, love. Waiting for the 412? They've moved the stop with all these roadworks.",
            endCondition: "the learner has explained where they are going, understood the directions and chosen a way to get there",
            voice: "sage",
          },
          learnerRole: "newcomer waiting for a bus",
          taskCard: "- Explain where you need to go and by what time\n- Ask where the new bus stop is\n- Ask about another way to get there\n- Repeat the directions back to check",
          learnerOpens: false,
          timeLimitMinutes: 6,
        },
        {
          title: "Your card didn't tap on",
          description: "A transport officer checks your card on the train and says it shows no trip. Stay calm, explain what happened and find out what you need to do.",
          difficultyLevel: "advanced",
          character: {
            name: "Hamid Rahimi",
            role: "transport officer checking fares on the train",
            goal: "You're checking cards. This passenger's card shows no tap on. You need to know where they got on and whether they tapped. If they explain the reader at Lidcombe beeped red and they were confused, ask for their card and ID. You can give a warning if their story is clear and the card has credit. If they argue or are vague, explain you may need to issue a notice and they can ask for a review later.",
            demeanor: "formal, firm, neutral tone, fair if the passenger is calm and clear",
            openingLine: "Morning. Can I check your travel card, please? ... It's not showing a trip today. Where did you get on?",
            endCondition: "the learner has explained what happened, answered the officer's questions and understood the outcome",
            voice: "verse",
          },
          learnerRole: "passenger whose card did not tap on",
          taskCard: "- Hand over your card and say where you got on\n- Explain what happened at the card reader\n- Answer the officer's questions calmly\n- Ask what happens now and how to avoid it next time",
          learnerOpens: false,
          timeLimitMinutes: 8,
        },
      ],
    },
    {
      slug: "first-meeting-at-a-job-agency",
      kind: "roleplay",
      title: "First Meeting at a Job Agency",
      tagline: "Talk about your skills, handle questions about your qualifications and say no to the wrong job.",
      description:
        "This course is for new arrivals meeting an employment consultant to start looking for work in Australia. You practise introducing your experience, explaining your goals and talking about what you can and cannot do. In the first scenario you have a friendly first meeting where the consultant asks about your background and the kind of work you want. In the second the consultant tells you your overseas qualification may not be recognised straight away, and you need to understand your options and ask about next steps. In the third the consultant pushes a job offer that does not fit your life, and you must decline politely, explain your limits and suggest what would work instead. The agency and jobs are invented; the focus is confident, honest conversation.",
      keywords: ["jobs", "employment", "job agency", "work", "qualifications", "career"],
      whatYouGet: [
        "Three meetings with an employment consultant",
        "Phrases for describing your experience, skills and availability",
        "Practice declining an offer politely and suggesting an alternative",
      ],
      audience: "Newcomers starting their job search with an Australian employment agency.",
      bannerBrief: "A torn-paper office desk with a cut-out résumé, an ocean blue paper briefcase and two paper chairs facing each other.",
      scenarios: [
        {
          title: "Telling your story",
          description: "You're at your first meeting at Pathway Employment in Blacktown. Tell the consultant about your experience and the kind of work you want.",
          difficultyLevel: "beginner",
          character: {
            name: "Natalie Brooks",
            role: "employment consultant at Pathway Employment",
            goal: "You're meeting a new jobseeker. Ask what work they did before, for how long, and what they enjoyed. Ask what kind of job they want now, which days they can work, and if they have a driver's licence. Ask if they have a résumé. Offer a free résumé workshop next Tuesday at 10am. Write notes and summarise their goals at the end.",
            demeanor: "encouraging, warm, open questions, gives lots of positive feedback",
            openingLine: "Welcome to Pathway, I'm Natalie. Grab a seat. Let's start with you. Tell me a bit about yourself.",
            endCondition: "the learner has described their experience, the work they want and their availability",
            voice: "marin",
          },
          learnerRole: "jobseeker at a first meeting",
          taskCard: "- Introduce yourself and your work experience\n- Say what kind of job you want now\n- Explain which days and times you can work\n- Ask about help with your résumé",
          learnerOpens: false,
          timeLimitMinutes: 5,
        },
        {
          title: "Your qualification isn't recognised yet",
          description: "You worked as an accountant overseas, but the consultant says employers may not recognise your qualification yet. Understand your options and plan the next step.",
          difficultyLevel: "intermediate",
          character: {
            name: "Sione Taufa",
            role: "employment consultant at Pathway Employment",
            goal: "You're explaining to a qualified accountant that some employers will want a local assessment of their overseas qualification. Say you can't confirm how long it takes, but suggest they check with the relevant professional body. Meanwhile, suggest bookkeeping or accounts assistant roles to get local experience, and a short TAFE course in Australian payroll. Listen if they're disappointed and ask what matters most to them.",
            demeanor: "honest, supportive, calm, doesn't oversell",
            openingLine: "So I've looked at your résumé, and your experience is strong. There's one thing we need to talk about, though.",
            endCondition: "the learner has understood the issue with their qualification, asked about options and chosen a next step",
            voice: "cedar",
          },
          learnerRole: "jobseeker with an overseas qualification",
          taskCard: "- Ask why your qualification might not be recognised\n- Ask how you can get it assessed\n- Ask what jobs you could do in the meantime\n- Agree on one next step",
          learnerOpens: false,
          timeLimitMinutes: 6,
        },
        {
          title: "Saying no to the wrong job",
          description: "The consultant has a warehouse job with night shifts starting Monday, but you have young children. Decline politely, explain your limits and ask for something that fits.",
          difficultyLevel: "advanced",
          character: {
            name: "Bronwyn Hughes",
            role: "senior consultant at Pathway Employment",
            goal: "You have a target to fill a warehouse role at Riverside Logistics: nights, 10pm to 6am, four nights a week, $32 an hour, starting Monday. Push it as a great opportunity. If they decline, ask why and suggest trying it for a month. Only if they clearly explain their limits and say what would work, mention a day-shift admin assistant role at Greenway Plumbing, 9am to 3pm, interviews next week.",
            demeanor: "energetic, pushy, positive, talks fast, accepts clear reasons",
            openingLine: "Great news, I've got something for you! Warehouse role, good money, starts Monday. What do you say?",
            endCondition: "the learner has declined the night-shift job, explained their limits and discussed a role that fits",
            voice: "coral",
          },
          learnerRole: "jobseeker who needs day-time work",
          taskCard: "- Thank the consultant for the offer\n- Decline politely and explain why\n- Say clearly which hours and days you can work\n- Ask about other jobs that fit",
          learnerOpens: false,
          timeLimitMinutes: 8,
        },
      ],
    },
    {
      slug: "at-the-licence-counter",
      kind: "roleplay",
      title: "At the Licence and ID Counter",
      tagline: "Ask about your overseas licence, book a test and fix a name that doesn't match.",
      description:
        "This course is for new arrivals dealing with licences and identity documents at a service counter. You practise asking about processes, booking appointments and explaining personal details clearly. In the first scenario you ask a friendly officer what you need to start driving with your overseas licence. In the second you try to book a driving test, but the dates you want are full and you need to find another option. In the third your name is spelled differently on two documents, the officer cannot continue, and you must explain the difference and work out how to fix it. The service centre and processes are invented and simplified; the scenarios give no real rules, time limits or legal advice about licences or identity, so always check official sources for your own situation.",
      keywords: ["driver licence", "identity documents", "driving test", "service centre", "paperwork", "new arrivals"],
      whatYouGet: [
        "Three counter conversations about licences and ID",
        "Language for spelling names, dates, documents and bookings",
        "Practice explaining a document problem calmly",
      ],
      audience: "Newcomers who need to sort out a driver licence or ID documents at a service counter.",
      bannerBrief: "A paper cut-out service counter with a torn-paper car, a cream paper licence card and an ocean blue calendar page.",
      scenarios: [
        {
          title: "Can I drive with my overseas licence?",
          description: "You're at the Liverpool Service Centre to ask about driving with your overseas licence. Find out what you need to bring and what to do next.",
          difficultyLevel: "beginner",
          character: {
            name: "Daniel Costa",
            role: "service officer at the Liverpool Service Centre",
            goal: "You're answering a newcomer's questions about an overseas licence. Ask which country issued it, whether it's in English, and how long they've lived here. Tell them to check the official website for their situation, then explain the general steps here: book an appointment, bring the licence, passport and proof of address, and do an eyesight test. Offer to book them in for Thursday at 1.30pm.",
            demeanor: "friendly, simple explanations, unhurried, likes checklists",
            endCondition: "the learner has asked about their licence, understood what to bring and booked or declined an appointment",
            voice: "ash",
          },
          learnerRole: "newcomer asking about their licence",
          taskCard: "- Say you have an overseas driver licence\n- Ask what you need to do to drive here\n- Ask which documents to bring\n- Book an appointment",
          learnerOpens: true,
          timeLimitMinutes: 5,
        },
        {
          title: "The test dates are full",
          description: "You want to book your driving test before you start a new job in three weeks, but the first dates are full. Find another option that works.",
          difficultyLevel: "intermediate",
          character: {
            name: "Hannah Lee",
            role: "bookings officer at the Liverpool Service Centre",
            goal: "You're booking a driving test. Liverpool is full for five weeks. The first date there is the 14th of next month at 8.40am. Penrith has a test in 12 days at 2.15pm, and Campbelltown in 16 days at 11am. You can add them to a cancellation list for Liverpool. Ask for their licence number and which car they'll use. The test fee is $60, paid when booking.",
            demeanor: "efficient, polite, reads dates and times clearly, a little formal",
            openingLine: "Hi, next please. You're after a driving test? Let me check what we've got.",
            endCondition: "the learner has compared the options, chosen a date and location and confirmed the booking",
            voice: "shimmer",
          },
          learnerRole: "learner driver booking a test",
          taskCard: "- Say you want to book a driving test soon\n- Explain why you need it in the next three weeks\n- Ask about other locations and the cancellation list\n- Choose an option and confirm the date and time",
          learnerOpens: false,
          timeLimitMinutes: 6,
        },
        {
          title: "When your name doesn't match",
          description: "Your name is spelled differently on your passport and your bank letter, and the officer can't continue. Explain the difference and find out how to fix it.",
          difficultyLevel: "advanced",
          character: {
            name: "Vikram Singh",
            role: "senior officer at the Liverpool Service Centre",
            goal: "You can't process the application because the passport shows one spelling and the proof of address shows another, with a middle name missing. Explain you need names to match. Ask which name they use day to day. If they explain clearly, say a new letter from the bank with the passport spelling would fix it, or a different proof of address that matches. Don't accept a handwritten note. Offer to hold the file for 14 days.",
            demeanor: "serious, careful, polite, sticks to the rules but wants to help",
            openingLine: "I'm sorry, I can't go ahead with this today. The name on your passport and this letter aren't the same.",
            endCondition: "the learner has explained the name difference, understood what document will fix it and agreed on a plan",
            voice: "ballad",
          },
          learnerRole: "applicant whose documents don't match",
          taskCard: "- Ask the officer to show you what doesn't match\n- Explain why your name is spelled differently\n- Ask what you can bring to fix it\n- Agree on when you will come back",
          learnerOpens: false,
          timeLimitMinutes: 8,
        },
      ],
    },
  ],
};
