import type { OriginalCreator } from "./types";

export const kindHands: OriginalCreator = {
  handle: "kind-hands",
  displayName: "Kind Hands",
  tagline: "Everyday English for care and support workers: calm words for real shifts, with dignity and consent at the centre.",
  bio: "Kind Hands is a XINGO Original studio based in Hobart, built for people who work in aged care, disability support and home care. Our role-plays follow a real working day: knocking on a resident's door in the morning, handing over to the next shift, ringing a client's family, reporting a fall, and writing notes that someone else can actually use. Every scenario puts the person you support first, so you practise asking before helping, offering choices and respecting a no. The people you meet are friendly, worried, rushed or upset, just like on the floor. The care details are kept general on purpose, so you can focus on the English you need to be clear, kind and professional.",
  location: "Hobart, TAS",
  accent: "#A21CAF",
  visualStyle: "Soft pastel gouache with matte painted textures in lilac and peach, gentle rounded figures and calm, even morning light.",
  logoBrief: "Two rounded gouache hands gently cupped together in lilac and peach, with a matte painted texture and soft edges.",
  avatarBrief: "A smiling care worker with a rounded face and lilac lanyard, painted in soft matte gouache against a warm peach background.",
  courses: [
    {
      slug: "aged-care-morning-routine",
      kind: "roleplay",
      title: "Good Morning: The Aged-Care Morning Routine",
      tagline: "Knock, greet, offer choices and help a resident start the day at their own pace.",
      description:
        "This course is for aged-care workers and students on placement who want to sound warm and confident during the first hour of a shift. You practise knocking and introducing yourself, asking how someone slept, offering choices about clothes and breakfast, and asking permission before you help with anything personal. In the first scenario you help a cheerful resident get ready for the day, and she follows your lead. In the second, a resident wants to change the usual routine and skip his shower, so you need to listen, offer options and agree on a plan without pressure. In the third, a resident who is embarrassed about needing help with dressing says she can manage alone, and you must respect her independence while still keeping her safe. By the end you will have the phrases to make a morning feel like her morning, not your task list.",
      keywords: ["aged care", "morning routine", "consent", "personal care", "residents", "offering choices"],
      whatYouGet: [
        "Natural ways to knock, introduce yourself and ask how someone slept",
        "Phrases for offering real choices about clothes, breakfast and timing",
        "Polite ways to ask permission before helping with personal care",
        "Practice respecting a no while still keeping someone safe",
      ],
      audience: "Aged-care workers, students on placement and new carers who want warmer, clearer morning conversations with residents.",
      bannerBrief: "A care worker opening soft lilac curtains for a smiling older woman sitting on her bed, painted in matte peach and lilac gouache with calm morning light.",
      scenarios: [
        {
          title: "Good morning, Dorothy",
          description: "You're a care worker on the morning shift at Wattle Grove Aged Care, and it's 7.30 am. Knock on Dorothy's door, greet her, and help her choose what to wear and what she'd like for breakfast.",
          difficultyLevel: "beginner",
          character: {
            name: "Dorothy Whitfield",
            role: "84-year-old resident at Wattle Grove Aged Care, Room 12",
            goal: "You're a friendly retired primary teacher who has lived at Wattle Grove for two years. You slept well and want to wear your blue cardigan because your granddaughter Emma is visiting at 11 am. For breakfast you'd like porridge with brown sugar and a weak tea with milk. You like being asked rather than told. If the worker asks, you mention your left knee is a bit stiff this morning, so you'd like a hand standing up.",
            demeanor: "cheerful and chatty, speaks slowly and clearly, says 'love' a lot, happy to follow a polite lead",
            openingLine: "Come in, come in! Oh, are you new? I don't think we've met.",
            endCondition: "the learner has introduced themselves, asked about her outfit and breakfast, and asked before helping her stand",
            voice: "shimmer",
          },
          learnerRole: "care worker on the morning shift",
          taskCard: "- Knock, greet Dorothy and introduce yourself by name\n- Ask how she slept and how she's feeling this morning\n- Offer her a choice of clothes and ask what she'd like for breakfast\n- Ask permission before you help her stand up",
          learnerOpens: true,
          timeLimitMinutes: 5,
        },
        {
          title: "Not today, thanks: Vasilis skips his shower",
          description: "You're a care worker at Wattle Grove Aged Care, and Vasilis is usually showered at 8 am on Tuesdays. Today he says he doesn't want one, so find out why and agree on a plan that suits him.",
          difficultyLevel: "intermediate",
          character: {
            name: "Vasilis Kostopoulos",
            role: "79-year-old resident at Wattle Grove Aged Care, Room 4",
            goal: "You're a retired fruit-shop owner. You don't want your shower at 8 am today because the bathroom felt cold last time and you want to watch the soccer replay at 8.30. You'll happily have a shower this afternoon or a wash at the sink now. You push back if the worker sounds bossy or says 'you have to'. If asked kindly, you admit you'd like the heater turned on first and prefer a male worker for showers if one is free.",
            demeanor: "polite but stubborn, a bit grumpy before breakfast, warms up fast if offered choices",
            openingLine: "Shower? No, no. Not this morning. Leave it, please.",
            endCondition: "the learner has found out his reasons, offered at least two options and agreed on a time or alternative he is happy with",
            voice: "cedar",
          },
          learnerRole: "care worker on the morning shift",
          taskCard: "- Ask Vasilis why he'd rather not shower this morning\n- Listen without pressuring him or saying he has to\n- Offer at least two other options, like a later time or a sink wash\n- Agree on a plan and check he's happy with it",
          learnerOpens: false,
          timeLimitMinutes: 6,
        },
        {
          title: "I can do it myself: Lan and the buttons",
          description: "You're a care worker at Wattle Grove Aged Care, and Lan has been unsteady on her feet this week. She insists on dressing alone with the door shut, so respect her independence while finding a safe way to support her.",
          difficultyLevel: "advanced",
          character: {
            name: "Lan Nguyen",
            role: "76-year-old resident at Wattle Grove Aged Care, Room 19",
            goal: "You're a proud former seamstress who hates needing help. You want to dress alone with the door closed. You refuse if the worker just says it's the rules. Only if asked gently do you admit the buttons on your good blouse are hard now and you nearly fell yesterday reaching for your shoes. You'll accept a compromise, like the worker waiting outside with the door ajar, sitting down to dress, or help only with shoes. You want them to knock before coming back in.",
            demeanor: "dignified and sharp, short replies when she feels rushed, softens when treated as capable",
            openingLine: "Thank you, but I've been dressing myself for seventy years. I'm fine.",
            endCondition: "the learner has acknowledged her independence, gently raised the safety concern and agreed on a compromise she accepts",
            voice: "marin",
          },
          learnerRole: "care worker on the morning shift",
          taskCard: "- Acknowledge that Lan wants to dress herself and say you respect that\n- Gently ask how she's been managing, without lecturing\n- Raise your safety concern in plain, kind words\n- Offer a compromise and agree on exactly how you'll help",
          learnerOpens: false,
          timeLimitMinutes: 8,
        },
      ],
    },
    {
      slug: "disability-support-visit",
      kind: "roleplay",
      title: "On the Visit: Disability Support Shifts",
      tagline: "Plan a shift with the person you support, follow their lead and handle changes respectfully.",
      description:
        "This course is for disability support workers who visit clients at home or in the community and want to sound natural, respectful and organised. You practise checking in at the start of a visit, asking what the person wants to do today, and supporting them to make their own decisions rather than taking over. In the first scenario a young man with a clear routine walks you through his plan for groceries and lunch. In the second, a client changes the plan at the last minute, and you need to adjust politely and check what is possible in the time you have. In the third, a client is frustrated and wants you to just do the cooking for him, so you must negotiate between his goals and his mood without sounding like a teacher. Throughout, the focus is on choice, control and plain, friendly English.",
      keywords: ["disability support", "home visits", "choice and control", "support worker", "planning a shift"],
      whatYouGet: [
        "Easy openers for checking in at the start of a support visit",
        "Questions that let the client lead the plan for the day",
        "Phrases for adjusting when plans change at the last minute",
        "Practice staying calm and supportive when someone is frustrated",
      ],
      audience: "Disability support workers and students who want confident, respectful English for one-on-one visits.",
      bannerBrief: "A support worker and a young man writing a shopping list together at a kitchen table, in soft lilac and peach gouache with rounded figures and calm window light.",
      scenarios: [
        {
          title: "Shopping list Tuesday with Liam",
          description: "You're a support worker arriving for a three-hour visit with Liam at his unit in Glenorchy. Check in, then help him plan his grocery shop and lunch the way he likes to do it.",
          difficultyLevel: "beginner",
          character: {
            name: "Liam O'Connor",
            role: "28-year-old client who lives in his own unit in Glenorchy",
            goal: "You're a friendly young man who loves routine and footy. Every Tuesday you write a shopping list, catch the bus to Northgate Fresh Market and make toasted sandwiches for lunch. You need bread, cheese, tomatoes, milk and dog food for your dog Biscuit. Your budget is $60. You like to write the list yourself and want the worker to check spelling only if you ask. If asked, you mention you want to try making pasta next week.",
            demeanor: "relaxed, upbeat, simple sentences, likes jokes, gets confused if too many questions come at once",
            openingLine: "Hey! You're the new worker, yeah? Biscuit, sit. Come in.",
            endCondition: "the learner has checked in with Liam, helped him finish his list within budget and agreed on the plan for the visit",
            voice: "ash",
          },
          learnerRole: "disability support worker on a home visit",
          taskCard: "- Greet Liam and Biscuit, and introduce yourself\n- Ask Liam what he'd like to do today\n- Help him finish his shopping list without taking over\n- Check the budget and agree on the plan and timing",
          learnerOpens: false,
          timeLimitMinutes: 5,
        },
        {
          title: "Change of plan: Priya wants the library",
          description: "You're a support worker visiting Priya, and the plan says grocery shopping from 1 pm to 3 pm. She now wants to go to the library instead, so work out together what's possible today.",
          difficultyLevel: "intermediate",
          character: {
            name: "Priya Raman",
            role: "34-year-old client who uses a wheelchair and lives in Moonah",
            goal: "You're a keen reader and the Moonah Library has a book club at 2 pm you just found out about. You want to go instead of shopping. You still need milk and bread before Thursday. You get annoyed if the worker says they need to ask someone first without explaining why. If asked, you'll suggest picking up milk at the corner store on the way home. You want the worker to check the accessible bus times with you, not for you.",
            demeanor: "bright and quick, direct, a little impatient, appreciates being treated as the decision-maker",
            openingLine: "Okay, small change. Forget shopping. There's a book club at the library at two and I'm going.",
            endCondition: "the learner has acknowledged her choice, worked through the timing and the groceries with her, and agreed on a new plan",
            voice: "coral",
          },
          learnerRole: "disability support worker on a home visit",
          taskCard: "- Respond positively to Priya's new plan\n- Check the time you have and what still needs to happen, like groceries\n- Work out transport and timing with her, not for her\n- Confirm the new plan and anything you'll note for your team",
          learnerOpens: false,
          timeLimitMinutes: 6,
        },
        {
          title: "Just do it for me: Tevita's bad day",
          description: "You're a support worker visiting Tevita, whose goal this month is cooking his own dinners. Today he's frustrated and wants you to do it all, so respond to how he feels and agree on something that works for both of you.",
          difficultyLevel: "advanced",
          character: {
            name: "Tevita Fifita",
            role: "31-year-old client who lives in a shared house in Bridgewater",
            goal: "You're usually proud of your cooking but today you got bad news: your Saturday job at Riverbend Nursery has cut your hours. You don't want to talk about cooking goals. You want the worker to make the stir-fry while you watch TV. You push back hard if they sound like a teacher. Only if asked kindly about your day do you share the news. You'll agree to help with part of the cooking, like the rice, if you feel heard.",
            demeanor: "flat and irritable at first, short answers, sighs, opens up slowly when someone listens without lecturing",
            openingLine: "Not today, bro. Can you just cook it? I'm not in the mood.",
            endCondition: "the learner has acknowledged his mood, given him space to share what's wrong and agreed on a plan for dinner he is comfortable with",
            voice: "verse",
          },
          learnerRole: "disability support worker on a home visit",
          taskCard: "- Notice Tevita's mood and ask how his day has been\n- Listen without lecturing or pushing his goals straight away\n- Offer options, like sharing the cooking or doing a smaller part\n- Agree on a plan for dinner that he is comfortable with",
          learnerOpens: false,
          timeLimitMinutes: 8,
        },
      ],
    },
    {
      slug: "shift-handover-to-a-colleague",
      kind: "roleplay",
      title: "Over to You: Shift Handover",
      tagline: "Give a clear, complete handover so the next worker knows exactly what matters.",
      description:
        "This course is for care workers who hand over to the next shift and want their verbal handover to be short, clear and complete. You practise summarising each person's shift, flagging anything that changed, passing on follow-up tasks and answering questions without guessing. In the first scenario a calm colleague listens while you hand over two residents in order. In the second, a busy colleague asks pointed questions and you realise you forgot something important, so you need to correct yourself clearly. In the third, a tired colleague pushes back on taking over a task you didn't finish, and you must explain why it's still outstanding and agree on who does what. You'll finish with a simple structure you can use on any shift: who, what changed, what to watch for, what's left to do.",
      keywords: ["shift handover", "teamwork", "care workers", "communication", "aged care"],
      whatYouGet: [
        "A simple handover structure: who, what changed, what to watch, what's left",
        "Phrases for flagging changes and concerns without sounding alarmed",
        "Practice correcting yourself when you've left something out",
        "Polite ways to agree on unfinished tasks with a colleague",
      ],
      audience: "Care and support workers who hand over to colleagues at the start or end of a shift.",
      bannerBrief: "Two care workers talking beside a nurses' station with a handover sheet between them, painted in matte lilac and peach gouache with soft afternoon light.",
      scenarios: [
        {
          title: "Afternoon handover to Grace",
          description: "You're finishing your morning shift in Banksia Wing, and Grace is starting the afternoon. Hand over two residents clearly: Mr Ellis and Mrs Doyle.",
          difficultyLevel: "beginner",
          character: {
            name: "Grace Kim",
            role: "care worker starting the afternoon shift in Banksia Wing",
            goal: "You're a calm, organised colleague who has worked in Banksia Wing for three years. You want a short handover on Mr Ellis in Room 3 and Mrs Doyle in Room 7. You ask how each person's morning went, whether they ate and drank well, and whether anything needs following up. If the learner forgets something, you gently ask, for example 'And did Mrs Doyle's daughter ring back?' You thank them and repeat the key points back.",
            demeanor: "relaxed, friendly, a good listener, asks one simple question at a time",
            endCondition: "the learner has handed over both residents, including meals, mood and any follow-ups, and Grace has repeated the key points back",
            voice: "sage",
          },
          learnerRole: "care worker finishing the morning shift",
          taskCard: "- Greet Grace and tell her you're ready to hand over\n- Give a short update on Mr Ellis: mood, meals and anything new\n- Give a short update on Mrs Doyle, including any follow-up\n- Answer her questions and check she has everything",
          learnerOpens: true,
          timeLimitMinutes: 5,
        },
        {
          title: "Wait, there's one more thing: handover to Marco",
          description: "You're handing over to Marco, who is short on time. As he asks questions, you realise you forgot to mention that a resident's daughter asked for a call back about a GP appointment.",
          difficultyLevel: "intermediate",
          character: {
            name: "Marco Bianchi",
            role: "care worker starting the evening shift in Banksia Wing",
            goal: "You're running late and want a fast handover on Rooms 1 to 6. You ask direct questions: who's unsettled, who didn't eat lunch, anything for the RN. You get slightly impatient with long stories. If the learner corrects themselves clearly, you appreciate it and ask who should make the call back to the daughter, what time she's free, and whether it's in the notes. You expect it to be written down, not just said.",
            demeanor: "quick, practical, friendly but clipped, checks his watch, likes bullet-point answers",
            openingLine: "Hey, sorry, I'm late. Give me the quick version, yeah?",
            endCondition: "the learner has given a concise handover, corrected the missed call-back clearly and agreed who will follow it up",
            voice: "ballad",
          },
          learnerRole: "care worker finishing the afternoon shift",
          taskCard: "- Give Marco a short, clear handover for your residents\n- Answer his direct questions without long stories\n- Correct yourself clearly about the missed call-back\n- Agree who will make the call and confirm it's in the notes",
          learnerOpens: false,
          timeLimitMinutes: 6,
        },
        {
          title: "That's not my job: unfinished task with Kirra",
          description: "You're ending a busy shift and didn't get to finish Mr Ellis's room check and fluid chart for the afternoon. Kirra, who is taking over, isn't happy about it, so explain clearly and agree on a fair plan.",
          difficultyLevel: "advanced",
          character: {
            name: "Kirra Walker",
            role: "senior care worker starting the night shift",
            goal: "You're tired and the night shift is short one worker. You don't want to inherit day-shift jobs. You push back: 'Why wasn't it done?' You want a clear reason, not excuses. If the learner explains honestly, for example that a resident fell and took an hour, you soften. You'll agree to finish the fluid chart if the learner stays ten minutes to do the room check, or tells the team leader. You don't accept vague answers.",
            demeanor: "blunt and tired, folded-arms energy, fair once she hears an honest reason",
            openingLine: "Hang on, the fluid chart's not done? Again? We're one short tonight.",
            endCondition: "the learner has explained why the task is unfinished, stayed calm and polite, and agreed a fair plan with Kirra for who does what",
            voice: "shimmer",
          },
          learnerRole: "care worker finishing a busy afternoon shift",
          taskCard: "- Acknowledge Kirra's frustration without getting defensive\n- Explain honestly why the task wasn't finished\n- Offer a fair solution, like staying a few minutes or telling the team leader\n- Agree clearly on who does what before you leave",
          learnerOpens: false,
          timeLimitMinutes: 8,
        },
      ],
    },
    {
      slug: "talking-with-worried-family",
      kind: "roleplay",
      title: "Families Who Care: Talking with Worried Relatives",
      tagline: "Reassure, listen and pass concerns on properly when a family member is worried.",
      description:
        "This course is for care workers who chat with residents' families during visits and want to respond with warmth and care while staying within their role. You practise giving a friendly general update, listening to a concern, saying what you can and can't share, and explaining who will follow up. In the first scenario a son visiting his mum just wants to know how her week has been. In the second, a daughter notices a bruise on her father's arm, and you need to stay calm, avoid guessing, and pass it on to the right person. In the third, an upset son demands answers about his mother's weight loss and threatens to complain, and you must stay respectful, avoid blaming anyone and arrange a proper conversation with the nurse or manager. You'll build phrases that sound caring without promising things you can't deliver.",
      keywords: ["family communication", "aged care", "concerns", "reassurance", "escalation", "complaints"],
      whatYouGet: [
        "Friendly ways to give a general update to a visiting relative",
        "Phrases for saying what's outside your role without sounding cold",
        "Practice passing a concern on to the nurse or manager properly",
        "Calm language for an upset relative who wants answers now",
      ],
      audience: "Aged-care and support workers who regularly meet residents' families during visiting hours.",
      bannerBrief: "A care worker and a worried middle-aged man talking quietly in a lounge with lilac armchairs, painted in soft peach gouache with gentle afternoon light.",
      scenarios: [
        {
          title: "How's Mum been? A visit from Michael",
          description: "You're a care worker at Wattle Grove Aged Care, and Michael is visiting his mum, Mrs Chen, on Saturday afternoon. Give him a friendly update on her week.",
          difficultyLevel: "beginner",
          character: {
            name: "Michael Chen",
            role: "son visiting his mother at Wattle Grove Aged Care",
            goal: "You're a polite accountant who visits your mum every Saturday at 2 pm. You want a general update: is she eating, joining activities, sleeping okay, and is she happy? You ask whether she went to Wednesday's music afternoon. You're relaxed and grateful. If asked, you mention you've brought her favourite custard tarts and want to know if that's okay. You also ask when the next family meeting is.",
            demeanor: "gentle and appreciative, speaks clearly, nods along, asks simple questions",
            openingLine: "Hi there. I'm Michael, Mrs Chen's son. How's Mum been this week?",
            endCondition: "the learner has given a general update on his mum's week, answered his questions and told him who to ask about the family meeting",
            voice: "cedar",
          },
          learnerRole: "care worker at an aged-care home",
          taskCard: "- Greet Michael and introduce yourself\n- Give a friendly general update on his mum's week\n- Answer his question about the food he's brought\n- Tell him who to ask about the next family meeting",
          learnerOpens: false,
          timeLimitMinutes: 5,
        },
        {
          title: "Where did this bruise come from? Fatima asks",
          description: "You're a care worker, and Fatima has just noticed a bruise on her father's forearm during her visit. You don't know how it happened, so respond calmly and make sure it's followed up properly.",
          difficultyLevel: "intermediate",
          character: {
            name: "Fatima Haddad",
            role: "daughter of a resident at Wattle Grove Aged Care",
            goal: "You're worried but reasonable. You noticed a purple bruise on your dad Youssef's left forearm and want to know what happened. You ask if he fell, if anyone saw it, and whether the nurse knows. If the worker guesses, you get more worried. You calm down if they say honestly they don't know yet, will tell the registered nurse now and that the nurse will call you. You want a time for that call and you give your mobile.",
            demeanor: "anxious, speaks a little fast, asks follow-up questions, relieved by honesty and a clear plan",
            openingLine: "Excuse me, sorry. Have you seen Dad's arm? There's a big bruise. What happened?",
            endCondition: "the learner has acknowledged her concern, avoided guessing, explained it will go to the nurse now and agreed when she'll be contacted",
            voice: "marin",
          },
          learnerRole: "care worker at an aged-care home",
          taskCard: "- Acknowledge Fatima's worry and thank her for telling you\n- Be honest about what you do and don't know, without guessing\n- Explain that you'll report it to the nurse straight away\n- Agree on how and when she'll hear back",
          learnerOpens: false,
          timeLimitMinutes: 6,
        },
        {
          title: "Why has nobody told me? George is upset",
          description: "You're a care worker, and George is upset that his mother, Mrs Antoniou, has lost weight. He wants answers from you right now and mentions making a complaint, so stay calm and arrange a proper conversation.",
          difficultyLevel: "advanced",
          character: {
            name: "George Antoniou",
            role: "son of a resident at Wattle Grove Aged Care",
            goal: "You're angry because your mum's clothes are loose and nobody rang you. You demand to know who's watching what she eats and say you'll complain. You test whether the worker blames others or makes excuses. You calm down only if they listen, take you seriously and arrange a talk with the RN or manager today. If asked, you reveal mum never liked the soft food and used to love lemon soup. You want her preferences written down.",
            demeanor: "loud and frustrated, interrupts, repeats 'nobody told me', softens slowly when he feels heard",
            openingLine: "Look at her! She's lost so much weight. Why has nobody rung me about this?",
            endCondition: "the learner has stayed calm, acknowledged his concern without blaming anyone, noted his mother's food preferences and arranged a conversation with the nurse or manager",
            voice: "ash",
          },
          learnerRole: "care worker at an aged-care home",
          taskCard: "- Stay calm and let George say what's worrying him\n- Acknowledge his feelings without blaming colleagues or making excuses\n- Ask about his mum's food likes and dislikes and say you'll pass them on\n- Arrange for him to speak with the nurse or manager, and explain how to raise a complaint if he wants to",
          learnerOpens: false,
          timeLimitMinutes: 8,
        },
      ],
    },
    {
      slug: "when-a-resident-says-no",
      kind: "roleplay",
      title: "When Someone Says No: Meals and Activities",
      tagline: "Respond to a refusal with curiosity and respect, then find a choice that works.",
      description:
        "This course is for care workers who want better English for the moment a resident says no to a meal, a drink or an activity. You practise asking open questions, offering alternatives, respecting the person's right to decide and knowing when to pass a concern on. In the first scenario a resident simply isn't hungry at lunch, and you find something small he'd enjoy. In the second, a resident refuses the exercise group, and you discover the real reason with gentle questions. In the third, a resident refuses dinner several nights in a row and is clearly upset, and you need to find out what's going on, respect his wishes and decide what to report. These conversations are about dignity: the goal is never to make someone comply, but to understand, offer choices and keep the team informed.",
      keywords: ["refusal of care", "dignity", "meals", "activities", "aged care", "person-centred care"],
      whatYouGet: [
        "Open questions for finding out why someone says no",
        "Phrases for offering alternatives without pressure",
        "Language that respects a person's right to choose",
        "Practice deciding what to report to the nurse or team leader",
      ],
      audience: "Care workers in residential aged care who want respectful, confident responses when a resident declines.",
      bannerBrief: "A care worker crouching beside an older man at a dining table with a covered plate, painted in soft lilac and peach gouache with calm, rounded shapes.",
      scenarios: [
        {
          title: "Not hungry today: lunch with Bill",
          description: "You're a care worker in the dining room at lunchtime, and Bill has pushed away his plate of shepherd's pie. Find out if he'd like something else.",
          difficultyLevel: "beginner",
          character: {
            name: "Bill Dawson",
            role: "88-year-old resident and retired Tasmanian ferry engineer",
            goal: "You're a gentle, quiet man. You had a big morning tea with your nephew at 10.30, so you're not hungry. You don't want the shepherd's pie. If offered choices, you'd take a small bowl of tomato soup or a sandwich later at 3 pm. You like a cup of tea with two sugars. You appreciate being asked, not nagged. If asked, you mention your nephew brought scones.",
            demeanor: "soft-spoken, slow, polite, a little hard of hearing so likes short, clear questions",
            openingLine: "No thanks, love. I couldn't eat a thing.",
            endCondition: "the learner has asked why he isn't eating, offered at least one alternative and agreed what he'd like and when",
            voice: "ballad",
          },
          learnerRole: "care worker in the dining room",
          taskCard: "- Ask Bill kindly why he doesn't feel like lunch\n- Offer him a lighter option or a later time\n- Ask what he'd like to drink\n- Confirm what you'll bring and when",
          learnerOpens: false,
          timeLimitMinutes: 5,
        },
        {
          title: "No exercise group for me: Rosa holds back",
          description: "You're a care worker inviting residents to the 10 am chair exercise group in the lounge. Rosa says no, so find out why and see whether anything would help.",
          difficultyLevel: "intermediate",
          character: {
            name: "Rosa Ferraro",
            role: "81-year-old resident and keen gardener",
            goal: "You say you're too tired for the exercise group. The real reason is that you can't hear the instructor over the music and you felt silly last week when you did the wrong move. You only reveal this if asked gently and openly. You'd go if you could sit near the front and the music was turned down, or you'd prefer helping in the courtyard garden at 11 am instead. You don't want a fuss made in front of others.",
            demeanor: "polite, a bit embarrassed, changes the subject, opens up when spoken to privately and kindly",
            openingLine: "Oh, not today, darling. I'm too tired for all that jumping around.",
            endCondition: "the learner has gently found the real reason, offered a practical solution or alternative and respected her final choice",
            voice: "coral",
          },
          learnerRole: "care worker running the morning activities",
          taskCard: "- Accept her answer and gently ask what she thinks of the group\n- Use open questions to find the real reason\n- Offer practical options, like a different seat or another activity\n- Respect her final choice and say you'll pass on any changes",
          learnerOpens: false,
          timeLimitMinutes: 6,
        },
        {
          title: "Dinner untouched again: Khalid's reason",
          description: "You're a care worker on the evening shift, and Khalid has refused dinner for three nights. He's upset and wants to be left alone, so listen, respect his wishes and work out what needs reporting.",
          difficultyLevel: "advanced",
          character: {
            name: "Khalid Mansour",
            role: "74-year-old resident who moved in two weeks ago",
            goal: "You're new, homesick and fed up. You tell the worker to leave you alone. You've stopped eating dinner because you're not sure the meat is halal and you feel embarrassed to keep asking. Only if the worker is patient and asks respectfully do you say this. You want someone to check with the kitchen and you'd like your son Omar to bring meals on Fridays. You'll accept fruit and yoghurt tonight if offered.",
            demeanor: "short-tempered at first, sighs, says 'it doesn't matter', becomes warmer once he feels respected",
            openingLine: "Take it away. I told the other one, I don't want it. Just leave me.",
            endCondition: "the learner has respected his refusal, gently found out the reason, offered a suitable option for tonight and explained they'll pass it on to the nurse and kitchen",
            voice: "verse",
          },
          learnerRole: "care worker on the evening shift",
          taskCard: "- Respect Khalid's refusal and don't pressure him to eat\n- Show you're willing to listen and ask, gently, what's behind it\n- Offer a suitable option for tonight\n- Explain what you'll pass on to the nurse and kitchen, and check he's okay with that",
          learnerOpens: false,
          timeLimitMinutes: 8,
        },
      ],
    },
    {
      slug: "reporting-a-fall-or-incident",
      kind: "roleplay",
      title: "Speak Up: Reporting a Fall or Incident",
      tagline: "Report what you saw, in order, with facts not guesses, and own your part honestly.",
      description:
        "This course is for care workers who need to report a fall or incident to a supervisor and want to do it clearly and accurately. You practise describing what happened in time order, separating what you saw from what you were told, saying what you did straight afterwards, and answering follow-up questions without guessing. In the first scenario a calm supervisor walks you through a simple report of a resident who slipped in the bathroom. In the second, a supervisor notices a gap in your timeline, and you need to clarify exactly when you found the resident. In the third, you realise a walking frame was left out of reach, and you must report your part honestly to a busy supervisor who wants the full picture. The focus is on factual, objective language and taking responsibility calmly.",
      keywords: ["incident reporting", "falls", "supervisor", "objective language", "aged care", "accountability"],
      whatYouGet: [
        "A clear order for reporting: when, where, what you saw, what you did",
        "Phrases for separating facts from what you were told",
        "Practice answering 'what time exactly?' without guessing",
        "Calm, honest language for owning a mistake",
      ],
      audience: "Care and support workers who may need to report falls, injuries or near misses to a supervisor.",
      bannerBrief: "A care worker speaking with a supervisor holding a clipboard in a quiet corridor, painted in soft matte lilac and peach gouache with calm light.",
      scenarios: [
        {
          title: "A slip in the bathroom: telling Joanne",
          description: "You're a care worker, and ten minutes ago Mrs Patterson slid from the shower chair to the floor while you were helping her. She's now resting and the nurse has checked her, so report it to your supervisor, Joanne.",
          difficultyLevel: "beginner",
          character: {
            name: "Joanne Clarke",
            role: "care supervisor at Wattle Grove Aged Care",
            goal: "You're calm and supportive. You want a clear verbal report before the learner fills in the incident form. You ask: what time, where, what you saw, whether she hit her head, what you did next, and who you told. You praise clear answers. If the learner says something unclear, you ask them to say it again simply. You remind them to fill in the incident form before the end of the shift and to write only what they saw.",
            demeanor: "steady and warm, unhurried, asks one question at a time, encouraging",
            openingLine: "Thanks for coming to find me. Take a breath. Tell me what happened with Mrs Patterson.",
            endCondition: "the learner has reported the time, place, what they saw, what they did and who they told, and Joanne has explained the next step",
            voice: "sage",
          },
          learnerRole: "care worker reporting an incident",
          taskCard: "- Tell Joanne what happened, in time order\n- Say what you saw and what you did straight after\n- Answer her questions clearly and don't guess\n- Confirm the next step, like the incident form",
          learnerOpens: false,
          timeLimitMinutes: 5,
        },
        {
          title: "Minding the gap: Rajesh checks your timeline",
          description: "You're a care worker who found Mr Ellis sitting on his bedroom floor this afternoon. Your supervisor Rajesh notices your times don't add up, so clarify exactly what you saw and when.",
          difficultyLevel: "intermediate",
          character: {
            name: "Rajesh Patel",
            role: "clinical team leader on the afternoon shift",
            goal: "You're thorough and fair. You want the exact time the learner last saw Mr Ellis, the time they found him on the floor, and when they called for help. If the times are vague, you point out the gap: 'You said 2.15 and then 2.45, what happened between?' You want them to separate what they saw from what Mr Ellis told them. If asked, you explain that family will be called by the RN, not the care worker.",
            demeanor: "precise, calm, asks clarifying questions, never rude but won't accept 'around about'",
            openingLine: "Right. Let's go through it step by step. When did you last see Mr Ellis before you found him?",
            endCondition: "the learner has given a clear timeline, explained any gap honestly and separated what they saw from what they were told",
            voice: "cedar",
          },
          learnerRole: "care worker reporting an incident",
          taskCard: "- Give Rajesh the times you last saw and then found Mr Ellis\n- Explain any gap in your timeline honestly\n- Separate what you saw from what Mr Ellis told you\n- Check who will contact the family and what you need to write",
          learnerOpens: false,
          timeLimitMinutes: 6,
        },
        {
          title: "My part in it: reporting to Melissa",
          description: "You're a care worker, and Mrs Doyle fell reaching for her walking frame, which you'd moved to the corner to vacuum and forgot to put back. She's sore but okay, so report this honestly to your busy supervisor, Melissa.",
          difficultyLevel: "advanced",
          character: {
            name: "Melissa Brennan",
            role: "facility manager at Wattle Grove Aged Care",
            goal: "You're busy, on your way to a meeting, and want the facts fast. You ask where the frame was and why. If the learner is vague or blames the resident, you press harder. If they admit their part clearly and calmly, you respect it and say it's how the team learns. You want to know what they did after the fall and what they'd do differently. You remind them the incident form must include where the frame was.",
            demeanor: "brisk and serious, direct questions, impatient with excuses, fair and respectful toward honesty",
            openingLine: "I've got five minutes. Tell me about Mrs Doyle. What happened?",
            endCondition: "the learner has reported the fall factually, clearly admitted moving the frame, explained what they did afterwards and what they'll do differently",
            voice: "shimmer",
          },
          learnerRole: "care worker reporting an incident",
          taskCard: "- Report the fall clearly and in order, even though Melissa is rushed\n- Explain honestly that you moved the walking frame\n- Don't blame Mrs Doyle or make excuses\n- Say what you did afterwards and what you'll do differently",
          learnerOpens: false,
          timeLimitMinutes: 8,
        },
      ],
    },
    {
      slug: "phone-calls-to-client-families",
      kind: "roleplay",
      title: "On the Line: Phone Calls to Client Families",
      tagline: "Make clear, friendly calls to families, with no body language to help you.",
      description:
        "This course is for home-care and support workers who ring clients' families and want to sound clear and professional on the phone. You practise introducing yourself and your organisation, explaining why you're calling, checking you're talking to the right person and confirming details at the end. In the first scenario you ring a daughter to confirm her mum's appointment times for next week. In the second, you call to let a son know his dad seems unwell and skipped lunch, and you must explain without alarming him and answer his questions. In the third, you call a daughter at work about a change to her mother's visit times, and she is unhappy with the change and the timing of your call, so you need to stay polite, explain the reason and offer options. Phone calls are hard in a second language; these scenarios help you slow down and stay clear.",
      keywords: ["phone calls", "family contact", "home care", "telephone english", "support worker"],
      whatYouGet: [
        "A simple script for starting a work call and stating its purpose",
        "Phrases for checking and confirming details on the phone",
        "Practice sharing a concern without causing alarm",
        "Calm language for an unhappy caller",
      ],
      audience: "Home-care and disability support workers who need to phone clients' families.",
      bannerBrief: "A care worker on a phone at a small desk with a lilac notebook, painted in soft peach gouache with gentle rounded shapes and calm window light.",
      scenarios: [
        {
          title: "Confirming next week with Thuy",
          description: "You're a home-care worker with Southern Hearth Home Care. Ring Thuy to confirm her mother's support times for next week and check if anything has changed.",
          difficultyLevel: "beginner",
          character: {
            name: "Thuy Tran",
            role: "daughter of a home-care client in Kingston",
            goal: "You're friendly and organised. Your mum, Mrs Tran, has visits Monday and Thursday at 9 am. You want to confirm those times. You ask if the same worker is coming. If asked about changes, you say Mum has a hearing test on Thursday at 11 am, so the 9 am visit is still fine but should finish by 10.15. You ask the worker to spell their name and give the office number.",
            demeanor: "warm, organised, speaks clearly, a little busy but patient",
            openingLine: "Hello, Thuy speaking.",
            endCondition: "the learner has introduced themselves, confirmed both visit times, noted the Thursday appointment and given their name and contact details",
            voice: "coral",
          },
          learnerRole: "home-care worker making a phone call",
          taskCard: "- Introduce yourself and your organisation, and check you're speaking to Thuy\n- Explain why you're calling\n- Confirm next week's visit times and ask if anything has changed\n- Repeat the details back and give your name and contact number",
          learnerOpens: false,
          timeLimitMinutes: 5,
        },
        {
          title: "Dad's not himself: calling Peter",
          description: "You're a home-care worker visiting Mr Lowe, who seems more tired than usual and didn't eat his lunch. You've already rung your coordinator, who asked you to let his son Peter know, so make the call.",
          difficultyLevel: "intermediate",
          character: {
            name: "Peter Lowe",
            role: "son of a home-care client in Sandy Bay",
            goal: "You're a builder on a job site. When you hear 'calling about your dad' you get worried fast. You ask: is he okay, is it serious, should you leave work now? You want facts, not guesses. If the worker stays calm and explains what they saw and that the coordinator knows, you settle down. If asked, you say Dad didn't sleep well because of a storm. You decide to call in after work at 4.30 pm.",
            demeanor: "worried, noisy background, asks quick questions, calms down with clear facts",
            openingLine: "Yeah, Peter here. Sorry, it's loud, I'm on site.",
            endCondition: "the learner has explained what they noticed calmly, answered his questions without guessing and agreed on next steps",
            voice: "ash",
          },
          learnerRole: "home-care worker making a phone call",
          taskCard: "- Introduce yourself and reassure Peter early that it isn't an emergency call\n- Describe what you noticed, using facts not guesses\n- Answer his questions and say who else knows\n- Agree on next steps and confirm what will happen",
          learnerOpens: false,
          timeLimitMinutes: 6,
        },
        {
          title: "Not a good time: Leilani and the new roster",
          description: "You're a home-care worker calling Leilani, whose mother's Wednesday visit is moving from 10 am to 1 pm because of staffing changes. She's at work and unhappy, so explain clearly and offer workable options.",
          difficultyLevel: "advanced",
          character: {
            name: "Leilani Tupou",
            role: "daughter of a home-care client in New Town",
            goal: "You're a busy nurse on a short break. You're annoyed: your mum has her community choir at 1 pm on Wednesdays and loves it. You say this is the second change this month. You ask why, and whether anyone thought about Mum. You won't accept 'that's just the roster'. You'd agree to an 8.30 am visit or moving it to Thursday at 10 am, if the worker checks with the office and calls back by 5 pm today.",
            demeanor: "clipped and frustrated, interrupts, polite underneath, values being listened to",
            openingLine: "Leilani speaking. I've only got a few minutes, what's this about?",
            endCondition: "the learner has explained the change, acknowledged her frustration, offered or noted alternative times and agreed when they'll call back",
            voice: "marin",
          },
          learnerRole: "home-care worker making a phone call",
          taskCard: "- Introduce yourself and get to the point quickly\n- Explain the change and the reason in plain words\n- Acknowledge her frustration and ask what matters to her mum\n- Offer to check alternative times and agree when you'll call back",
          learnerOpens: false,
          timeLimitMinutes: 8,
        },
      ],
    },
    {
      slug: "community-outing-support",
      kind: "roleplay",
      title: "Out and About: Supporting a Community Outing",
      tagline: "Support someone out in the community while they stay in charge of their day.",
      description:
        "This course is for support workers who take clients out into the community and want to communicate naturally on the move. You practise planning an outing together, checking on comfort and energy, handling small problems and supporting someone's right to make their own choices. In the first scenario you head to the Saturday market with a cheerful client who knows exactly what he wants. In the second, the bus home is cancelled, and you need to explain the options and decide together what to do. In the third, a client wants to stop at the pub for a beer although her daughter has asked that she doesn't, so you must respect her choice, talk through any risks honestly and decide what to tell the team. These scenarios balance safety with the dignity of making your own decisions.",
      keywords: ["community access", "outings", "support worker", "dignity of risk", "problem solving"],
      whatYouGet: [
        "Phrases for planning an outing with someone, not for them",
        "Easy check-ins about comfort, energy and timing",
        "Practice explaining options when plans go wrong",
        "Respectful language for talking through risk and choice",
      ],
      audience: "Disability and aged-care support workers who accompany clients to shops, markets, appointments and events.",
      bannerBrief: "A support worker walking beside an older man with a walking stick through a sunny waterfront market, in soft lilac and peach gouache with rounded figures.",
      scenarios: [
        {
          title: "Market morning with Arthur",
          description: "You're a support worker taking Arthur to the Saturday waterfront market in Hobart. Plan the outing with him and check how he's going as you walk around.",
          difficultyLevel: "beginner",
          character: {
            name: "Arthur Pemberton",
            role: "82-year-old client who loves the Saturday market",
            goal: "You're a retired postman who knows everyone at the market. You want to buy apples from the Huon Valley stall, a loaf of sourdough and some fudge for your granddaughter. You have $40 cash. You like to rest on a bench after about 30 minutes. If asked, you say you'd like a flat white before heading home at 11.30 am. You enjoy friendly chat about the stalls.",
            demeanor: "cheerful and chatty, slow walker, tells little stories, happy to be asked how he's going",
            openingLine: "Lovely day for it! Right, I've got my list. Shall we?",
            endCondition: "the learner has planned the stops with him, checked his comfort and agreed what time to head home",
            voice: "ballad",
          },
          learnerRole: "support worker on a community outing",
          taskCard: "- Ask Arthur what he'd like to do at the market\n- Plan the stops together and check his budget\n- Check in about his comfort and when he'd like a rest\n- Agree on a time to head home",
          learnerOpens: false,
          timeLimitMinutes: 5,
        },
        {
          title: "Bus cancelled: deciding with Joon-ho",
          description: "You're a support worker with Joon-ho after his swimming session at the aquatic centre. The 3.10 pm bus home has been cancelled, so explain the options and decide together.",
          difficultyLevel: "intermediate",
          character: {
            name: "Joon-ho Park",
            role: "26-year-old client who uses public transport with support",
            goal: "You're tired after swimming and get anxious when plans change. The next bus is at 3.55 pm. A taxi would cost about $25 and you'd pay. Your mum expects you home by 4.30 pm. You ask what happens now and whether you'll be late. You calm down if the worker explains slowly. If asked, you say you'd like to wait at the cafe and text Mum yourself. You don't want the worker deciding for you.",
            demeanor: "quiet and a little anxious, asks the same question twice, settles with calm, clear steps",
            openingLine: "Wait, it says cancelled? What do we do? Are we going to be late?",
            endCondition: "the learner has explained the options clearly and calmly, and Joon-ho has chosen what to do and who to tell",
            voice: "verse",
          },
          learnerRole: "support worker on a community outing",
          taskCard: "- Stay calm and explain what has happened in simple words\n- Give Joon-ho the options, with times and costs\n- Let him choose and support his decision\n- Agree on who will let his mum know",
          learnerOpens: false,
          timeLimitMinutes: 6,
        },
        {
          title: "Just one beer: Maureen's choice",
          description: "You're a support worker on an outing with Maureen, who wants to stop at the Lenah Hotel for a beer. Her daughter told the agency she'd rather Maureen didn't drink, so respect Maureen's choice while talking through it honestly.",
          difficultyLevel: "advanced",
          character: {
            name: "Maureen Kelly",
            role: "70-year-old client who lives independently in Lindisfarne",
            goal: "You're a sharp, funny retired publican. You want one cold beer at the pub like you've done every Friday for forty years. You know your daughter Sharon worries, and you're sick of being treated like a child. You push back hard if the worker says 'you're not allowed'. If they ask respectfully, you agree to one beer with food and a lift home by 3 pm. You want the worker to tell Sharon the truth, not hide it.",
            demeanor: "witty and fiery, teases, firm about her rights, respects straight talk",
            openingLine: "Right, we're stopping at the Lenah for a beer. Don't give me that look.",
            endCondition: "the learner has respected that the choice is Maureen's, discussed any risks honestly, agreed a plan and explained what they'll record and pass on",
            voice: "sage",
          },
          learnerRole: "support worker on a community outing",
          taskCard: "- Acknowledge that it's Maureen's decision\n- Mention her daughter's concern honestly, without taking sides\n- Talk through any risks and agree a plan together\n- Explain what you'll record and who you'll tell",
          learnerOpens: false,
          timeLimitMinutes: 8,
        },
      ],
    },
    {
      slug: "home-care-first-visit",
      kind: "roleplay",
      title: "First Visit: Starting Home Care with a New Client",
      tagline: "Build trust on the doorstep, learn how someone likes things done and ask before you help.",
      description:
        "This course is for home-care workers meeting a new client for the first time and wanting to make a calm, trustworthy first impression. You practise introducing yourself at the door, showing ID, asking how the person likes things done, and checking consent before starting any task. In the first scenario a welcoming client shows you around and tells you about her routine. In the second, a client wasn't expecting you and is wary of letting a stranger in, so you need to explain who you are and suggest a way to check. In the third, an older man says he doesn't need help at all and only agreed because his daughter arranged it, and you must listen, respect his say over his own home and build enough trust to agree on a small start. You'll practise sounding warm, patient and professional on day one.",
      keywords: ["home care", "first visit", "building trust", "consent", "new client", "introductions"],
      whatYouGet: [
        "A friendly doorstep introduction, including showing ID",
        "Questions for learning how someone likes things done at home",
        "Practice handling a client who is wary of strangers",
        "Respectful ways to start small with a reluctant client",
      ],
      audience: "Home-care and community support workers who regularly meet new clients in their homes.",
      bannerBrief: "A care worker smiling at the front door of a little weatherboard cottage while an older woman opens it, in soft matte lilac and peach gouache with calm morning light.",
      scenarios: [
        {
          title: "Welcome in: meeting Eleni",
          description: "You're a home-care worker from Southern Hearth Home Care on your first visit to Eleni in Moonah. Introduce yourself, then learn how she likes her home and routine.",
          difficultyLevel: "beginner",
          character: {
            name: "Eleni Georgiou",
            role: "77-year-old new home-care client in Moonah",
            goal: "You're warm and talkative and expecting the worker at 10 am. You'd like help with vacuuming, changing your bed linen and a trip to the chemist each fortnight. You like the vacuum put back in the hall cupboard and shoes off on the good rug. If asked, you mention your cat Bella hides from strangers and your son Nick rings every afternoon. You offer the worker a coffee.",
            demeanor: "chatty and welcoming, mixes stories with instructions, laughs easily",
            endCondition: "the learner has introduced themselves, shown ID, asked how she likes things done and agreed on what they'll help with today",
            voice: "shimmer",
          },
          learnerRole: "home-care worker on a first visit",
          taskCard: "- Introduce yourself and your organisation, and offer your ID\n- Ask Eleni what she'd like help with\n- Ask how she likes things done in her home\n- Agree on what you'll do today",
          learnerOpens: true,
          timeLimitMinutes: 5,
        },
        {
          title: "Who sent you? Frank at the screen door",
          description: "You're a home-care worker arriving for a first visit to Frank in Claremont. He wasn't expecting anyone today and won't open the screen door, so explain who you are and help him check.",
          difficultyLevel: "intermediate",
          character: {
            name: "Frank Russo",
            role: "83-year-old new home-care client in Claremont",
            goal: "You're cautious because a man knocked last month pretending to be from the council. You thought visits started next week. You want to see ID through the screen and hear who arranged this. You won't let the worker in until you've checked. If they suggest you ring the office yourself on the number in your welcome letter, you do, then relax. You need help taking the bins out and changing a light globe.",
            demeanor: "suspicious, gruff, short questions, becomes friendly once he feels safe and in control",
            openingLine: "Yeah? Who are you? I'm not buying anything.",
            endCondition: "the learner has explained who they are, shown ID, suggested a way for Frank to check, and he has agreed to start the visit",
            voice: "cedar",
          },
          learnerRole: "home-care worker on a first visit",
          taskCard: "- Introduce yourself calmly and explain why you're there\n- Offer ID and suggest a way for Frank to check with the office\n- Respect his right to say no or wait\n- Once he's comfortable, ask what he'd like help with",
          learnerOpens: false,
          timeLimitMinutes: 6,
        },
        {
          title: "I don't need help: Desmond's terms",
          description: "You're a home-care worker on your first visit to Desmond in Rosny. His daughter arranged the service, but he says he doesn't need anyone, so listen, respect his say and see if you can agree on a small start.",
          difficultyLevel: "advanced",
          character: {
            name: "Desmond Hughes",
            role: "86-year-old new home-care client in Rosny",
            goal: "You're a proud widower and former carpenter. You only agreed because your daughter Claire worried after you slipped in the garden. You say you don't need anyone. You test whether the worker listens or just follows a plan. You hate people moving your things. If asked what's hard lately, you admit hanging washing and carrying shopping from the car hurt your back. You'll agree to a trial of washing help only.",
            demeanor: "polite but cool, dry humour, folded arms, short answers until he feels respected",
            openingLine: "Look, you seem nice, but I'll tell you now, I don't need help. This was Claire's idea.",
            endCondition: "the learner has listened to his view, asked what has been hard lately, respected his limits and agreed on a small trial he is happy with",
            voice: "ash",
          },
          learnerRole: "home-care worker on a first visit",
          taskCard: "- Acknowledge Desmond's feelings and that it's his home and his choice\n- Ask open questions about his day-to-day life\n- Avoid pushing the full care plan\n- Agree on one small thing to try, and check he consents",
          learnerOpens: false,
          timeLimitMinutes: 8,
        },
      ],
    },
    {
      slug: "end-of-shift-notes",
      kind: "roleplay",
      title: "Clear Notes: End-of-Shift Progress Notes",
      tagline: "Talk through your shift notes so they're factual, specific and useful to the next person.",
      description:
        "This course is for care and support workers who write progress notes and want to discuss them confidently with team leaders and nurses. You practise describing what happened in a shift, choosing objective words instead of opinions, adding specific times and details, and standing by what you've written. In the first scenario a team leader goes through your notes and asks simple clarifying questions. In the second, a registered nurse says your notes are too vague, like 'was fine' or 'seemed upset', and helps you rewrite them with facts. In the third, a colleague asks you to add something to your notes that you didn't see yourself, and you must politely decline and suggest the right way to record it. You'll learn to speak and write about care in a way that protects both the person and you.",
      keywords: ["progress notes", "documentation", "objective language", "care workers", "team leader", "integrity"],
      whatYouGet: [
        "Ways to describe a shift clearly and in order",
        "Objective words to replace vague phrases like 'was fine'",
        "Practice adding times and specific details on the spot",
        "Polite, firm language for saying no to writing what you didn't see",
      ],
      audience: "Care and support workers who write daily progress notes and discuss them with team leaders or nurses.",
      bannerBrief: "A care worker and a team leader reading a notes folder together at a small table, in soft lilac and peach gouache with matte texture and calm evening light.",
      scenarios: [
        {
          title: "Going through notes with Natalie",
          description: "You're a support worker finishing an afternoon shift at Banksia Wing. Your team leader, Natalie, wants to quickly go through your progress notes for Mrs Doyle.",
          difficultyLevel: "beginner",
          character: {
            name: "Natalie Ward",
            role: "team leader in Banksia Wing",
            goal: "You're friendly and supportive. You want to hear how Mrs Doyle's afternoon went and check the notes match. You ask what she ate at dinner, whether she had visitors, how she seemed, and whether anything was unusual. If the learner gives a good detail, you say 'great, put that in'. If asked, you explain that notes should say what happened, when, and what you did.",
            demeanor: "friendly and relaxed, asks simple questions, gives small compliments",
            openingLine: "Hey, got a sec before you go? Let's run through your notes for Mrs Doyle.",
            endCondition: "the learner has described Mrs Doyle's afternoon clearly, answered Natalie's questions and confirmed what's in the notes",
            voice: "marin",
          },
          learnerRole: "support worker finishing an afternoon shift",
          taskCard: "- Describe Mrs Doyle's afternoon in order\n- Answer Natalie's questions about meals, visitors and mood\n- Add any specific detail she asks for\n- Confirm what's written in your notes",
          learnerOpens: false,
          timeLimitMinutes: 5,
        },
        {
          title: "\"Was fine\" isn't enough: notes with Samuel",
          description: "You're a care worker, and the registered nurse, Samuel, has read your note that says Mr Ellis 'was fine, seemed a bit upset later'. Work with him to make it specific and factual.",
          difficultyLevel: "intermediate",
          character: {
            name: "Samuel Mensah",
            role: "registered nurse on the afternoon shift",
            goal: "You're patient but particular. You want notes another worker could act on. You ask what 'fine' means: did he eat, walk, chat? What did 'upset' look like, at what time, and what did the learner do? If the learner gives facts, like 'at 4 pm he was calling out for his wife', you help them phrase it. If asked, you explain why opinions like 'difficult' don't belong in notes.",
            demeanor: "calm, teacherly, curious questions, praises improvement, never harsh",
            openingLine: "Thanks for your notes. Can I ask, when you say Mr Ellis 'was fine', what did that look like?",
            endCondition: "the learner has replaced vague words with specific facts, including times, what they saw and what they did",
            voice: "verse",
          },
          learnerRole: "care worker reviewing notes with a nurse",
          taskCard: "- Explain what you meant by 'fine' using facts\n- Describe what 'upset' looked like, with a time\n- Say what you did in response\n- Agree on clearer wording for the note",
          learnerOpens: false,
          timeLimitMinutes: 6,
        },
        {
          title: "Can you just add it? Saying no to Bianca",
          description: "You're a care worker writing your end-of-shift notes. Your colleague Bianca asks you to write that you saw Mrs Patterson have her 2 pm drink, but you were on break, so politely decline and suggest the right way to record it.",
          difficultyLevel: "advanced",
          character: {
            name: "Bianca Lucas",
            role: "care worker on the same afternoon shift",
            goal: "You're a likeable colleague who's stressed and running late for school pick-up. You gave Mrs Patterson her drink at 2 pm but forgot to chart it. You ask the learner to write it in their notes because 'it's the same thing'. You push back: 'Don't make it a big deal'. If the learner stays friendly and firm, you accept writing it yourself or adding a late entry with your name, and you thank them.",
            demeanor: "friendly, rushed, a bit pushy, uses 'mate' and 'come on', respects firm kindness",
            openingLine: "Hey, quick favour. Can you pop in your notes that Mrs Patterson had her drink at two? I'm so late.",
            endCondition: "the learner has politely declined to record what they didn't see, explained why, and Bianca has agreed to record it herself",
            voice: "sage",
          },
          learnerRole: "care worker finishing an afternoon shift",
          taskCard: "- Stay friendly and acknowledge that Bianca is rushed\n- Politely decline to write something you didn't see\n- Explain why, simply and without lecturing\n- Suggest she records it herself, such as with a late entry under her name",
          learnerOpens: false,
          timeLimitMinutes: 8,
        },
      ],
    },
  ],
};

