import type { OriginalCreator } from "./types";

export const lastOrdersAcademy: OriginalCreator = {
  handle: "last-orders-academy",
  displayName: "Last Orders Academy",
  tagline: "Speaking practice for hospitality staff: orders, bookings, allergies, complaints and the bar, from first shift to last call.",
  bio: "Last Orders Academy is a XINGO Original studio for people who work, or want to work, in Australian hospitality. You play the staff member: the barista, the waiter, the bartender, the person who picks up the phone when a booking comes in. Our characters are the customers, chefs and managers you will meet on a real shift, from the regular who wants the usual to the diner with a serious allergy and the guest who has had one too many. Each course starts with a calm, predictable conversation and builds to the moments that test you: a sold-out dish, a complaint at the table, a polite but firm no. Practise the words before the pressure is on, so your next shift feels a little easier. Brisbane-made, Australian English throughout.",
  location: "Brisbane, QLD",
  accent: "#6D28D9",
  visualStyle: "Neon line art on deep navy: glowing single-weight strokes in violet and pink neon with a soft halo, simple bar-sign shapes and lots of dark negative space.",
  logoBrief: "A glowing violet neon outline of a tilted cocktail glass inside a rounded bar-sign frame, with the words Last Orders in pink neon script on deep navy.",
  avatarBrief: "A single-weight pink and violet neon outline of a coffee cup and a beer glass side by side, glowing softly in a circle on deep navy.",
  courses: [
    {
      slug: "cafe-counter-orders",
      kind: "roleplay",
      title: "Cafe Counter: Taking Orders",
      tagline: "Greet, take the order, get the milk right and handle the till without losing the queue.",
      description:
        "This course is for new cafe staff, international students starting their first barista or counter job, and anyone who freezes when a customer rattles off a coffee order. You play the person at the counter. You will practise greeting customers, repeating orders back, asking the questions that matter (size, milk, sugar, dine in or takeaway), suggesting food, and taking payment. The first scenario is a friendly regular with a simple order and plenty of patience. The second brings a complication: a customer orders something you have just sold out of, and you need to offer an alternative and adjust the price. The third is a busy morning with a customer ordering for a whole office, changing their mind halfway through and asking to split payment, so you need to stay calm, confirm everything clearly and keep the queue moving. By the end you will have the phrases you need to run the counter on a busy shift with confidence.",
      keywords: ["cafe", "coffee orders", "barista", "counter service", "hospitality", "taking payment"],
      whatYouGet: [
        "Three counter conversations that build from a simple coffee to a big, changing office order",
        "Practice confirming size, milk and dine in or takeaway without sounding robotic",
        "Phrases for offering alternatives when an item has sold out",
        "Confidence handling split payments and order changes under time pressure",
      ],
      audience: "New cafe staff and job seekers who want to sound confident taking orders at the counter.",
      bannerBrief: "A glowing neon outline of a takeaway coffee cup with rising steam lines beside a small till, in violet and pink on deep navy.",
      scenarios: [
        {
          title: "The Regular's Morning Flat White",
          description: "You're on the counter at Greenleaf Cafe in Paddington on a quiet Tuesday morning. A friendly regular walks up; greet her, take her order and take payment.",
          difficultyLevel: "beginner",
          character: {
            name: "Margaret Kelly",
            role: "retired teacher and regular at Greenleaf Cafe",
            goal: "You're a regular who comes in most mornings. You want a regular flat white with skim milk, takeaway, and a banana bread, toasted with butter. The flat white is $5.20 and banana bread is $6.50. Only say skim milk if the staff member asks about milk. If asked, say it's takeaway. You pay by card. You're happy to chat about the weather or the new mural outside if they ask. Speak slowly and kindly.",
            demeanor: "warm, patient, chatty, speaks slowly in short clear sentences",
            endCondition: "the learner has confirmed the flat white with skim milk and the toasted banana bread, said the total and taken payment",
            voice: "marin",
          },
          learnerRole: "counter staff member at Greenleaf Cafe",
          taskCard: "- Greet the customer and ask what she'd like\n- Ask about size and milk for the coffee\n- Ask if it's dine in or takeaway\n- Confirm the order and say the total\n- Take payment and tell her where to wait",
          learnerOpens: true,
          timeLimitMinutes: 5,
        },
        {
          title: "Sold Out of the Special",
          description: "You're on the counter at Greenleaf Cafe at lunchtime and the chicken and avocado toastie has just sold out. A customer comes in wanting exactly that; offer alternatives, take the order and take payment.",
          difficultyLevel: "intermediate",
          character: {
            name: "Daniel Tran",
            role: "office worker on a short lunch break",
            goal: "You want the chicken and avocado toastie ($14) and an iced latte with oat milk ($6.80). When told the toastie has sold out, sound a bit disappointed and ask what's similar. You'll take a reasonable suggestion, like the ham and cheese toastie ($12) or the chicken salad roll ($13.50), if they describe it. You can't have tomato. You only have 20 minutes, so ask how long it will take. Pay by phone.",
            demeanor: "polite but slightly rushed, checks the time, a little disappointed then easygoing",
            endCondition: "the learner has offered an alternative, confirmed the replacement food and the oat milk iced latte, given the new total and taken payment",
            voice: "cedar",
          },
          learnerRole: "counter staff member at Greenleaf Cafe",
          taskCard: "- Greet the customer and take the order\n- Explain the toastie has sold out and apologise\n- Describe one or two alternatives and check for anything he can't eat\n- Confirm the final order and the new total\n- Tell him how long it will take",
          learnerOpens: true,
          timeLimitMinutes: 6,
        },
        {
          title: "The Big Office Order",
          description: "You're on the counter at Greenleaf Cafe during the 8am rush with a queue to the door. A customer is ordering for her whole team, keeps changing her mind and wants to split the bill; get the order right without holding up the line.",
          difficultyLevel: "advanced",
          character: {
            name: "Priya Raman",
            role: "office manager ordering coffee for her team",
            goal: "You're ordering for six people from a list on your phone: two large flat whites, one with almond milk; a small cappuccino; a long black; a chai latte with soy; and a hot chocolate. Halfway through, change the cappuccino to a decaf and ask if there's a discount for six coffees (there isn't). Then ask to split payment: $20 on the company card and the rest on your own card. If the staff member doesn't read the order back, you'll later say they got something wrong.",
            demeanor: "brisk, distracted by her phone, talks fast, apologetic when she changes her mind",
            endCondition: "the learner has read back all six drinks with the changes, explained there's no discount politely, and processed the split payment",
            voice: "coral",
          },
          learnerRole: "counter staff member at Greenleaf Cafe",
          taskCard: "- Take a six-drink order and check each size and milk\n- Handle the change to a decaf without losing track\n- Politely explain there's no bulk discount\n- Read the full order back before payment\n- Split the payment between two cards",
          learnerOpens: true,
          timeLimitMinutes: 8,
        },
      ],
    },
    {
      slug: "restaurant-table-service",
      kind: "roleplay",
      title: "Restaurant Table Service",
      tagline: "Welcome the table, explain the menu, take the order and check back, the way a good waiter does.",
      description:
        "This course is for waiters, front-of-house staff and anyone starting out in a sit-down restaurant. You play the server looking after a table from welcome to order. You will practise greeting guests, offering water and drinks, explaining dishes in simple words, making recommendations, taking a clear order and checking back during the meal. The first scenario is a relaxed couple who want a quick explanation of the specials and are easy to please. The second adds a complication: a guest is unsure about the menu, asks lots of questions and the dish he wants comes with something he doesn't like, so you need to describe options and note a change for the kitchen. The third is a larger table at a busy Saturday service where the host is impatient, wants a wine suggestion within budget and asks for the meals to be timed around a speech. You will need to stay polite, take control of the order and set clear expectations. By the end you will feel ready to run a section on your own.",
      keywords: ["waiter", "table service", "restaurant", "taking orders", "menu", "front of house"],
      whatYouGet: [
        "Three table conversations from a calm couple to a demanding Saturday group",
        "Simple ways to describe dishes, specials and cooking methods",
        "Practice noting changes for the kitchen and reading the order back",
        "Language for setting expectations on timing when the restaurant is busy",
      ],
      audience: "New and aspiring waiters who want to look after a table smoothly from welcome to order.",
      bannerBrief: "A neon outline of a plate, knife and fork with a small glowing candle on a table, in violet and pink lines on deep navy.",
      scenarios: [
        {
          title: "A Quiet Table for Two",
          description: "You're a waiter at Olive and Ember, a Mediterranean restaurant in New Farm, on a calm Wednesday night. Welcome the couple at table 4, explain the two specials and take their order.",
          difficultyLevel: "beginner",
          character: {
            name: "Gus Papadopoulos",
            role: "diner out for dinner with his wife",
            goal: "You're out for a quiet dinner. You'd like tap water for the table. Ask what the specials are tonight. Tonight's specials are slow-cooked lamb shoulder ($38) and grilled barramundi with lemon potatoes ($36). Order the lamb for yourself and the barramundi for your wife, plus a share plate of garlic bread ($9). Ask for one glass of house red ($11). If asked, say there are no allergies.",
            demeanor: "relaxed, friendly, appreciative, speaks at an easy pace",
            endCondition: "the learner has explained the specials, taken the drinks and food order and read it back",
            voice: "ash",
          },
          learnerRole: "waiter at Olive and Ember restaurant",
          taskCard: "- Welcome the guests and offer water\n- Explain tonight's two specials\n- Take the drinks and food order\n- Check for any allergies\n- Read the order back",
          learnerOpens: true,
          timeLimitMinutes: 5,
        },
        {
          title: "The Guest With Lots of Questions",
          description: "You're a waiter at Olive and Ember on a busy Friday. A guest dining alone is unsure what to order and keeps asking about dishes; help him choose and note any changes for the kitchen.",
          difficultyLevel: "intermediate",
          character: {
            name: "Hamish Doyle",
            role: "first-time guest dining alone",
            goal: "You've never had Greek or Lebanese food and want help choosing. Ask what moussaka is ($32) and what is in the mixed mezze plate ($26). You don't like eggplant, so when you learn the moussaka has it, ask for another suggestion. You'd like something filling, not spicy. You'll happily take the chicken souvlaki plate ($30) if it's explained, but ask whether the chips can be swapped for salad. Ask what beer they have on tap.",
            demeanor: "curious, a little unsure, asks follow-up questions, grateful for clear answers",
            endCondition: "the learner has explained the dishes, helped him choose, noted the salad swap and taken a drink order",
            voice: "ballad",
          },
          learnerRole: "waiter at Olive and Ember restaurant",
          taskCard: "- Describe two or three dishes in simple words\n- Find out what he does and doesn't like\n- Suggest a dish that suits him\n- Note the side swap for the kitchen\n- Take his drink order and confirm everything",
          learnerOpens: true,
          timeLimitMinutes: 6,
        },
        {
          title: "Saturday Night Birthday Table",
          description: "You're a waiter at Olive and Ember on a packed Saturday night with a table of eight celebrating a birthday. The host is impatient, wants a wine suggestion under budget and needs mains timed around a speech; take control and set clear expectations.",
          difficultyLevel: "advanced",
          character: {
            name: "Leilani Fonoti",
            role: "host of a birthday dinner for eight",
            goal: "You're hosting your mum's 60th. You've waited ten minutes and say so. You want two bottles of red under $60 each; ask for a recommendation (house shiraz $48, Barossa grenache $58). You want the banquet for eight ($65 a head) but ask if one guest can have a vegetarian version. You want mains to come out after a speech at about 8:15. If the waiter promises exact times, push back. You calm down if they apologise and take charge.",
            demeanor: "impatient at first, direct, warms up when she feels looked after",
            endCondition: "the learner has apologised for the wait, suggested wine within budget, confirmed the banquet with one vegetarian and agreed a plan for timing the mains",
            voice: "sage",
          },
          learnerRole: "waiter at Olive and Ember restaurant",
          taskCard: "- Acknowledge the wait and apologise briefly\n- Recommend wine within her budget\n- Confirm the banquet and the vegetarian change\n- Agree a realistic plan for timing the mains around the speech\n- Read the order back clearly",
          learnerOpens: true,
          timeLimitMinutes: 8,
        },
      ],
    },
    {
      slug: "behind-the-bar",
      kind: "roleplay",
      title: "Behind the Bar: Drinks Service",
      tagline: "Serve drinks, explain what's on tap, run a tab and keep it friendly when the bar gets busy.",
      description:
        "This course is for bartenders, bar backs moving up and anyone starting work at a pub, small bar or club. You play the bartender. You will practise greeting customers at the bar, explaining beers, wines and cocktails in simple terms, checking ID, opening and closing a tab, and handling payment. The first scenario is an easygoing customer who wants a beer recommendation and a glass of wine for a friend. The second adds a complication: a customer wants a cocktail you can't make tonight and a tap has just run out, so you need to suggest alternatives and check his ID. The third is a crowded Friday night where a customer wants to open a tab for a group, disputes a drink on the bill and asks you to split it, so you need to stay friendly, explain the bill clearly and fix the problem without giving away the bar. By the end you will be comfortable running the bar on a busy night.",
      keywords: ["bartender", "bar service", "drinks", "pub", "tabs", "cocktails"],
      whatYouGet: [
        "Three bar conversations, from a simple beer order to a disputed group tab",
        "Plain-language ways to describe beers, wines and cocktails",
        "Practice checking ID politely and opening and closing a tab",
        "Phrases for sorting out bill disputes without arguing",
      ],
      audience: "New bartenders and pub staff who want to serve drinks confidently on a busy night.",
      bannerBrief: "A glowing neon outline of a row of beer taps and a cocktail shaker on a bar top, in violet and pink on deep navy.",
      scenarios: [
        {
          title: "What's on Tap Tonight?",
          description: "You're the bartender at The Copper Kettle, a pub in West End, early on a Thursday evening. A customer walks up to the bar; help her choose a beer and order for her friend.",
          difficultyLevel: "beginner",
          character: {
            name: "Tegan Walsh",
            role: "customer at the pub after work",
            goal: "You want a beer but aren't sure what to choose. Ask what's on tap. The taps are a local lager ($9.50 a pot), a pale ale ($10.50) and a dark stout ($11). Say you like something light and not bitter. Also order a glass of sauvignon blanc ($10) for your friend. Ask if they do bar snacks; you'll get a bowl of chips ($8). Pay by card and don't start a tab.",
            demeanor: "cheerful, relaxed, a bit indecisive, friendly small talk",
            endCondition: "the learner has recommended a beer, taken the wine and chips order, given the total and taken payment",
            voice: "shimmer",
          },
          learnerRole: "bartender at The Copper Kettle",
          taskCard: "- Greet the customer at the bar\n- Explain the beers on tap simply\n- Recommend one based on what she likes\n- Take the rest of the order\n- Say the total and take payment",
          learnerOpens: true,
          timeLimitMinutes: 5,
        },
        {
          title: "No Espresso Martinis Tonight",
          description: "You're the bartender at The Copper Kettle on a Saturday. The coffee machine is broken and the pale ale keg has just run out; serve a customer who wants both and remember to check ID.",
          difficultyLevel: "intermediate",
          character: {
            name: "Jun-ho Park",
            role: "young customer out with friends",
            goal: "You want two espresso martinis ($19 each) and a pale ale. When told the coffee machine is down, ask what's similar; you'll try another cocktail if it's described, like a chocolate and vanilla White Russian ($18). When told the pale ale is out, accept the lager. You're 21 and have your licence, but only show it if asked. Ask whether there's a happy hour (there isn't on Saturdays).",
            demeanor: "upbeat, a little impatient, easygoing once offered alternatives",
            endCondition: "the learner has checked ID, offered alternatives for both unavailable drinks, confirmed the new order and taken payment",
            voice: "verse",
          },
          learnerRole: "bartender at The Copper Kettle",
          taskCard: "- Take the order and check ID\n- Explain the espresso martinis aren't available\n- Suggest a cocktail alternative and describe it\n- Offer a replacement for the pale ale\n- Confirm the order and take payment",
          learnerOpens: true,
          timeLimitMinutes: 6,
        },
        {
          title: "The Disputed Group Tab",
          description: "You're the bartender at The Copper Kettle on a packed Friday night. A customer is closing a tab for his group, says there's a drink on the bill they didn't order and wants it split three ways; sort it out calmly.",
          difficultyLevel: "advanced",
          character: {
            name: "Rafael Costa",
            role: "customer closing a group tab",
            goal: "Your tab is $186 under the name Costa. You're sure your group never ordered the jug of sangria ($38). In fact a friend ordered it before you arrived, but you only admit you're not sure after the bartender goes through the items calmly. You want the bill split three ways and ask for a discount for the trouble. Push back if the bartender sounds accusing. You accept if they explain clearly, stay polite and offer a fair fix.",
            demeanor: "frustrated, speaks over noise, firm but not rude, softens with calm explanations",
            endCondition: "the learner has gone through the tab items, resolved the sangria question politely, responded to the discount request and split the bill three ways",
            voice: "cedar",
          },
          learnerRole: "bartender at The Copper Kettle",
          taskCard: "- Listen to the problem without arguing\n- Go through the items on the tab clearly\n- Resolve the disputed drink politely\n- Respond to the discount request honestly\n- Split the bill three ways",
          learnerOpens: false,
          timeLimitMinutes: 8,
        },
      ],
    },
    {
      slug: "phone-bookings",
      kind: "roleplay",
      title: "Taking Phone Bookings",
      tagline: "Answer the phone, take a booking, spell names and handle the calls that don't go to plan.",
      description:
        "This course is for restaurant hosts, front-of-house staff and anyone who has to answer the phone at a hospitality venue. You play the person who picks up. Phone calls are hard because there's no body language, so you will practise a clear greeting, checking the date, time and number of guests, spelling names, confirming phone numbers and repeating details back. The first scenario is a simple booking from a patient caller with no special requests. The second brings a complication: the time the caller wants is full, so you need to offer other times, put her on a short waitlist or suggest a different night. The third is a caller wanting to change an existing booking from four to eleven people on the same night, which means a different area, a set menu and a deposit, and he is not happy about any of it. By the end you will be able to take any booking call clearly and politely.",
      keywords: ["phone bookings", "reservations", "restaurant host", "phone calls", "front of house"],
      whatYouGet: [
        "Three phone calls from a simple booking to a difficult change",
        "Practice confirming dates, times, names and phone numbers clearly",
        "Ways to offer alternatives when the time someone wants is full",
        "Language for explaining deposits and booking policies politely",
      ],
      audience: "Front-of-house staff who answer the phone and want to take bookings without mistakes.",
      bannerBrief: "A glowing neon outline of an old-style telephone and an open booking book with a pen, in violet and pink on deep navy.",
      scenarios: [
        {
          title: "A Simple Dinner Booking",
          description: "You're answering the phone at Saltbush Kitchen in Bulimba on a quiet afternoon. A caller wants to book a table; take down all the details and confirm them.",
          difficultyLevel: "beginner",
          character: {
            name: "Noor Haddad",
            role: "caller booking dinner for her family",
            goal: "You want a table for four this Saturday at 6:30pm. The booking is under Haddad; spell it if asked: H-A-D-D-A-D. Your mobile is 0412 558 309. One of the four is a child in a high chair, so mention it if asked about special requests. Ask if there's parking nearby. Speak slowly and clearly, and thank them at the end.",
            demeanor: "polite, organised, patient, speaks clearly",
            endCondition: "the learner has taken the date, time, number of guests, name, phone number and high chair request and read them back",
            voice: "marin",
          },
          learnerRole: "front-of-house staff member answering the phone",
          taskCard: "- Answer the phone with the venue name and your name\n- Take the date, time and number of guests\n- Get the name and spelling, and a phone number\n- Ask about any special requests\n- Read the booking back to confirm",
          learnerOpens: true,
          timeLimitMinutes: 5,
        },
        {
          title: "Fully Booked at 7pm",
          description: "You're answering the phone at Saltbush Kitchen. The caller wants Friday at 7pm for six, but the only free times are 5:30pm and 8:45pm; offer options and get a booking or a waitlist spot.",
          difficultyLevel: "intermediate",
          character: {
            name: "Mei Lin Zhao",
            role: "caller organising dinner with friends",
            goal: "You want a table for six this Friday at 7pm. When told it's full, sound disappointed and ask about 7:30. You won't take 5:30 because friends finish work late. You might take 8:45 but ask if the kitchen is still open then (it closes at 9:30). Ask to go on the waitlist for 7pm as well. Name is Zhao, Z-H-A-O; mobile 0433 210 774. If they offer Saturday, say you'll check with friends.",
            demeanor: "friendly but a little stressed, thinks out loud, polite",
            endCondition: "the learner has offered alternative times, confirmed either the 8:45pm booking or a waitlist spot with her details, and explained how the waitlist works",
            voice: "coral",
          },
          learnerRole: "front-of-house staff member answering the phone",
          taskCard: "- Explain that 7pm is fully booked\n- Offer the times that are free\n- Answer her question about the kitchen closing\n- Take her details for a booking or waitlist\n- Explain what happens next",
          learnerOpens: true,
          timeLimitMinutes: 6,
        },
        {
          title: "From Four to Eleven Guests",
          description: "You're answering the phone at Saltbush Kitchen. A caller wants to change his booking from four to eleven people for tomorrow night; groups over ten need the set menu and a $20 a head deposit, and he isn't keen.",
          difficultyLevel: "advanced",
          character: {
            name: "Bill Henderson",
            role: "caller changing an existing booking",
            goal: "You have a booking for four tomorrow at 7pm under Henderson. You want eleven now. When told groups over ten need the $70 set menu and a $20 a head deposit, push back: say nobody told you and some guests are fussy eaters. Ask if you can book as two tables of five and six instead. If refused politely with a reason, ask about the set menu and whether it suits a coeliac guest. You accept once it's clear and fair.",
            demeanor: "gruff, impatient, interrupts, reasonable when given clear reasons",
            endCondition: "the learner has found the booking, explained the group policy and deposit, answered the coeliac question and either confirmed the change or agreed a next step",
            voice: "ash",
          },
          learnerRole: "front-of-house staff member answering the phone",
          taskCard: "- Find the existing booking\n- Explain the set menu and deposit for large groups\n- Respond politely to his request to split into two tables\n- Check dietary needs for the group\n- Confirm the change or agree what happens next",
          learnerOpens: true,
          timeLimitMinutes: 8,
        },
      ],
    },
    {
      slug: "dietary-requirements-allergies",
      kind: "roleplay",
      title: "Dietary Requirements and Allergies",
      tagline: "Ask the right questions, check with the kitchen and never guess when a guest has an allergy.",
      description:
        "This course is for waiters, cafe staff and anyone who takes food orders. Allergies and dietary needs are among the most important conversations you'll have at work, and getting the words right matters. You play the staff member taking the order. You will practise asking about allergies, explaining what is in a dish, saying when you need to check with the kitchen, and being honest about what you can and can't promise. The first scenario is a vegan customer who wants to know which dishes suit her. The second is a parent ordering for a child with a nut allergy, where you need to check ingredients and explain how the kitchen handles cross-contact. The third is a guest with several needs who pushes you to promise a dish is completely safe when you can't, so you need to stay honest and offer a safer option. The scenarios use invented menus and kitchen practices; always follow your own venue's allergy procedures at work.",
      keywords: ["allergies", "dietary requirements", "vegan", "gluten free", "food safety", "waiter"],
      whatYouGet: [
        "Three ordering conversations that step up from vegan options to a serious allergy",
        "Clear questions to ask about allergies and dietary needs",
        "Practice saying you'll check with the kitchen instead of guessing",
        "Honest, polite language for when you can't guarantee a dish",
      ],
      audience: "Waiters and cafe staff who want to handle dietary requests and allergies clearly and honestly.",
      bannerBrief: "A neon outline of a menu card with a small leaf, a wheat stalk and a peanut drawn in glowing violet and pink lines on deep navy.",
      scenarios: [
        {
          title: "What's Vegan on the Menu?",
          description: "You're a waiter at Harbourlight Cafe in Wynnum. A customer is vegan and wants to know what she can eat; explain the options and take her order.",
          difficultyLevel: "beginner",
          character: {
            name: "Aisha Rahman",
            role: "customer at a bayside cafe for brunch",
            goal: "You're vegan and want brunch. Ask which dishes are vegan. The smashed avocado on sourdough ($19) comes with feta, so it's vegan without it. The mushroom and spinach bowl ($21) is vegan. Ask whether the sourdough has egg or milk in it (it doesn't). Choose the avocado without feta and add a hash brown ($5). Order a soy cappuccino. Be friendly and thank them for checking.",
            demeanor: "friendly, calm, clear about what she needs, appreciative",
            endCondition: "the learner has explained the vegan options, confirmed the avocado without feta, the hash brown and the soy cappuccino",
            voice: "sage",
          },
          learnerRole: "waiter at Harbourlight Cafe",
          taskCard: "- Ask about any dietary needs\n- Explain which dishes are vegan or can be made vegan\n- Answer her question about the bread\n- Take the order with the changes\n- Read it back",
          learnerOpens: true,
          timeLimitMinutes: 5,
        },
        {
          title: "Ordering for a Child With a Nut Allergy",
          description: "You're a waiter at Harbourlight Cafe. A parent is ordering for his son, who has a tree nut allergy; check what's in the dishes, explain how the kitchen handles it and take the order.",
          difficultyLevel: "intermediate",
          character: {
            name: "Tom Fitzgerald",
            role: "father ordering lunch for himself and his son",
            goal: "Your son Ollie, 7, has a tree nut allergy. You want the kids' pancakes ($14) for him, but ask whether they're cooked near nuts. The pancakes come with a hazelnut spread, so if the waiter doesn't mention it, ask what the topping is. You'll take them with maple syrup instead if the kitchen confirms. If the waiter guesses, ask them to check. For yourself, order a chicken burger ($24) and a long black.",
            demeanor: "calm but careful, asks direct questions, relieved when taken seriously",
            endCondition: "the learner has noted the allergy, checked the pancakes with the kitchen, swapped the topping and taken the full order",
            voice: "ballad",
          },
          learnerRole: "waiter at Harbourlight Cafe",
          taskCard: "- Ask about allergies before taking the order\n- Find out what's in the pancakes\n- Say you'll check with the kitchen, then report back\n- Offer a safe change to the dish\n- Confirm the order and that the allergy is noted",
          learnerOpens: true,
          timeLimitMinutes: 6,
        },
        {
          title: "Can You Guarantee It?",
          description: "You're a waiter at Harbourlight Cafe on a busy Sunday. A guest has coeliac disease and a sesame allergy and wants you to promise a dish is completely safe; stay honest and help her find the safest option.",
          difficultyLevel: "advanced",
          character: {
            name: "Grace Villanueva",
            role: "guest with coeliac disease and a sesame allergy",
            goal: "You have coeliac disease and a sesame allergy. You want the poke bowl ($24), which has sesame dressing and soy sauce containing wheat. Ask the waiter to guarantee it's completely safe. If they promise, push harder and ask how they know. You respect honesty: the kitchen shares a fryer and uses sesame oil. You'll accept a grilled fish salad ($26) without dressing and with lemon if the kitchen confirms. Mention a past bad experience if they sound casual.",
            demeanor: "firm, worried, direct, tests whether staff are being honest, relaxes when treated seriously",
            endCondition: "the learner has been honest about what they can't guarantee, checked with the kitchen, offered a safer option and confirmed her order with both needs noted",
            voice: "shimmer",
          },
          learnerRole: "waiter at Harbourlight Cafe",
          taskCard: "- Take both dietary needs seriously and note them\n- Explain honestly what's in the dish she wants\n- Don't promise what you can't guarantee\n- Check with the kitchen and offer a safer option\n- Confirm the order and what you've told the kitchen",
          learnerOpens: true,
          timeLimitMinutes: 8,
        },
      ],
    },
    {
      slug: "handling-customer-complaints",
      kind: "roleplay",
      title: "Handling Customer Complaints",
      tagline: "Listen, apologise, fix it and keep your cool when a guest isn't happy.",
      description:
        "This course is for anyone on the floor in a cafe, restaurant or pub who has to deal with an unhappy customer. You play the staff member who is approached. You will practise listening without interrupting, apologising sincerely, asking questions to understand the problem, offering a fix within your authority and knowing when to get a manager. The first scenario is a mild complaint about a cold coffee, a simple fix with a friendly customer. The second is a guest whose meal came out wrong and late while the rest of her table has finished eating, so you need to apologise, offer options and set realistic expectations. The third is an angry customer who wants a full refund for a meal he mostly ate and threatens to post a bad review. You'll need to stay calm, be fair, offer what you can and hold your ground politely. By the end you will have a reliable way to turn complaints around.",
      keywords: ["complaints", "customer service", "apologising", "difficult customers", "hospitality", "refunds"],
      whatYouGet: [
        "Three complaints that step up from a cold coffee to an angry refund demand",
        "A simple listen, apologise, fix, follow up pattern you can reuse",
        "Phrases for offering a fix without over-promising",
        "Practice staying calm and polite when a customer raises their voice",
      ],
      audience: "Hospitality staff who want to handle unhappy customers calmly and fairly.",
      bannerBrief: "A neon outline of a speech bubble with a small cracked plate inside, turning into a smile, in violet and pink on deep navy.",
      scenarios: [
        {
          title: "This Coffee Is Cold",
          description: "You're working the floor at Banksia Corner Cafe in Annerley. A customer waves you over because her latte is lukewarm; listen, apologise and fix it.",
          difficultyLevel: "beginner",
          character: {
            name: "Linh Pham",
            role: "customer having breakfast at a suburban cafe",
            goal: "Your latte arrived lukewarm. You're not angry, just disappointed, because you like it extra hot. You want a new one, extra hot, with full cream milk. If offered something extra, like a free muffin, say thank you but it isn't necessary. If the staff member asks, mention your eggs were lovely. Be easy to please.",
            demeanor: "mild, polite, slightly apologetic for complaining, speaks softly",
            openingLine: "Sorry, excuse me? I don't want to be a pain, but my latte's a bit cold.",
            endCondition: "the learner has apologised, offered to remake the latte extra hot and confirmed it's on its way",
            voice: "marin",
          },
          learnerRole: "floor staff member at Banksia Corner Cafe",
          taskCard: "- Listen to the problem\n- Apologise sincerely\n- Offer to remake the coffee and check how she likes it\n- Tell her when it will be ready",
          learnerOpens: false,
          timeLimitMinutes: 5,
        },
        {
          title: "Wrong Meal, Long Wait",
          description: "You're working the floor at Banksia Corner Cafe at lunch. A customer's meal came out 25 minutes late and wrong, and her friends have finished eating; apologise, offer options and set realistic expectations.",
          difficultyLevel: "intermediate",
          character: {
            name: "Colin Barker",
            role: "customer whose lunch came out wrong and late",
            goal: "You ordered the beef burger ($24) with no onion and it came out with onion, 25 minutes after your friends' meals. Your friends have finished. You want it fixed fast; you have to leave in 15 minutes. Ask how long a new one will take (about 10 minutes). If told it'll be quick, ask if it can be made takeaway. If offered something off the bill, accept. Be annoyed but fair.",
            demeanor: "annoyed, tired, sighs, short answers, calms down when given a clear plan",
            openingLine: "Mate, I've waited nearly half an hour and this has onion on it. I said no onion.",
            endCondition: "the learner has apologised, explained the wait for a new burger, offered takeaway or something off the bill, and agreed a plan",
            voice: "verse",
          },
          learnerRole: "floor staff member at Banksia Corner Cafe",
          taskCard: "- Listen and apologise for both the mistake and the wait\n- Explain how long a new meal will take\n- Offer options that suit his time\n- Agree a plan and check he's happy with it",
          learnerOpens: false,
          timeLimitMinutes: 6,
        },
        {
          title: "I Want a Full Refund",
          description: "You're working the floor at Banksia Corner Cafe and the manager is out. An angry customer has eaten most of his meal, says it was terrible and demands a full refund or he'll post a bad review; stay calm and be fair.",
          difficultyLevel: "advanced",
          character: {
            name: "Antonio Russo",
            role: "angry customer at the end of his meal",
            goal: "You had the seafood linguine ($32) and ate most of it but say it was too salty and the prawns were overcooked. You want a full refund. Threaten an online review. Interrupt when the staff member explains. If they offer 50% off or a free dessert and coffee (which they can do without the manager), say it isn't enough at first. You accept a fair offer if they stay calm, listen and pass your feedback to the chef.",
            demeanor: "loud, angry, interrupts, sarcastic, slowly calms if treated with respect",
            openingLine: "This was honestly the worst pasta I've had. I'm not paying for it.",
            endCondition: "the learner has listened, apologised, made a fair offer within their authority, held their ground politely on the full refund and agreed an outcome",
            voice: "cedar",
          },
          learnerRole: "floor staff member at Banksia Corner Cafe",
          taskCard: "- Let him explain without arguing\n- Apologise and ask specific questions about the meal\n- Offer a fair fix within your authority\n- Politely decline what you can't do and explain why\n- Agree an outcome and say you'll pass on the feedback",
          learnerOpens: false,
          timeLimitMinutes: 8,
        },
      ],
    },
    {
      slug: "responsible-service-of-alcohol",
      kind: "roleplay",
      title: "Refusing Service Politely (RSA)",
      tagline: "Practise the hardest bar conversations: checking ID, slowing someone down and saying no with respect.",
      description:
        "This course is for bartenders, wait staff and anyone who serves alcohol and needs to practise responsible service. You play the staff member. Saying no to a customer is uncomfortable, so you will practise the language: checking ID, noticing signs someone has had enough, offering water or food, refusing service firmly but politely, and getting help from a manager or security when needed. The first scenario is a customer without ID, where you must refuse and explain kindly. The second is a customer who is buying drinks for a friend who has clearly had too much, so you need to refuse the round without embarrassing anyone. The third is a well-known regular who is intoxicated, wants one more drink and gets upset, so you must hold your ground, keep him safe and help him get home. These scenarios practise communication only. Always follow your own state's RSA training and your venue's house policy at work.",
      keywords: ["rsa", "responsible service of alcohol", "refusing service", "bartender", "checking id", "pub"],
      whatYouGet: [
        "Three refusal conversations, from a missing ID to an intoxicated regular",
        "Calm, respectful phrases for saying no and sticking to it",
        "Practice offering water, food and a way home",
        "Ways to involve a manager without escalating the situation",
      ],
      audience: "Bar and restaurant staff who serve alcohol and want to refuse service confidently and kindly.",
      bannerBrief: "A neon outline of a glass of water beside an upside-down empty beer glass under a glowing closed sign, in violet and pink on deep navy.",
      scenarios: [
        {
          title: "No ID, No Drink",
          description: "You're on the bar at The Fig and Anchor in Fortitude Valley. A young-looking customer orders two beers but has left his ID at home; refuse politely and offer alternatives.",
          difficultyLevel: "beginner",
          character: {
            name: "Kyle Watson",
            role: "young customer who left his ID at home",
            goal: "You want two pints of lager. You're 19 but left your licence at home. Say you're 19 and your mates can vouch for you. Offer to show a photo of your licence on your phone; that isn't accepted at this venue. Ask whether you can just have one. If the bartender is clear and kind, accept it and order two lemon, lime and bitters ($6 each) instead. Don't get angry, just a bit embarrassed.",
            demeanor: "friendly, a bit embarrassed, tries his luck once or twice, accepts no",
            endCondition: "the learner has asked for ID, refused alcohol politely, explained why a photo isn't accepted and offered a non-alcoholic option",
            voice: "ash",
          },
          learnerRole: "bartender at The Fig and Anchor",
          taskCard: "- Ask for ID before serving\n- Refuse politely when he can't show it\n- Explain why a photo on a phone isn't accepted here\n- Offer a non-alcoholic alternative",
          learnerOpens: true,
          timeLimitMinutes: 5,
        },
        {
          title: "The Round for a Friend",
          description: "You're on the bar at The Fig and Anchor on a Friday. A customer wants a round of drinks for her table, but one friend is clearly intoxicated; refuse that drink without embarrassing anyone.",
          difficultyLevel: "intermediate",
          character: {
            name: "Brooke Delaney",
            role: "customer buying a round for her friends",
            goal: "You want four vodka sodas ($12 each). One is for your friend Jess, who has been slurring and nearly fell off a stool. Say Jess is fine and just tired. Push back once: it's her birthday. If the bartender explains politely that they can't serve Jess alcohol, accept three vodka sodas and ask what Jess can have. Take water and a bowl of chips for her. Ask if you can get a taxi called.",
            demeanor: "bubbly, a bit tipsy herself but in control, defensive at first, then cooperative",
            endCondition: "the learner has refused the drink for the intoxicated friend, served the other three, offered water or food and helped arrange a way home",
            voice: "coral",
          },
          learnerRole: "bartender at The Fig and Anchor",
          taskCard: "- Take the order and notice who the drinks are for\n- Politely refuse the drink for the intoxicated friend\n- Explain the reason without embarrassing anyone\n- Offer water, food or help getting home",
          learnerOpens: true,
          timeLimitMinutes: 6,
        },
        {
          title: "Just One More, Mate",
          description: "You're on the bar at The Fig and Anchor near closing. A regular you know well is intoxicated, wants one more beer and gets upset when you say no; hold your ground kindly and help him get home safely.",
          difficultyLevel: "advanced",
          character: {
            name: "Marcus Bell",
            role: "intoxicated regular at the end of the night",
            goal: "You've been at the pub since 4pm and want one more schooner. You're a regular and remind the bartender you've been coming for ten years. When refused, get upset: say they're treating you like a kid and you'll take your business elsewhere. Ask to speak to the manager. Calm down if the bartender stays respectful, offers water and helps you call a taxi or your brother Darren. You live in Newstead.",
            demeanor: "loud, slurring slightly, hurt and indignant, sentimental, softens with respect",
            openingLine: "One more schooner, mate. Come on, I've been coming here ten years.",
            endCondition: "the learner has refused clearly, stayed respectful, offered water, involved a manager if needed and helped arrange a safe way home",
            voice: "verse",
          },
          learnerRole: "bartender at The Fig and Anchor",
          taskCard: "- Refuse the drink clearly and respectfully\n- Stay calm when he gets upset\n- Offer water and something to eat\n- Help arrange a safe way home\n- Get the manager if you need support",
          learnerOpens: false,
          timeLimitMinutes: 8,
        },
      ],
    },
    {
      slug: "functions-and-events",
      kind: "roleplay",
      title: "Functions and Events",
      tagline: "Plan a function with a client, explain packages and keep the night on track when plans change.",
      description:
        "This course is for function coordinators, events staff and front-of-house team members who look after group bookings and private events. You play the venue's events staff member. You will practise asking about the event, explaining room options and packages, talking about numbers, deposits and minimum spends, and confirming details in writing. The first scenario is an enquiry for a small work farewell, where the client needs help choosing between two packages. The second brings a complication: a client for an engagement party wants changes the venue can't easily do, like bringing her own cake and an extra hour, so you need to explain fees and offer options. The third is on the night itself: guest numbers are well over the booking, the bar tab is nearly used up and the host wants it all sorted now. You will need to stay calm, explain the costs clearly and get decisions. By the end you'll be ready to look after an event from enquiry to last drinks.",
      keywords: ["functions", "events", "group bookings", "packages", "event coordinator", "hospitality"],
      whatYouGet: [
        "Three event conversations from a first enquiry to a problem on the night",
        "Plain ways to explain packages, minimum spends and deposits",
        "Practice handling requests that come with extra fees",
        "Language for getting quick decisions from a host under pressure",
      ],
      audience: "Events and front-of-house staff who look after function bookings and private parties.",
      bannerBrief: "A neon outline of a long banquet table with glowing string lights and a small cake, in violet and pink lines on deep navy.",
      scenarios: [
        {
          title: "A Work Farewell Enquiry",
          description: "You're the events staff member at Riverbend Hotel in Kangaroo Point. A caller wants to hold a farewell for a colleague; find out what she needs and explain the two packages.",
          difficultyLevel: "beginner",
          character: {
            name: "Deepa Iyer",
            role: "office worker organising a colleague's farewell",
            goal: "You're organising a farewell for about 25 people on a Friday in three weeks, from 5pm to 8pm. Ask what packages there are. The venue has a canape package ($45 a head) and a drinks and grazing package ($60 a head with three hours of drinks). Ask which is better for a work crowd. Ask whether a deposit is needed ($200) and if you can have a small speech area. Ask them to email details to deepa.iyer@email.com.",
            demeanor: "friendly, organised, takes notes, asks practical questions",
            openingLine: "Hi, I'm hoping to book something for a work farewell in a few weeks.",
            endCondition: "the learner has asked about date, numbers and times, explained both packages and the deposit, and offered to send the details in writing",
            voice: "sage",
          },
          learnerRole: "events staff member at Riverbend Hotel",
          taskCard: "- Ask about the date, times and number of guests\n- Explain the two packages simply\n- Help her choose based on her group\n- Explain the deposit\n- Offer to send everything in writing",
          learnerOpens: false,
          timeLimitMinutes: 5,
        },
        {
          title: "Our Own Cake and One More Hour",
          description: "You're the events staff member at Riverbend Hotel meeting a client about her engagement party. She wants to bring her own cake and stay an extra hour; explain the fees and find a fair solution.",
          difficultyLevel: "intermediate",
          character: {
            name: "Natalie Georgiou",
            role: "client planning her engagement party",
            goal: "Your engagement party is booked for 60 people, 7pm to 11pm, on the deck. You want to bring a cake from your aunt's bakery and finish at midnight. The venue charges a $4 a head cakeage fee and $500 for an extra hour, but the deck must close at 11pm because of neighbours. Push back on cakeage: it's family. Ask if the party can move inside after 11. You'll accept a clear option if it's explained kindly.",
            demeanor: "excited, chatty, a bit stubborn on details that matter to her family",
            openingLine: "Thanks for meeting me! So I've got a couple of little changes for the party.",
            endCondition: "the learner has explained the cakeage fee and the 11pm deck rule, offered options such as moving inside, and confirmed what she has decided",
            voice: "shimmer",
          },
          learnerRole: "events staff member at Riverbend Hotel",
          taskCard: "- Listen to both requests\n- Explain the cakeage fee and why it exists\n- Explain why the deck closes at 11pm\n- Offer a workable option for the extra hour\n- Confirm her decisions and next steps",
          learnerOpens: false,
          timeLimitMinutes: 6,
        },
        {
          title: "Too Many Guests, Not Enough Tab",
          description: "You're the events staff member on duty at Riverbend Hotel during a 40th birthday party. About 20 more guests than booked have arrived and the $1,500 bar tab is nearly used; explain the situation to the host and get decisions now.",
          difficultyLevel: "advanced",
          character: {
            name: "Steve Kowalski",
            role: "host of a 40th birthday party at the venue",
            goal: "You booked for 50 but about 70 people are here. Your $1,500 bar tab has $120 left. You want more food and the tab kept going, but don't want to pay much more. Ask whether the extra guests can just share the food. Say the tab should have lasted longer and ask how it was used. Push back on extra food ($25 a head). You'll agree to top up the tab by $500 and add one round of grazing if it's clearly explained.",
            demeanor: "stressed, defensive, a bit merry, wants to look good in front of guests",
            openingLine: "Hey, the bar staff said something about my tab? What's going on?",
            endCondition: "the learner has explained the guest numbers, the tab balance and the costs of extra food and drinks, and the host has made clear decisions on both",
            voice: "ballad",
          },
          learnerRole: "events staff member on duty at Riverbend Hotel",
          taskCard: "- Explain the tab balance and how it was used\n- Raise the extra guest numbers politely\n- Explain the costs for more food and drinks\n- Get a clear decision on the tab and food\n- Confirm what happens next",
          learnerOpens: false,
          timeLimitMinutes: 8,
        },
      ],
    },
    {
      slug: "kitchen-to-floor-communication",
      kind: "roleplay",
      title: "Kitchen to Floor Communication",
      tagline: "Talk to chefs clearly at the pass: changes, delays, allergies and the hard conversations mid-service.",
      description:
        "This course is for waiters, runners and front-of-house staff who need to talk to the kitchen during service. You play the floor staff member, and the character is a chef at the pass. Kitchens are busy and loud, so you will practise being short and clear, using table numbers, calling out changes, asking how long a dish will be and passing information back to guests. The first scenario is a calm check-in with the head chef about specials and a simple dish change before service. The second adds a complication: you forgot to put an allergy on a docket that's already cooking, and you need to tell the sous chef quickly and honestly. The third is the peak of a busy Saturday, with the kitchen running 30 minutes behind and a stressed executive chef, while you push for a guest's urgent request. You'll need to stay calm, be brief and agree a plan. By the end you'll communicate confidently with any kitchen.",
      keywords: ["kitchen", "chefs", "front of house", "service", "communication", "waiter"],
      whatYouGet: [
        "Three conversations at the pass, from a calm pre-service briefing to a stressed Saturday",
        "Short, clear phrases for changes, delays and allergies",
        "Practice owning a mistake quickly and honestly",
        "Ways to pass kitchen information back to guests accurately",
      ],
      audience: "Waiters and runners who want to talk to chefs clearly and calmly during service.",
      bannerBrief: "A neon outline of a kitchen pass with a bell, order dockets and a chef's hat glowing in violet and pink on deep navy.",
      scenarios: [
        {
          title: "Pre-Service Briefing",
          description: "You're a waiter at Mango Street Kitchen in South Brisbane, 20 minutes before dinner service. Check with the head chef about tonight's specials and whether a dish change is possible.",
          difficultyLevel: "beginner",
          character: {
            name: "Kirra Thompson",
            role: "head chef at Mango Street Kitchen",
            goal: "You're prepping before service and happy to brief the waiter. Tonight's specials: a red curry with pork belly ($34), mild to medium spicy, and a grilled snapper with green papaya salad ($38). Only 12 snappers are available, so ask the waiter to tell you when six are sold. If asked, the curry can be made with tofu for vegetarians but contains fish sauce, so it isn't vegan. Explain clearly and check they understood.",
            demeanor: "calm, friendly, organised, explains clearly, short sentences",
            endCondition: "the learner has asked about both specials, the snapper numbers and the vegetarian option, and repeated the key details back",
            voice: "marin",
          },
          learnerRole: "waiter at Mango Street Kitchen",
          taskCard: "- Ask the chef to explain tonight's specials\n- Ask how many of each are available\n- Ask whether a dish can be made vegetarian or vegan\n- Repeat the key details back",
          learnerOpens: true,
          timeLimitMinutes: 5,
        },
        {
          title: "I Forgot the Allergy",
          description: "You're a waiter at Mango Street Kitchen mid-service. You forgot to add a peanut allergy to table 9's docket and the pad thai is already cooking; go to the pass and tell the sous chef right away.",
          difficultyLevel: "intermediate",
          character: {
            name: "Minh Le",
            role: "sous chef running the pass at Mango Street Kitchen",
            goal: "You're running the pass and busy. Table 9's pad thai has peanuts and is nearly done. When told about the allergy, be annoyed but act fast: you'll bin it and remake it in a clean wok, about 12 minutes. Ask for the exact allergy and whether it's peanut only or all nuts. Ask the waiter to tell the table about the wait and to fix the docket. Calm down if they're clear and honest.",
            demeanor: "fast, blunt, annoyed for a moment, then focused and practical",
            endCondition: "the learner has clearly told the chef the table, dish and allergy, answered his questions and agreed to update the docket and tell the guest about the wait",
            voice: "cedar",
          },
          learnerRole: "waiter at Mango Street Kitchen",
          taskCard: "- Get the chef's attention quickly\n- Give the table number, dish and allergy clearly\n- Own the mistake honestly\n- Answer his questions about the allergy\n- Agree what you'll tell the guest",
          learnerOpens: true,
          timeLimitMinutes: 6,
        },
        {
          title: "Thirty Minutes Behind",
          description: "You're a waiter at Mango Street Kitchen during the Saturday peak and the kitchen is running 30 minutes behind. A table needs their mains in ten minutes to make a show at the theatre; negotiate with the stressed executive chef.",
          difficultyLevel: "advanced",
          character: {
            name: "Luca Bianchi",
            role: "executive chef running a slammed Saturday service",
            goal: "You're 30 minutes behind with 18 dockets on the rail. Table 14 wants mains in ten minutes for a 7:30 theatre show. Say you can't jump the queue for everyone. Ask what they ordered: two beef rendang ($36) and a barramundi ($38). The rendang is ready to plate; the barramundi takes 15 minutes. Offer the rendang now and suggest swapping the fish for a quicker dish. Be short and sharp; respect waiters who are brief.",
            demeanor: "stressed, curt, loud kitchen voice, impatient with long explanations, fair when spoken to clearly",
            openingLine: "Not now unless it's urgent. What do you need?",
            endCondition: "the learner has explained the request briefly, given the order details, agreed a plan with the chef and said how they'll explain it to the guests",
            voice: "ash",
          },
          learnerRole: "waiter at Mango Street Kitchen",
          taskCard: "- Explain the urgent request in one or two sentences\n- Give the table number and exact order\n- Listen to what the chef can do\n- Agree a plan, including any swap\n- Say how you'll update the guests",
          learnerOpens: false,
          timeLimitMinutes: 8,
        },
      ],
    },
    {
      slug: "closing-shift",
      kind: "roleplay",
      title: "Closing Shift: Last Orders to Lock-Up",
      tagline: "Handover, last orders, lingering guests and the cash-up: the conversations that end the night well.",
      description:
        "This course is for cafe, restaurant and bar staff who work the closing shift. You play the staff member closing up. The end of the night has its own conversations: checking the closing list with your manager, calling last orders, politely moving on guests who want to stay, and explaining problems with the cash-up. The first scenario is a friendly handover with your manager about what needs doing before lock-up. The second is a group of guests who are still chatting after closing time and want one more round, so you need to move them on warmly but clearly. The third is a phone call from the owner the next morning about a till that was $40 short and a broken glass incident that wasn't written up, so you need to explain what happened, take responsibility where it's yours and agree what changes. By the end you will be able to close any shift calmly and professionally.",
      keywords: ["closing shift", "last orders", "cash up", "handover", "hospitality", "manager"],
      whatYouGet: [
        "Three end-of-night conversations from a calm handover to a tricky call with the owner",
        "Friendly, firm phrases for last orders and closing time",
        "Practice reporting problems clearly and taking responsibility",
        "Language for checking a closing list and asking for help",
      ],
      audience: "Hospitality staff who work late shifts and want to close up confidently.",
      bannerBrief: "A glowing neon sign reading Closed hanging on a door, with a set of keys and a clock showing midnight, in violet and pink on deep navy.",
      scenarios: [
        {
          title: "The Closing Checklist",
          description: "You're starting the closing shift at Juniper Lane Bistro in Woolloongabba. Your manager is leaving early; go through the closing list with her and ask about anything you're unsure of.",
          difficultyLevel: "beginner",
          character: {
            name: "Fiona McLeod",
            role: "duty manager at Juniper Lane Bistro",
            goal: "You're leaving at 9pm and handing over closing to the learner. The list: last food orders at 9:30pm, bar closes at 10:30pm, wipe down and restock the bar fridges, run the dishwasher clean cycle, count the till and leave the float of $300, lock the back door and set the alarm with code 4417. Explain one item at a time and wait for questions. If they ask, say to call your mobile if something goes wrong.",
            demeanor: "kind, clear, a bit hurried, encourages questions",
            endCondition: "the learner has gone through the closing list, asked at least one question and repeated the key times and the float amount back",
            voice: "coral",
          },
          learnerRole: "staff member closing the bistro",
          taskCard: "- Ask your manager what needs doing at close\n- Check the times for last food and bar orders\n- Ask about the till and float\n- Ask who to call if there's a problem\n- Repeat the key details back",
          learnerOpens: true,
          timeLimitMinutes: 5,
        },
        {
          title: "The Table That Won't Leave",
          description: "You're closing at Juniper Lane Bistro and it's 10:45pm, 15 minutes after the bar closed. A friendly group is still chatting and wants one more round; move them on warmly but clearly.",
          difficultyLevel: "intermediate",
          character: {
            name: "Tevita Taufa",
            role: "guest at a friendly group table after closing",
            goal: "You're with five friends celebrating a mate's new job and you're having a great time. Ask for one more round of beers. When told the bar is closed, ask for just ten more minutes and whether you can buy takeaway drinks. Ask where a good late bar is nearby. You'll happily pay and leave if the staff member is friendly and clear, and ask them to call a taxi for two friends going to Carindale.",
            demeanor: "loud, happy, charming, jokes around, cooperative when asked nicely",
            openingLine: "Hey, legend! Can we grab one more round before we head off?",
            endCondition: "the learner has explained the bar is closed, politely declined another round, settled the bill and helped the group leave",
            voice: "verse",
          },
          learnerRole: "staff member closing the bistro",
          taskCard: "- Explain warmly that the bar has closed\n- Decline another round without being rude\n- Bring the bill and settle it\n- Help them on their way, including a taxi",
          learnerOpens: false,
          timeLimitMinutes: 6,
        },
        {
          title: "The Till Was Forty Dollars Short",
          description: "You closed Juniper Lane Bistro last night, and the owner calls you in the morning. The till was $40 short and a broken glass incident wasn't written up; explain what happened, take responsibility where it's yours and agree what changes.",
          difficultyLevel: "advanced",
          character: {
            name: "Rosa Santos",
            role: "owner of Juniper Lane Bistro",
            goal: "The till was $40 short and the closing notes don't mention that a guest cut his hand on a broken glass at 10pm. You want to know what happened with both. You suspect a cash refund was given without a docket, so ask about refunds if they don't mention one. Press for detail and say incident reports aren't optional. You don't want blame, you want honesty and a fix. Agree a plan if they're open.",
            demeanor: "serious, calm, direct, asks follow-up questions, fair when given honest answers",
            openingLine: "Morning. Have you got a few minutes? I want to go through last night's close.",
            endCondition: "the learner has explained the missing $40, described the glass incident, taken responsibility where appropriate and agreed what they'll do differently",
            voice: "sage",
          },
          learnerRole: "staff member who closed the bistro last night",
          taskCard: "- Listen to the owner's concerns\n- Explain what happened with the till honestly\n- Describe the glass incident and why it wasn't written up\n- Take responsibility without over-apologising\n- Agree what you'll do differently next time",
          learnerOpens: false,
          timeLimitMinutes: 8,
        },
      ],
    },
  ],
};

