import type { OriginalCreator } from "./types";

export const overTheFence: OriginalCreator = {
  handle: "over-the-fence",
  displayName: "Over the Fence",
  tagline: "Everyday conversations for life in your street, your suburb and your local community.",
  bio: "Over the Fence is a XINGO Original studio from Adelaide, built around the small conversations that make a suburb feel like home. Saying hello to the people next door. Asking for your parcel back. Calling the property manager about a leaking tap, ringing the council about a missed bin, joining the library, the community garden or the local footy club. These chats are short, but they can feel big when English is your second or third language. Each course gives you three practice conversations that start friendly and slow, then add a complication, then ask you to negotiate politely under a bit of pressure. Practise out loud with patient, realistic locals until the words come easily.",
  location: "Adelaide, SA",
  accent: "#2E7D32",
  visualStyle: "Loose watercolour with botanical detail: soft green and ochre washes, fine ink outlines, gum leaves and red bottlebrush framing everyday suburban scenes.",
  logoBrief: "A loose watercolour timber paling fence with a sprig of gum leaves and one red bottlebrush flower leaning over it, outlined in fine ink.",
  avatarBrief: "A round watercolour badge of two gum leaves crossed over a red bottlebrush bloom on a soft green wash, with fine ink outlines.",
  courses: [
    // 1
    {
      slug: "meet-the-neighbours",
      kind: "roleplay",
      title: "Meet the Neighbours",
      tagline: "Say hello, sort out a missing parcel and return a borrowed tool without the awkwardness.",
      description:
        "This course is for anyone who has just moved into a new street, unit block or townhouse and wants to feel comfortable talking to the people next door. You practise the small, friendly language that builds good neighbour relationships in Australia: introducing yourself, making small talk about the street, asking about bin night, and asking for or offering help. The first conversation is a relaxed hello over the front fence with a chatty neighbour who has lived there for years. The second adds a complication: a courier says your parcel was left next door, but the neighbour you knock on says they don't have it, so you need to explain clearly and work out what happened together. The third is the hardest: you borrowed a neighbour's hedge trimmer and it broke while you were using it. You need to own up, apologise, offer a fair fix and keep the relationship friendly even when they are disappointed.",
      keywords: ["neighbours", "small talk", "parcels", "borrowing", "apologising", "moving house"],
      whatYouGet: [
        "Three neighbour conversations that build from a friendly hello to a tricky apology",
        "Natural phrases for introductions, small talk and asking for help",
        "Practice explaining a problem clearly and offering a fair fix",
      ],
      audience: "New arrivals and anyone who has just moved into a new street and wants to get to know the neighbours.",
      bannerBrief: "A loose watercolour of two people chatting over a low paling fence, gum leaves and bottlebrush spilling over the top, a wheelie bin by the kerb.",
      scenarios: [
        {
          title: "Hello over the front fence",
          description: "You're watering your new front garden when the neighbour next door wanders over to say hello. Introduce yourself and find out a little about the street.",
          difficultyLevel: "beginner",
          character: {
            name: "Helen Papadopoulos",
            role: "long-time resident next door in a quiet Prospect street",
            goal: "You're friendly and curious about the new neighbour. You want to know their name, where they've moved from and who lives with them. You happily share that bins go out Sunday night (red and yellow one week, red and green the next), that the corner deli has good coffee, and that your grandson Nick mows lawns for $25. If asked, you mention you've lived here 31 years and offer your phone number for emergencies.",
            demeanor: "warm, chatty, speaks slowly, laughs easily, asks simple questions",
            openingLine: "Hello there! You must be the new folks. I'm Helen, from number 14. How are you settling in?",
            endCondition: "the learner has introduced themselves, asked at least one question about the street, and you have swapped names and said goodbye",
            voice: "marin",
          },
          learnerRole: "new resident who just moved in",
          taskCard: "- Introduce yourself and say who lives with you\n- Ask Helen which night the bins go out\n- Ask one more question about the street or the area\n- Thank her and say goodbye politely",
          learnerOpens: false,
          timeLimitMinutes: 5,
        },
        {
          title: "My parcel went next door",
          description: "A delivery message says your parcel was left with your neighbour at number 9, but when you knock, he isn't sure he has it. Explain the problem and work it out together.",
          difficultyLevel: "intermediate",
          character: {
            name: "Duc Nguyen",
            role: "neighbour at number 9, working from home",
            goal: "You're busy on a work call break and don't remember taking a parcel. You ask what it looks like, who sent it and what time the message said. If the learner says it's a small brown box from Pinewood Homewares delivered around 11am, you remember your daughter signed for something, and you find it in the hallway. You push back gently if the description is vague. You suggest leaving a note on your door next time, and offer your number.",
            demeanor: "polite but distracted, slightly confused at first, relaxes once it's sorted",
            openingLine: "Oh, hi. Sorry, I'm between meetings. What can I do for you?",
            endCondition: "the learner has described the parcel well enough for you to find it, has it back, and you've agreed how to handle deliveries next time",
            voice: "cedar",
          },
          learnerRole: "neighbour looking for a missing parcel",
          taskCard: "- Explain that the delivery message said your parcel was left at number 9\n- Describe the parcel: size, sender and delivery time\n- Stay polite if Duc doesn't remember at first\n- Agree on what to do with future parcels",
          learnerOpens: true,
          timeLimitMinutes: 6,
        },
        {
          title: "I broke your hedge trimmer",
          description: "You borrowed your neighbour's hedge trimmer and it stopped working halfway through the job. Return it, own up, and offer a fair way to fix things.",
          difficultyLevel: "advanced",
          character: {
            name: "Graham Whitfield",
            role: "retired neighbour who lent you his hedge trimmer",
            goal: "You lent your trimmer, a gift from your late wife, and you're upset it's broken. You want an honest account of what happened. You push back if the learner blames the trimmer or offers only $20. A repair shop in Kilkenny quotes about $90; a new one costs $180. You accept either paying the repair or replacing it. If asked, you admit the blade was a bit loose last time you used it, which softens you.",
            demeanor: "reserved, disappointed, short replies at first, warms up if the learner is honest and specific",
            openingLine: "Ah, you've brought it back. Everything go alright with the hedge?",
            endCondition: "the learner has apologised, explained what happened and you have both agreed on a specific fix (repair or replacement) and when it will happen",
            voice: "ash",
          },
          learnerRole: "neighbour returning a borrowed tool",
          taskCard: "- Tell Graham honestly that the trimmer stopped working\n- Apologise without making excuses\n- Offer a fair fix, such as paying for a repair or a replacement\n- Agree on exactly what you'll do and by when",
          learnerOpens: false,
          timeLimitMinutes: 8,
        },
      ],
    },
    // 2
    {
      slug: "neighbour-noise-conversations",
      kind: "roleplay",
      title: "Noise Next Door",
      tagline: "Raise a noise problem calmly, handle a barking dog mix-up and respond when the complaint is about you.",
      description:
        "Noise is one of the most common reasons neighbours fall out, and one of the hardest things to talk about in a second language. This course is for renters and owners in houses, units and apartments who want to raise a problem without starting a fight. You practise polite openings, describing a problem with times and details, suggesting a solution, and staying calm when the other person disagrees. In the first conversation you ask a friendly young neighbour to turn down music on a weeknight, and she agrees easily. In the second, you raise a barking dog with the family over the back fence, but there is a misunderstanding about whose dog it is. In the third, the tables turn: a neighbour knocks to complain that your household is too noisy late at night. You need to listen, apologise for what is fair, explain your side, and agree on realistic quiet times.",
      keywords: ["noise complaint", "neighbours", "apartments", "polite requests", "negotiating", "conflict"],
      whatYouGet: [
        "Polite ways to start a hard conversation with a neighbour",
        "Language for describing a problem with times and details",
        "Practice responding calmly when someone complains about you",
        "A realistic agreement to aim for in each conversation",
      ],
      audience: "Renters and home owners who want to sort out noise with neighbours calmly and in plain English.",
      bannerBrief: "A loose watercolour of two lit windows in a small unit block at dusk, gum branches framing the scene, a few ink musical notes drifting between them.",
      scenarios: [
        {
          title: "Could you turn it down a little?",
          description: "It's 10:30pm on a Tuesday and music from the unit upstairs is keeping you awake. Knock and politely ask your neighbour to turn it down.",
          difficultyLevel: "beginner",
          character: {
            name: "Priya Raman",
            role: "university student in the unit upstairs",
            goal: "You're having two friends over to study and didn't realise the speaker was so loud through the floor. You're embarrassed and happy to help. You ask which room the noise is coming through and whether it's the music or the voices. You offer to move the speaker off the floor and finish by 11pm on weeknights. If asked, you share your mobile so the learner can text you next time instead of knocking.",
            demeanor: "friendly, apologetic, speaks clearly, a bit embarrassed",
            openingLine: "Oh hi! Sorry, is everything okay?",
            endCondition: "the learner has explained the problem politely and you have agreed to turn it down and how to contact each other next time",
            voice: "coral",
          },
          learnerRole: "resident in the unit downstairs",
          taskCard: "- Say who you are and that you live downstairs\n- Explain politely that the music is keeping you awake\n- Ask her to turn it down, and agree on a time it will be quiet\n- Thank her and say goodnight",
          learnerOpens: false,
          timeLimitMinutes: 5,
        },
        {
          title: "The dog that barks all day",
          description: "A dog has been barking for hours every weekday while you work from home. You talk to the neighbour over the back fence, but he thinks it's someone else's dog.",
          difficultyLevel: "intermediate",
          character: {
            name: "Tony Esposito",
            role: "neighbour over the back fence with a kelpie named Bella",
            goal: "You're sure Bella is quiet; she's an old girl. You think it's the terrier two doors down. You ask when the barking happens. If the learner gives specific times, like 9 to 11am when you leave for work, you admit you're not home then and might not know. You suggest asking the other neighbour too. You agree to try leaving the radio on and a chew toy, and ask the learner to text you a short video if it keeps happening.",
            demeanor: "friendly but defensive about his dog, talks fast, uses casual Aussie phrases",
            openingLine: "G'day! Haven't seen you over the fence in a while. What's up?",
            endCondition: "the learner has described the barking with times, you have accepted it might be Bella, and you have agreed on a next step and a way to stay in touch",
            voice: "ballad",
          },
          learnerRole: "neighbour who works from home",
          taskCard: "- Explain the barking problem without sounding angry\n- Give specific days and times it happens\n- Handle the misunderstanding about whose dog it is\n- Agree on something Tony will try and how you'll follow up",
          learnerOpens: true,
          timeLimitMinutes: 7,
        },
        {
          title: "When the complaint is about you",
          description: "Your neighbour knocks on Sunday morning to complain about noise from your place late last night. Listen, respond fairly, and agree on quiet times that work for both of you.",
          difficultyLevel: "advanced",
          character: {
            name: "Kylie Morrison",
            role: "nurse on night shifts in the house next door",
            goal: "You're tired and frustrated. You say there was loud talking and car doors until 1am Saturday and twice the weekend before. You work nights and sleep 8am to 3pm, so daytime noise matters too. You push back if the learner only says sorry without changes. You want quiet after 10pm and no power tools before 3pm on weekdays. If asked, you'd accept a text before any party. You soften if the learner is respectful.",
            demeanor: "tired, blunt, frustrated at first, fair once listened to",
            openingLine: "Morning. Look, sorry to knock, but I need to talk to you about last night.",
            endCondition: "the learner has acknowledged the problem, explained their side calmly, and you have agreed specific quiet times and how to give notice of gatherings",
            voice: "sage",
          },
          learnerRole: "resident whose household had guests over",
          taskCard: "- Listen and let Kylie explain without interrupting\n- Apologise for what is fair and explain your side calmly\n- Ask about her work hours so you understand her needs\n- Agree on specific quiet times and how you'll give notice of gatherings",
          learnerOpens: false,
          timeLimitMinutes: 8,
        },
      ],
    },
    // 3
    {
      slug: "fences-trees-and-boundaries",
      kind: "roleplay",
      title: "Fences, Trees and Boundaries",
      tagline: "Talk through overhanging branches, a shared fence quote and a disagreement over who pays.",
      description:
        "In Australian suburbs, the fence and the trees along it belong to everyone and no-one, which makes them a classic source of neighbour chats. This course is for home owners and long-term renters who want to raise boundary issues clearly and politely. You practise describing where something is, asking for permission, talking about quotes and costs, and holding your position without being rude. In the first conversation you ask a relaxed neighbour about trimming a branch that drops leaves into your gutter. In the second, you bring a quote for replacing the old shared fence, but your neighbour wants a different style and a cheaper builder. In the third, the conversation gets harder: a neighbour insists you should pay for the whole fence repair after a storm, and you need to disagree respectfully, suggest a fair split and agree on next steps. The course does not give legal advice; it helps you have the conversation.",
      keywords: ["fences", "trees", "neighbours", "quotes", "sharing costs", "negotiating"],
      whatYouGet: [
        "Words for describing fences, branches, gutters and boundaries",
        "Practice talking about quotes and splitting costs",
        "Polite ways to disagree and suggest a fair compromise",
      ],
      audience: "Home owners and renters who need to talk with a neighbour about a shared fence or overhanging tree.",
      bannerBrief: "A loose watercolour of a weathered paling fence under a big gum tree, leaves drifting into a gutter, bottlebrush in the foreground, fine ink outlines.",
      scenarios: [
        {
          title: "Your branch is over my gutter",
          description: "A branch from your neighbour's gum tree hangs over your roof and fills your gutter with leaves. Ask him about trimming it.",
          difficultyLevel: "beginner",
          character: {
            name: "Sione Taufa",
            role: "easygoing neighbour who owns the big gum tree",
            goal: "You're relaxed and didn't know the branch was a problem. You ask which branch and how bad the gutter is. You're happy for it to be trimmed but you don't own a ladder that tall. You suggest your cousin Viliami, an arborist, who would charge about $150 and could come next Saturday morning. You offer to split it. If asked, you'll also pick up the leaves from your side.",
            demeanor: "easygoing, slow and friendly, says 'no worries' a lot",
            endCondition: "the learner has explained the problem and you have agreed who will trim the branch, when, and how the cost is shared",
            voice: "verse",
          },
          learnerRole: "neighbour with leaves in your gutter",
          taskCard: "- Greet Sione and explain which branch is the problem\n- Describe what it's doing to your gutter\n- Ask if it can be trimmed\n- Agree on who does it, when, and who pays",
          learnerOpens: true,
          timeLimitMinutes: 5,
        },
        {
          title: "A quote for the new fence",
          description: "The shared side fence is falling apart and you've got a quote to replace it. Your neighbour has different ideas about the style and the builder.",
          difficultyLevel: "intermediate",
          character: {
            name: "Wendy Liu",
            role: "neighbour who shares the side fence with you",
            goal: "You agree the fence is bad but the learner's quote, $3,400 for steel panels from Southern Cross Fencing, feels high. You'd prefer timber pickets and your friend's builder quoted $2,700. You ask about height, colour and when work would start. You push back on steel because it gets hot. If asked, you admit your quote doesn't include removing the old fence, which costs about $500 extra. You agree to get a third quote.",
            demeanor: "practical, careful with money, asks lots of detailed questions",
            openingLine: "Hi! You said you had something about the fence to show me?",
            endCondition: "the learner has explained their quote, compared it with yours, and you have agreed on a next step such as a third quote and a date to decide",
            voice: "shimmer",
          },
          learnerRole: "neighbour who got the first fence quote",
          taskCard: "- Explain the quote: price, material and what's included\n- Listen to Wendy's preferences and her cheaper quote\n- Ask what her quote includes\n- Agree on a fair next step and a date to decide",
          learnerOpens: false,
          timeLimitMinutes: 7,
        },
        {
          title: "Who pays after the storm?",
          description: "A storm knocked down part of the back fence. Your neighbour says your tree caused it and you should pay for everything. Disagree respectfully and work towards a fair split.",
          difficultyLevel: "advanced",
          character: {
            name: "Bruce Harland",
            role: "neighbour whose backyard shares the damaged fence",
            goal: "You're stressed because your dogs can now get out. You say the learner's tree fell on the fence, so they pay all $1,800. You push back hard on a 50/50 split. If the learner points out the posts were already rotten, or that the storm was the cause, you hesitate. If asked, you admit your insurer might cover part. You want the gap covered with temporary panels today and the fence fixed within two weeks.",
            demeanor: "stressed, loud, interrupts, calms down when the learner stays polite and gives reasons",
            openingLine: "Right, have you seen the state of that fence? Your tree's done that, mate.",
            endCondition: "the learner has disagreed respectfully, given reasons, and you have agreed on a cost split or next step plus a plan for the gap today",
            voice: "cedar",
          },
          learnerRole: "neighbour whose tree branch fell in the storm",
          taskCard: "- Stay calm and acknowledge Bruce's problem with his dogs\n- Disagree respectfully with paying the whole cost, and give reasons\n- Suggest a fair split or another step, like checking insurance\n- Agree on how to cover the gap today",
          learnerOpens: false,
          timeLimitMinutes: 8,
        },
      ],
    },
    // 4
    {
      slug: "calling-your-property-manager",
      kind: "roleplay",
      title: "Calling Your Property Manager",
      tagline: "Report repairs, chase an urgent job and talk through a rent increase on the phone.",
      description:
        "Renting in Australia usually means dealing with a property manager at a real estate agency, often on the phone. This course is for tenants who want to report problems clearly, follow up when things don't happen, and talk about rent and inspections with confidence. You practise giving your address and details, describing a problem, asking for a time, following up, and negotiating politely. In the first call you report a dripping kitchen tap to a helpful property manager. In the second, the plumber didn't turn up to fix your broken hot water system, and you need to explain that it is urgent and get a firm time. In the third, you have received a notice of a rent increase and want to ask questions, point out issues with the property and ask for a smaller increase. The course does not give legal advice; it practises the conversation, and characters may mention checking your state's tenancy rules.",
      keywords: ["renting", "property manager", "repairs", "rent increase", "phone calls", "tenants"],
      whatYouGet: [
        "Clear phrases for reporting repairs and giving details on the phone",
        "Practice following up firmly when a job is missed",
        "Language for asking questions about a rent increase and negotiating politely",
      ],
      audience: "Tenants who need to call their property manager about repairs, rent or inspections.",
      bannerBrief: "A loose watercolour of a small brick rental cottage with a phone on the front step, gum leaves and bottlebrush framing the door, soft ochre wash.",
      scenarios: [
        {
          title: "Reporting a dripping tap",
          description: "Your kitchen tap has been dripping for a week. Call your property manager, report it and find out what happens next.",
          difficultyLevel: "beginner",
          character: {
            name: "Jasmine Haddad",
            role: "property manager at Fernleigh Realty in Norwood",
            goal: "You're helpful and organised. You need the tenant's name, address and a phone number. You ask which tap, how long it's been dripping and whether there is any water under the sink. You explain you'll send Kevin from Clearflow Plumbing and ask if he can use the office key if no-one's home. You tell them he'll call to book, usually within three business days.",
            demeanor: "professional, friendly, speaks clearly, repeats details back",
            openingLine: "Good morning, Fernleigh Realty, Jasmine speaking. How can I help?",
            endCondition: "the learner has given their details and described the problem, and you have explained who will come, when, and how access will work",
            voice: "marin",
          },
          learnerRole: "tenant calling about a repair",
          taskCard: "- Give your name and the rental address\n- Describe the problem with the tap\n- Answer questions about access to the house\n- Ask when the plumber will come",
          learnerOpens: false,
          timeLimitMinutes: 5,
        },
        {
          title: "The plumber never came",
          description: "Your hot water stopped working three days ago and the plumber didn't turn up this morning. Call the agency, explain it's urgent and get a firm time.",
          difficultyLevel: "intermediate",
          character: {
            name: "Ryan O'Connell",
            role: "busy property manager at Harbourside Property in Port Adelaide",
            goal: "You have 180 properties and assumed the plumber went. At first you say you'll 'chase it up'. You push back that the owner needs to approve costs over $500. If the learner explains there's no hot water with young kids and it's been three days, you treat it as urgent and call Swift Hot Water, booking tomorrow 8 to 10am. If asked, you confirm you'll email the booking and text if it changes.",
            demeanor: "rushed, vague at first, becomes more helpful when the learner is clear and firm",
            openingLine: "Harbourside Property, Ryan here.",
            endCondition: "the learner has explained the problem and the missed visit, you have agreed it's urgent, and you have given a specific booking time and how you'll confirm it",
            voice: "ash",
          },
          learnerRole: "tenant with no hot water",
          taskCard: "- Explain the hot water problem and that the plumber didn't come\n- Say clearly why it's urgent for your household\n- Don't accept a vague answer: ask for a specific time\n- Ask how the booking will be confirmed",
          learnerOpens: false,
          timeLimitMinutes: 7,
        },
        {
          title: "Talking about a rent increase",
          description: "You've received a letter saying your rent will rise by $60 a week. Call your property manager to ask questions and politely negotiate a smaller increase.",
          difficultyLevel: "advanced",
          character: {
            name: "Mei Zhou",
            role: "senior property manager at Fernleigh Realty",
            goal: "The owner wants rent to go from $520 to $580 a week from 1 March, saying it matches the market. You defend it at first. If the learner mentions they've paid on time for three years, the old oven and the mould in the bathroom, you soften. You can offer $550 if they sign a 12-month lease, and arrange the bathroom fix. You suggest checking the state's tenancy rules but give no legal advice.",
            demeanor: "polite, firm, businesslike, listens to reasons, won't respond to anger",
            openingLine: "Hi, Mei speaking. I understand you're calling about the rent review letter?",
            endCondition: "the learner has asked questions, given reasons for a smaller increase, and you have reached an outcome such as a revised amount, a repair or a time to get back to them",
            voice: "coral",
          },
          learnerRole: "long-term tenant",
          taskCard: "- Confirm the new rent amount and when it starts\n- Explain why you'd like a smaller increase, with reasons\n- Mention any repairs the property needs\n- Agree on a specific outcome or next step",
          learnerOpens: false,
          timeLimitMinutes: 8,
        },
      ],
    },
    // 5
    {
      slug: "tradie-at-home",
      kind: "roleplay",
      title: "When the Tradie Comes Round",
      tagline: "Book a tradie, handle a surprise extra cost and speak up when a job isn't finished.",
      description:
        "Plumbers, electricians, tilers and handypeople, or tradies, are part of Australian home life, whether you own or rent. This course is for anyone who needs to explain a job, understand a quote and make sure the work gets done properly. You practise describing a problem around the house, asking about price and timing, asking what is included, and speaking up politely but firmly when you are not happy. In the first conversation you book a friendly plumber over the phone for a blocked bathroom sink. In the second, an electrician arrives to replace a light fitting and says the job will cost more than quoted, so you need to ask why and decide. In the third, a tiler says the bathroom is finished, but there are gaps and a cracked tile, and you need to point out the problems, hold back final payment fairly and agree on when she will return.",
      keywords: ["tradies", "home repairs", "quotes", "plumber", "electrician", "complaints"],
      whatYouGet: [
        "Everyday words for describing problems around the house",
        "Questions to ask about price, timing and what's included",
        "Practice speaking up politely when a job isn't done right",
      ],
      audience: "Home owners and renters who need to book, talk to or follow up with a tradie.",
      bannerBrief: "A loose watercolour of a tradie's ute parked under a gum tree outside a suburban house, a toolbox on the verandah, bottlebrush by the gate.",
      scenarios: [
        {
          title: "Booking a plumber for a blocked sink",
          description: "Your bathroom sink drains very slowly. Call a local plumber, explain the problem and book a time.",
          difficultyLevel: "beginner",
          character: {
            name: "Darren Pike",
            role: "owner of Pike Plumbing in Salisbury",
            goal: "You're friendly and straightforward. You ask where the sink is, how long it's been slow and whether other drains are slow too. You explain your call-out fee is $95, which includes the first 30 minutes, then $40 per extra 15 minutes. You offer Thursday 1 to 3pm or Friday 8 to 10am. You need the address, a name and a mobile, and ask about parking and pets.",
            demeanor: "cheerful, plain-speaking, a bit of Aussie slang, patient",
            openingLine: "Pike Plumbing, Darren speaking.",
            endCondition: "the learner has described the problem, heard the price, and booked a specific time with their address and contact number",
            voice: "ballad",
          },
          learnerRole: "resident calling a plumber",
          taskCard: "- Explain the problem with your bathroom sink\n- Ask how much it will cost\n- Choose a time that suits you\n- Give your address and phone number",
          learnerOpens: false,
          timeLimitMinutes: 5,
        },
        {
          title: "That's more than the quote",
          description: "An electrician has come to replace a light fitting quoted at $180, but now says it will cost $320. Find out why and decide what to do.",
          difficultyLevel: "intermediate",
          character: {
            name: "Ravi Kapoor",
            role: "licensed electrician from Brightline Electrical",
            goal: "You opened the fitting and the old wiring is brittle and unsafe; you need to replace a section of cable, which adds $140 for parts and an hour's labour. You explain clearly and show the scorched wire. You push back on doing just the fitting because it's unsafe. If asked, you'll put the change in writing, take a photo, and you'll waive the $40 second-visit fee if they want time to think.",
            demeanor: "calm, professional, explains technical things simply, patient with questions",
            openingLine: "Okay, so I've had a look behind the old light and there's a bit of a problem.",
            endCondition: "the learner has asked why the price changed, understood the reason, and made a clear decision about whether to go ahead, with the new price confirmed",
            voice: "verse",
          },
          learnerRole: "home owner who booked the electrician",
          taskCard: "- Ask Ravi to explain why the price has gone up\n- Check that you understand the safety problem\n- Ask for the new price in writing\n- Decide whether to go ahead now or later",
          learnerOpens: false,
          timeLimitMinutes: 7,
        },
        {
          title: "The job isn't finished",
          description: "The tiler says your bathroom is done and asks for the final $1,200, but you've found gaps in the grout and a cracked tile. Raise the problems and agree on a fix before paying.",
          difficultyLevel: "advanced",
          character: {
            name: "Tash Webb",
            role: "owner of Webb Tiling, finishing your bathroom renovation",
            goal: "You're running late for another job and want the final $1,200 today. You say the grout gaps are normal and will 'settle'. You push back that the crack might be from the learner moving furniture. If the learner points to specific spots and stays calm, you admit the corner grout is short and you'll fix it. You offer to return Monday at 7am. You'll accept holding back $300 until it's fixed if pushed politely.",
            demeanor: "brisk, confident, a bit defensive, respects people who are specific and calm",
            openingLine: "Right, all done in here! Looks good, hey? I'll just need the final payment and I'll get out of your hair.",
            endCondition: "the learner has pointed out the specific problems, you have agreed what will be fixed and when, and you have agreed how much is paid now and how much later",
            voice: "sage",
          },
          learnerRole: "home owner checking the finished bathroom",
          taskCard: "- Point out the specific problems with the grout and the cracked tile\n- Stay calm if Tash disagrees or blames you\n- Ask for a date and time to fix the problems\n- Agree how much you'll pay now and how much after the fix",
          learnerOpens: false,
          timeLimitMinutes: 8,
        },
      ],
    },
    // 6
    {
      slug: "calling-the-council",
      kind: "roleplay",
      title: "Calling the Council",
      tagline: "Book a hard rubbish pickup, sort out a parking permit and lodge a complaint that gets action.",
      description:
        "Your local council looks after bins, parking permits, footpaths, street trees, parks and much more, and most contact starts with a phone call to the customer service centre. This course is for residents who want to make those calls confidently. You practise giving your address, explaining what you need, spelling names, understanding the steps the council explains, and following up when something is not done. In the first call you book a hard rubbish collection and check what you can put out. In the second, you apply for a residential parking permit but find out you are missing a document, so you need to ask what else you can use. In the third, you are calling for the third time about a broken footpath outside your house that has already caused a fall, and you need to explain clearly, push for a reference number and a date, and stay polite while being firm.",
      keywords: ["local council", "hard rubbish", "parking permit", "footpaths", "phone calls", "complaints"],
      whatYouGet: [
        "Phrases for giving your address and spelling your name on the phone",
        "Practice asking about steps, documents and timeframes",
        "Language for following up firmly on a complaint",
      ],
      audience: "Residents who need to call their local council about bins, parking or problems in their street.",
      bannerBrief: "A loose watercolour of a suburban street with a hard rubbish pile on the verge, a street sign and a big gum tree, soft green washes and ink lines.",
      scenarios: [
        {
          title: "Booking a hard rubbish pickup",
          description: "You've got an old couch and a broken bookshelf to get rid of. Call the council to book a hard rubbish collection.",
          difficultyLevel: "beginner",
          character: {
            name: "Leanne Brooks",
            role: "customer service officer at Cadell Creek Council",
            goal: "You help residents book hard rubbish. You need the full address, a name and phone number. You explain each household gets two free collections a year, up to two cubic metres, roughly a small trailer load. You ask what items they have. Furniture is fine; paint, tyres and building rubble are not. The next date is Wednesday the 14th; items go on the verge no earlier than the weekend before. You give booking number HR-20471.",
            demeanor: "patient, cheerful, speaks slowly and spells things out",
            openingLine: "Cadell Creek Council, Leanne speaking. How can I help you today?",
            endCondition: "the learner has booked a collection, told you the items, and you have given the date, the rules for the verge and a booking number",
            voice: "shimmer",
          },
          learnerRole: "resident booking a collection",
          taskCard: "- Say you want to book a hard rubbish collection\n- Give your address and what items you have\n- Ask when the items can go out on the verge\n- Write down the date and booking number",
          learnerOpens: false,
          timeLimitMinutes: 5,
        },
        {
          title: "Parking permit, missing paperwork",
          description: "You've moved into a street with two-hour parking and need a resident permit. You don't have the document the council asks for, so find out what else you can use.",
          difficultyLevel: "intermediate",
          character: {
            name: "Arjun Mehta",
            role: "parking permits officer at Cadell Creek Council",
            goal: "You need proof of address and the car's registration. The usual proof is a rates notice or a signed lease. You push back if the learner offers only a phone bill because it must be in the resident's name and under three months old. If asked, you accept a bond lodgement receipt plus a utility bill. First permit is $45 a year. You can email a temporary permit valid for 14 days once documents are uploaded.",
            demeanor: "polite, by-the-book, precise, helpful when asked direct questions",
            openingLine: "Parking permits, Arjun speaking.",
            endCondition: "the learner has explained their situation, found out which documents will work, and you have explained the cost, how to submit and the temporary permit",
            voice: "ash",
          },
          learnerRole: "new resident applying for a parking permit",
          taskCard: "- Explain that you need a resident parking permit\n- Tell Arjun which document you don't have\n- Ask what other documents you can use\n- Check the cost and how long it will take",
          learnerOpens: false,
          timeLimitMinutes: 6,
        },
        {
          title: "Third call about the broken footpath",
          description: "You've called twice about a lifted footpath slab outside your house, and last week an older neighbour tripped on it. Call again and push politely for a real date.",
          difficultyLevel: "advanced",
          character: {
            name: "Fiona McAllister",
            role: "team leader in customer service at Cadell Creek Council",
            goal: "You can see two earlier requests but no action. At first you say it's 'on the list' and could take 8 to 12 weeks. You push back on promising a date. If the learner says someone fell and gives the date and exact spot, you escalate it as a safety hazard: a crew will put a barrier up within 48 hours and repair within three weeks. You give reference CR-88315 and offer a callback by Friday.",
            demeanor: "calm, professional, cautious about promises, responds well to clear facts",
            openingLine: "Hi, Fiona here, I'm a team leader. I understand you've called about this before?",
            endCondition: "the learner has given the history and the fall, and you have escalated it with a reference number, a timeframe for a barrier and repair, and a follow-up arrangement",
            voice: "marin",
          },
          learnerRole: "resident following up a complaint",
          taskCard: "- Explain that this is your third call and give the earlier dates\n- Describe the exact location and the fall\n- Ask for a reference number and a specific timeframe\n- Agree on how and when the council will follow up",
          learnerOpens: false,
          timeLimitMinutes: 8,
        },
      ],
    },
    // 7
    {
      slug: "at-the-local-library",
      kind: "roleplay",
      title: "At the Local Library",
      tagline: "Join the library, sort out a lost book and book a room for your community group.",
      description:
        "Australian public libraries are free, friendly places for books, wi-fi, English conversation groups, kids' programs and meeting rooms. This course is for anyone who wants to use their local library with confidence. You practise asking for information, giving your details, understanding rules about loans and fees, and making a booking. In the first conversation you join the library at the front desk and ask about wi-fi and the conversation group. In the second, you have lost a borrowed book and been charged a replacement fee, so you need to explain and ask about your options. In the third, you want to book a meeting room for your community group's regular Saturday catch-up, but the room is already taken and the staff member has rules about groups, so you need to negotiate times, numbers and conditions.",
      keywords: ["library", "library card", "community groups", "bookings", "fees", "conversation group"],
      whatYouGet: [
        "Phrases for joining and using your local library",
        "Practice explaining a problem and asking about options",
        "Language for negotiating a room booking with rules and conditions",
      ],
      audience: "New and regular library users who want to join, borrow, sort out problems or book spaces.",
      bannerBrief: "A loose watercolour of a sunny suburban library with tall windows and shelves, gum leaves at the edges and a bottlebrush in a pot by the door.",
      scenarios: [
        {
          title: "Joining the library",
          description: "You've walked into your local library for the first time. Ask to join and find out about wi-fi and the free English conversation group.",
          difficultyLevel: "beginner",
          character: {
            name: "Grace Santos",
            role: "library officer at the front desk of Mitcham Hills Library",
            goal: "You love helping new members. Joining is free; you need photo ID and proof of address, or a letter with their name and address. You ask for their name, date of birth and email. You explain they can borrow 20 items for three weeks. Wi-fi is free with the card number. The English conversation group meets Tuesdays at 10am in the community room, no booking needed. You hand over a card.",
            demeanor: "warm, encouraging, speaks slowly, smiles a lot",
            endCondition: "the learner has joined, asked about wi-fi or the conversation group, and has their card and the key information",
            voice: "coral",
          },
          learnerRole: "new library visitor",
          taskCard: "- Say you'd like to join the library\n- Give your details when asked\n- Ask how to use the wi-fi\n- Ask when the English conversation group meets",
          learnerOpens: true,
          timeLimitMinutes: 5,
        },
        {
          title: "I lost a library book",
          description: "You can't find a library book you borrowed, and your account shows a $35 replacement fee. Explain what happened and ask about your options.",
          difficultyLevel: "intermediate",
          character: {
            name: "Hamish Reid",
            role: "customer service librarian at Mitcham Hills Library",
            goal: "You see the cookbook 'Seasons of the Hills' is three weeks overdue, now charged at $35 plus a $5 processing fee. Your account is blocked until it's sorted. You ask when they last saw it. You explain options: keep looking for 30 days and the fee is removed if it's returned; pay now; or buy the same edition new and bring it in, which removes the $35 but not the $5. If asked, you can unblock the card while they search.",
            demeanor: "kind, a little formal, careful to explain rules clearly",
            endCondition: "the learner has explained the situation, understood the options, and chosen one, and you have confirmed what happens to their account",
            voice: "ballad",
          },
          learnerRole: "library member with a lost book",
          taskCard: "- Explain that you've lost a book you borrowed\n- Ask about the fee on your account\n- Find out all your options\n- Choose one and check if you can still borrow",
          learnerOpens: true,
          timeLimitMinutes: 6,
        },
        {
          title: "Booking a room for our group",
          description: "Your community group wants a regular Saturday spot in the library meeting room, but the slot you want is taken and there are rules. Negotiate a booking that works.",
          difficultyLevel: "advanced",
          character: {
            name: "Joon-ho Park",
            role: "community spaces coordinator at Mitcham Hills Library",
            goal: "The Saturday 10am to 12pm slot is taken by a craft group until June. You can offer Saturday 1 to 3pm or Sunday 10am to 12pm. Rooms are free for not-for-profit groups, but you need a contact person, a group name and numbers under 25. You push back on food other than tea and biscuits, and on bookings longer than two hours. If asked, you'll put them on the waitlist for the 10am slot.",
            demeanor: "friendly, organised, firm about rules, open to fair compromises",
            openingLine: "Hi, I'm Joon-ho. I hear you're interested in booking the community room?",
            endCondition: "the learner has explained their group, negotiated around the clash and the rules, and you have agreed a specific regular booking or waitlist arrangement",
            voice: "verse",
          },
          learnerRole: "organiser of a local community group",
          taskCard: "- Explain your group: name, purpose and how many people\n- Ask for the Saturday morning slot, and handle the clash\n- Discuss the rules about food and time\n- Agree on a regular booking or a waitlist option",
          learnerOpens: false,
          timeLimitMinutes: 8,
        },
      ],
    },
    // 8
    {
      slug: "community-garden-plot",
      kind: "roleplay",
      title: "Getting a Community Garden Plot",
      tagline: "Ask about a garden plot, handle a waitlist and sort out a watering roster clash.",
      description:
        "Community gardens are a great way to grow food, meet people and practise English with neighbours. This course is for anyone who would like a plot or wants to get involved. You practise asking about how a garden works, understanding fees and rules, explaining what you want to grow, and working through disagreements with other members. In the first conversation you visit the garden on an open day and ask the coordinator how to get a plot. In the second, you find out there is a waitlist, so you ask about other ways to join, such as sharing a plot or helping in the shared beds. In the third, you are now a member, and another gardener says you have been using too much water and missing your roster turns. You need to listen, explain, and agree on a fair arrangement without falling out.",
      keywords: ["community garden", "gardening", "volunteering", "rosters", "waitlists", "neighbours"],
      whatYouGet: [
        "Gardening words for plots, beds, compost and watering",
        "Practice asking about fees, rules and waitlists",
        "Language for handling a disagreement with another member",
      ],
      audience: "Anyone who wants to join a community garden, grow food or meet people locally.",
      bannerBrief: "A loose watercolour of raised garden beds with tomatoes and herbs, a water tank and a gum tree behind, bottlebrush along the fence, fine ink lines.",
      scenarios: [
        {
          title: "How do I get a plot?",
          description: "It's open day at the Kaurna Street Community Garden. Ask the coordinator how the garden works and how you can get a plot.",
          difficultyLevel: "beginner",
          character: {
            name: "Denise Walker",
            role: "coordinator of the Kaurna Street Community Garden",
            goal: "You're proud of the garden. Plots are 2 by 3 metres, $60 a year, and include water and compost. Members join two working bees a year, on Saturday mornings. You ask what they'd like to grow and whether they've gardened before. You explain the water roster and that chemicals are not allowed. If asked, you mention a free seedling swap on the first Sunday of the month. You give them a form.",
            demeanor: "warm, proud, relaxed, speaks slowly, uses friendly Aussie phrases",
            endCondition: "the learner has asked about plots and costs, told you what they'd like to grow, and you have explained the rules and next step",
            voice: "sage",
          },
          learnerRole: "local resident visiting on open day",
          taskCard: "- Introduce yourself and say you're interested in a plot\n- Ask about the size and cost\n- Tell Denise what you'd like to grow\n- Ask what the next step is",
          learnerOpens: true,
          timeLimitMinutes: 5,
        },
        {
          title: "There's a waitlist",
          description: "You've come back with your form, but the coordinator says all the plots are taken. Ask about the waitlist and other ways to get involved.",
          difficultyLevel: "intermediate",
          character: {
            name: "Marco Bellini",
            role: "membership volunteer at the Kaurna Street Community Garden",
            goal: "All 40 plots are taken and the waitlist is about eight months. You can add their name. If asked, you explain other options: share a plot with Rosemary, an older member who needs help, for $30 a year; or join the shared herb and fruit beds as a volunteer member for $20 and get first pick of a plot when one frees up. You ask about their availability. You push back on jumping the queue.",
            demeanor: "friendly, chatty, a bit apologetic, likes to tell stories about the garden",
            endCondition: "the learner has asked about the waitlist and other options and has chosen a way forward, and you have taken their details and next steps",
            voice: "cedar",
          },
          learnerRole: "resident hoping to join the garden",
          taskCard: "- Hand in your form and ask about getting a plot\n- Ask how long the waitlist is\n- Find out about other ways to be involved\n- Choose an option and give your details",
          learnerOpens: true,
          timeLimitMinutes: 6,
        },
        {
          title: "The watering roster argument",
          description: "Another gardener stops you to say you've missed your watering turns and been using too much water. Listen, explain your side and agree on something fair.",
          difficultyLevel: "advanced",
          character: {
            name: "Lan Tran",
            role: "long-time member who manages the watering roster",
            goal: "You say the learner missed two roster turns in January and left the hose running on their plot. You want an apology and for them to follow the roster. You push back on excuses. If the learner explains they were away or didn't understand the roster, you soften and admit the roster wasn't emailed to new members. You suggest they swap turns via the group chat and use a drip timer. You want a clear commitment.",
            demeanor: "direct, a bit frustrated, values fairness, friendly once things are clear",
            openingLine: "Oh, good, you're here. Can I have a quick word about the watering?",
            endCondition: "the learner has listened, explained or apologised where fair, and you have agreed on how they will handle watering turns and water use from now on",
            voice: "shimmer",
          },
          learnerRole: "newer member of the community garden",
          taskCard: "- Listen to Lan's concerns without getting defensive\n- Apologise where it's fair and explain your side\n- Ask how the roster works and how to swap turns\n- Agree on what you'll do from now on",
          learnerOpens: false,
          timeLimitMinutes: 8,
        },
      ],
    },
    // 9
    {
      slug: "joining-a-sports-club",
      kind: "roleplay",
      title: "Joining a Local Sports Club",
      tagline: "Ask about joining, sort out registration hiccups and talk fees and playing time.",
      description:
        "Local sports clubs, from netball and soccer to cricket, footy and basketball, are at the heart of many Australian communities, and joining one is a fast way to make friends. This course is for adults who want to sign up to play social sport. You practise asking how a club works, understanding seasons, fees and training times, explaining your experience, and speaking up about a problem. In the first conversation you ring a social soccer club to ask about joining. In the second, you arrive at your first training with your registration, but something is wrong: the club has no record of your payment and you need to work it out. In the third, you have been sitting on the bench most games and the season fees have gone up, so you talk to the coach about playing time and ask about a payment plan without souring things.",
      keywords: ["sports club", "social sport", "registration", "fees", "training", "teamwork"],
      whatYouGet: [
        "Language for asking about seasons, fees and training times",
        "Practice sorting out a registration problem in person",
        "Polite ways to raise playing time and money with a coach",
      ],
      audience: "Adults who want to join a local social sports club and get involved.",
      bannerBrief: "A loose watercolour of a suburban sports oval at sunset with a small clubhouse, gum trees along the boundary and a soccer ball in the foreground.",
      scenarios: [
        {
          title: "Can I join your social team?",
          description: "You'd like to play social soccer this season. Call the Westbourne Rovers club to ask how to join.",
          difficultyLevel: "beginner",
          character: {
            name: "Daniel Kim",
            role: "volunteer registrar for the Westbourne Rovers Soccer Club",
            goal: "You're keen for new players. The social mixed team plays Sunday afternoons, April to September, with training Wednesdays 6:30 to 8pm at Westbourne Oval. Season fees are $220, including a shirt and insurance. Shin pads and boots are needed. You ask about their experience and position. Beginners are welcome. You suggest coming to a free trial training next Wednesday and give the club email to register.",
            demeanor: "upbeat, encouraging, a bit fast but repeats when asked",
            openingLine: "Hey, Westbourne Rovers, Daniel speaking!",
            endCondition: "the learner has asked about the team, training times and fees, and you have invited them to a trial training and explained how to register",
            voice: "ash",
          },
          learnerRole: "adult wanting to play social soccer",
          taskCard: "- Say you want to join the social team\n- Ask when and where they train and play\n- Ask how much it costs\n- Tell Daniel about your experience",
          learnerOpens: false,
          timeLimitMinutes: 5,
        },
        {
          title: "My registration isn't showing",
          description: "You've arrived at your first netball training, but the team manager can't find your registration or payment. Explain what you did and sort it out.",
          difficultyLevel: "intermediate",
          character: {
            name: "Nadia Khoury",
            role: "team manager at the Seaview Sharks Netball Club",
            goal: "You check your list and the learner isn't on it. Without registration they're not insured to train. You ask when and how they registered and paid. If they say they paid $180 online two weeks ago, you suspect it went to last season's form. You ask for the receipt or bank reference. If they show it, you let them do a fitness session today but not match play, and promise to fix it with the club secretary by Friday.",
            demeanor: "organised, friendly but firm about insurance rules, apologetic about club admin",
            openingLine: "Hi! Welcome. Sorry, what was your name again? I can't see you on my list.",
            endCondition: "the learner has explained when and how they registered and paid, and you have agreed what they can do today and how the registration will be fixed",
            voice: "marin",
          },
          learnerRole: "new player at first training",
          taskCard: "- Give your name and say you've registered\n- Explain when and how you paid\n- Offer proof, like a receipt or reference number\n- Find out if you can train today and what happens next",
          learnerOpens: false,
          timeLimitMinutes: 6,
        },
        {
          title: "Playing time and fees with the coach",
          description: "You've spent most of the season on the bench, and the club has just raised fees. Talk to your cricket coach about more game time and a payment plan.",
          difficultyLevel: "advanced",
          character: {
            name: "Steve Pappas",
            role: "coach of the Thursday night social cricket team at Glenroy Cricket Club",
            goal: "You pick players who come to training, and the learner missed four sessions. You push back on promising game time. If they explain the missed sessions were due to shift work, you offer a rotation so everyone bats at least every second week. Fees rose from $150 to $190 for new nets. You can't discount, but if asked you'll check with the treasurer about paying in two $95 instalments.",
            demeanor: "laid-back but blunt, dislikes complaining, respects honest and direct players",
            openingLine: "Yeah, mate, what's on your mind? Got about five minutes before I lock up the nets.",
            endCondition: "the learner has raised both playing time and fees calmly, and you have agreed on a rotation or other change and a next step on payment",
            voice: "ballad",
          },
          learnerRole: "player on the social cricket team",
          taskCard: "- Raise your concern about playing time politely\n- Explain any reasons you missed training\n- Ask about the fee increase and a payment plan\n- Agree on specific changes and next steps",
          learnerOpens: false,
          timeLimitMinutes: 8,
        },
      ],
    },
    // 10
    {
      slug: "op-shops-volunteering-and-events",
      kind: "roleplay",
      title: "Op-Shops, Volunteering and Local Events",
      tagline: "Donate at the op-shop, sign up to volunteer and book a stall at the community fair.",
      description:
        "Op-shops, volunteer groups and local fairs are where many people first feel part of their community in Australia. This course is for anyone who wants to give back, get local experience or simply get involved. You practise asking what is accepted, explaining your availability, asking about rules and costs, and negotiating when plans don't quite fit. In the first conversation you drop off donations at a charity op-shop and check what they can take. In the second, you sign up to volunteer at the op-shop, but the shifts on offer clash with your work, so you need to explain and find another option. In the third, you want a stall at the local community fair to sell homemade food, but the organiser says the food stalls are full and there are permit rules, so you need to negotiate a spot, the cost and what you are allowed to sell.",
      keywords: ["op-shop", "volunteering", "donations", "community events", "markets", "availability"],
      whatYouGet: [
        "Everyday language for donating and volunteering locally",
        "Practice explaining your availability and finding a fit",
        "Language for negotiating a stall booking with rules and costs",
      ],
      audience: "Anyone who wants to donate, volunteer or take part in local community events.",
      bannerBrief: "A loose watercolour of a small op-shop shopfront with racks of clothes outside and bunting for a community fair, gum leaves and bottlebrush in the corners.",
      scenarios: [
        {
          title: "Dropping off donations",
          description: "You've got two bags of clothes, some kitchen items and an old heater to donate. Take them to the op-shop and check what they can accept.",
          difficultyLevel: "beginner",
          character: {
            name: "Beryl Thompson",
            role: "volunteer at the Hope Street Op-Shop in Unley",
            goal: "You've volunteered here for 12 years. You're happy to take clean clothes, books and kitchenware. You can't take electrical items like heaters because they need testing, and you can't take anything broken or stained. You ask what's in the bags. If asked, you explain the heater could go to the council's e-waste drop-off on Saturdays. You thank them and offer a receipt if they want one.",
            demeanor: "kind, chatty, slow speaker, calls people 'love'",
            endCondition: "the learner has handed over the donations, found out what can't be accepted and where else it could go, and you have thanked them",
            voice: "coral",
          },
          learnerRole: "local resident donating items",
          taskCard: "- Say you have some items to donate\n- Tell Beryl what's in your bags\n- Ask what they can't accept\n- Ask where you can take anything they don't want",
          learnerOpens: true,
          timeLimitMinutes: 5,
        },
        {
          title: "Volunteer shifts that don't fit",
          description: "You'd like to volunteer at the op-shop, but the shifts offered clash with your job. Explain your availability and find another way to help.",
          difficultyLevel: "intermediate",
          character: {
            name: "Rosa Fonoti",
            role: "volunteer coordinator at the Hope Street Op-Shop",
            goal: "You need volunteers for weekday shifts, 9am to 1pm, serving customers. You ask why they want to volunteer and what they've done before. You push back a little because weekends are well covered. If the learner explains their work hours, you mention Thursday late-night sorting, 5 to 8pm, or the second-Saturday pop-up stall at the market. All volunteers need a police check, which the shop pays for, and a two-hour induction.",
            demeanor: "energetic, welcoming, a bit hurried, keen to find a fit",
            openingLine: "Hi! You're here about volunteering? Fantastic. Come and sit down.",
            endCondition: "the learner has explained their availability and reasons, and you have agreed on a shift that fits plus the next steps like the police check and induction",
            voice: "sage",
          },
          learnerRole: "person applying to volunteer",
          taskCard: "- Say why you'd like to volunteer\n- Explain your work hours and when you're free\n- Ask about other shifts or roles\n- Find out what you need to do before you start",
          learnerOpens: false,
          timeLimitMinutes: 6,
        },
        {
          title: "A stall at the community fair",
          description: "You want a stall at the Brompton Spring Fair to sell homemade dumplings, but the organiser says food stalls are full and there are rules. Negotiate a spot that works.",
          difficultyLevel: "advanced",
          character: {
            name: "Imran Sheikh",
            role: "volunteer organiser of the Brompton Spring Fair",
            goal: "The fair is Saturday 9 November, 10am to 3pm. All 12 food stalls are taken. You push back because food sellers need a council temporary food permit and a kitchen check. You can offer a general stall at $40, selling packaged frozen dumplings with labels, if the permit is sorted, or the waitlist for a food stall at $75. If asked, you mention a free cooking demo slot on the main stage at 1pm.",
            demeanor: "friendly but stretched, talks fast, cautious about rules, open to ideas",
            openingLine: "Hi there, Imran. You've emailed about a food stall, yeah? Bit of a tricky one, I'm afraid.",
            endCondition: "the learner has asked about options, handled the rules about permits, and you have agreed on a specific stall type, cost or waitlist plus what they need to do",
            voice: "verse",
          },
          learnerRole: "local resident who wants to sell homemade food",
          taskCard: "- Explain what you want to sell and why\n- Ask what options there are if food stalls are full\n- Ask about permits and costs\n- Agree on a specific option and your next steps",
          learnerOpens: false,
          timeLimitMinutes: 8,
        },
      ],
    },
  ],
};
