import type { OriginalCreator } from "./types";

export const schoolGateStudio: OriginalCreator = {
  handle: "school-gate-studio",
  displayName: "School Gate Studio",
  tagline: "Everyday English for parents: the school office, the classroom door, the footy oval and the chat at pick-up.",
  bio: "School Gate Studio is for parents raising kids in Australia in a second language. We know the school gate can feel like its own country, with Kindy forms, permission slips, uniform shops, sick-day phone calls and quick chats with teachers who are always in a hurry. Our courses let you practise those moments out loud before they happen for real, with friendly characters who get busier and trickier as you improve. Every scenario is set in and around Perth, from the front office to the Saturday sports club, and focuses on the words parents actually need. A XINGO Original studio, free to practise.",
  location: "Perth, WA",
  accent: "#B45309",
  visualStyle: "Crayon and marker doodles that look kid-drawn: wobbly outlines, waxy crayon texture and loose scribble fills in amber and sky blue on plain white paper.",
  logoBrief: "A wobbly crayon-drawn school gate with a small amber sun above it and the words School Gate Studio scribbled underneath in sky-blue marker on white paper.",
  avatarBrief: "A kid-drawn crayon portrait of a smiling parent and child holding hands at a gate, in amber and sky-blue scribbles on a white paper circle.",
  courses: [
    // 1. Enrolment
    {
      slug: "enrolling-at-a-new-school",
      kind: "roleplay",
      title: "Enrolling Your Child at a New School",
      tagline: "Walk into the front office, ask the right questions and leave with your child's place sorted.",
      description:
        "This course is for parents who have just moved to a new suburb, or to Australia, and need to enrol a child at a local primary school. You'll practise the language of the front office: giving your child's details, asking what documents you need, understanding words like catchment, Kindy and Pre-primary, and checking start dates, before and after school care and what to bring on day one. In the first scenario, a friendly office manager walks you through a simple enrolment and answers your questions slowly. In the second, things get messier: a document is missing and you need to work out what you can bring instead and when. In the third, you meet an enrolment officer who tells you your address is outside the school's local area and the year group is full. You'll need to explain your situation clearly, ask about options, stay polite under pressure and leave with a clear next step in writing.",
      keywords: ["school enrolment", "front office", "primary school", "catchment area", "documents", "parents"],
      whatYouGet: [
        "Three front-office conversations that move from simple to stressful",
        "Practice giving dates of birth, addresses and contact details clearly",
        "Phrases for asking about documents, start dates and care options",
        "A calm way to push back and ask for options when the answer is no",
      ],
      audience: "Parents enrolling a child at an Australian primary school who want to feel confident at the front office.",
      bannerBrief: "A crayon-drawn school front office with a smiling receptionist behind a wobbly desk, a parent holding a folder of papers and a child peeking out, in amber and sky blue on white paper.",
      scenarios: [
        {
          title: "Enrolling for Pre-primary at the Front Office",
          description: "You're at the front office of Banksia Grove Primary to enrol your five-year-old in Pre-primary for next term. Give your child's details and ask what you need to bring.",
          difficultyLevel: "beginner",
          character: {
            name: "Karen Whitfield",
            role: "office manager at Banksia Grove Primary School",
            goal: "You're helping a parent enrol their child in Pre-primary. Ask for the child's full name, date of birth, home address and a parent phone number. Explain they need a birth certificate, proof of address like a lease or power bill, and the child's immunisation record. Term starts Monday 13 October; drop-off is 8.30am at the Pre-primary gate. Before and after school care is run by Little Wattles on site. Only mention the uniform shop (open Tuesday and Thursday mornings) if asked.",
            demeanor: "warm, patient, speaks slowly, repeats things happily, short simple sentences",
            openingLine: "Good morning! Welcome to Banksia Grove Primary. How can I help you today?",
            endCondition: "the learner has given their child's name, date of birth and address and knows which documents to bring and when term starts",
            voice: "marin",
          },
          learnerRole: "parent enrolling a child",
          taskCard: "- Say you want to enrol your child in Pre-primary\n- Give your child's name, date of birth and your address\n- Ask which documents you need to bring\n- Ask what time school starts and where to drop off",
          learnerOpens: false,
          timeLimitMinutes: 5,
        },
        {
          title: "Missing a Document on Enrolment Day",
          description: "You're back at the office to finish enrolling your eight-year-old in Year 3, but you don't have proof of address because you've just moved. Find out what else you can bring and whether your child can start.",
          difficultyLevel: "intermediate",
          character: {
            name: "Stavros Papadopoulos",
            role: "deputy principal at Lakeside Primary School in Joondalup",
            goal: "You want the enrolment complete, but you need proof of address in the local area. A lease or a power bill is best. If the parent has neither, you'll accept a signed letter from the real estate agent or a bank statement with the new address. You ask why the child left their last school and whether they have any learning or health needs. If the parent asks nicely, you'll let the child start Thursday while the document is pending, but only if it arrives within two weeks.",
            demeanor: "friendly but businesslike, a little rushed, asks follow-up questions, uses some school jargon",
            openingLine: "Hi there, I'm Stavros, the deputy. Karen tells me we're just missing one thing for your enrolment?",
            endCondition: "the learner has agreed which alternative document they will bring, by when, and the child's start day is confirmed",
            voice: "cedar",
          },
          learnerRole: "parent who has just moved house",
          taskCard: "- Explain that you don't have a lease or power bill yet and why\n- Ask what other documents the school will accept\n- Answer questions about your child's last school and any needs\n- Ask if your child can start this week and confirm the date",
          learnerOpens: false,
          timeLimitMinutes: 6,
        },
        {
          title: "Out of Catchment and the Class Is Full",
          description: "You're meeting the enrolment officer at Riverside Primary, and you've just been told your new address is outside the local intake area and Year 5 is full. Explain your situation, ask about every option and leave with a clear next step.",
          difficultyLevel: "advanced",
          character: {
            name: "Priya Raman",
            role: "enrolment officer at Riverside Primary School",
            goal: "You must protect places for local-area families. Year 5 has 31 students and you won't add more. You first suggest Hillcrest Primary, 2.5 km away, which has space. You push back on reasons like 'it's closer to work'. If the parent mentions a sibling already at Riverside, a medical need or a bus route problem, you offer to add the child to the waitlist and put the request to the principal, with an answer within five school days. Only give the waitlist position (third) if asked directly.",
            demeanor: "polite, firm, by-the-book, chooses words carefully, softens slightly when given good reasons",
            openingLine: "Thanks for waiting. I'm afraid I've checked your address and it sits outside our local intake area, and Year 5 is currently full.",
            endCondition: "the learner has explained their reasons, heard the alternatives, and agreed a clear next step such as the waitlist or the other school, with a timeframe",
            voice: "coral",
          },
          learnerRole: "parent wanting a place at a full school",
          taskCard: "- Stay calm and ask what 'outside the intake area' means for you\n- Give your strongest reasons for wanting this school\n- Ask about the waitlist and any other options\n- Get a clear next step and a date you will hear back\n- Thank the officer, even if you didn't get what you wanted",
          learnerOpens: false,
          timeLimitMinutes: 8,
        },
      ],
    },
    // 2. Parent-teacher
    {
      slug: "parent-teacher-chats",
      kind: "roleplay",
      title: "Parent-Teacher Chats",
      tagline: "From a quick hello at the classroom door to a tough talk about behaviour.",
      description:
        "This course is for parents who want to talk to their child's teacher with confidence, whether it's a two-minute chat at the classroom door or a booked parent-teacher interview. You'll practise asking how your child is going, understanding report and reading-level language, sharing what you see at home, and agreeing on a plan together. The first scenario is a relaxed chat with a Year 1 teacher about how your child is settling in. The second is a booked interview where the teacher raises a concern about reading, and you need to understand the problem and the support on offer. The third is the hardest: a Year 6 teacher calls you in after a playground incident, and you don't agree with how your child has been described. You'll need to listen, give your side respectfully, ask for facts and leave with a fair plan.",
      keywords: ["parent-teacher interview", "school report", "reading", "behaviour", "primary school", "parents"],
      whatYouGet: [
        "Three teacher conversations, from friendly to difficult",
        "Words for reports, reading levels, goals and support plans",
        "Phrases to share home information and ask what you can do to help",
        "Practice disagreeing politely and asking for a follow-up",
      ],
      audience: "Parents of primary school children who want to understand and speak up in teacher meetings.",
      bannerBrief: "A crayon doodle of a parent and a teacher sitting on tiny classroom chairs at a low table covered in drawings, amber and sky-blue scribbles on white paper.",
      scenarios: [
        {
          title: "How Is My Child Settling In?",
          description: "You're catching your daughter's Year 1 teacher at the classroom door after school. Ask how she's settling in and mention that she's been tired at home.",
          difficultyLevel: "beginner",
          character: {
            name: "Hannah O'Brien",
            role: "Year 1 teacher at Coogee Beach Primary",
            goal: "You're happy to have a quick chat. Mia is settling in well, loves art, and is making friends, especially with a girl called Ruby. She's a bit quiet at mat time. You ask how she seems at home. If the parent says she's tired, suggest an earlier bedtime and mention that Year 1 has sport on Wednesdays and Fridays, which can be tiring. Offer a longer meeting next week if they'd like one, Tuesday at 3.15pm.",
            demeanor: "cheerful, encouraging, speaks clearly, gives small concrete examples",
            endCondition: "the learner has asked how their child is going, shared the tiredness concern, and either booked or declined a longer meeting",
            voice: "sage",
          },
          learnerRole: "parent of a Year 1 student",
          taskCard: "- Say hello and ask if the teacher has a minute\n- Ask how your daughter Mia is settling in\n- Mention that she's been very tired after school\n- Ask if you can talk again later if needed",
          learnerOpens: true,
          timeLimitMinutes: 5,
        },
        {
          title: "A Concern About Reading",
          description: "You're at a booked parent-teacher interview for your son in Year 4. The teacher is worried about his reading, so find out what the problem is and what support the school can offer.",
          difficultyLevel: "intermediate",
          character: {
            name: "Marco Bellini",
            role: "Year 4 teacher at Morley Park Primary",
            goal: "You want the parent to understand that Leo is reading about a year below his class level. He guesses words and avoids reading aloud. You recommend a small-group reading program three mornings a week with the support teacher, Mrs Lowe, and 15 minutes of reading at home each night. You ask what language the family reads in at home and stress that reading in any language helps. Only mention a possible hearing or eye check if the parent asks what could be causing it.",
            demeanor: "kind, organised, uses school words like 'reading level' and 'intervention' then explains them",
            openingLine: "Thanks for coming in. Leo's a lovely kid, and I want to talk to you about his reading.",
            endCondition: "the learner understands the reading concern, has asked about support, and agreed on what they will do at home",
            voice: "ash",
          },
          learnerRole: "parent of a Year 4 student",
          taskCard: "- Ask the teacher to explain what 'below level' means\n- Ask what the school will do to help\n- Share what reading happens at home\n- Agree on one or two things you will do at home",
          learnerOpens: false,
          timeLimitMinutes: 7,
        },
        {
          title: "Called In After a Playground Incident",
          description: "You're meeting your son's Year 6 teacher after a fight at lunchtime. Your son says he was defending a friend, so listen, give his side respectfully and leave with a fair plan.",
          difficultyLevel: "advanced",
          character: {
            name: "Lien Tran",
            role: "Year 6 teacher at Midland Heights Primary",
            goal: "You need to report that Aiden pushed another boy over at lunch, and the boy grazed his knee. Aiden will miss lunchtime play for two days. You push back if the parent simply says the other boy started it. If the parent asks for details, admit that the duty teacher didn't see the start and that two students say the other boy was teasing a friend. Then you'll agree to talk to both boys again and call the parent by Friday.",
            demeanor: "serious, calm, careful with facts, slightly defensive at first, fair when asked good questions",
            openingLine: "Thanks for coming in at short notice. I need to talk to you about what happened with Aiden at lunchtime today.",
            endCondition: "the learner has given their son's side, asked for the facts, and agreed on a follow-up plan with the teacher",
            voice: "shimmer",
          },
          learnerRole: "parent of a Year 6 student",
          taskCard: "- Listen to what the teacher says happened\n- Calmly explain your son's side of the story\n- Ask who saw the start of the incident\n- Ask what the consequence is and if it's fair to all students\n- Agree on a follow-up and when you'll hear back",
          learnerOpens: false,
          timeLimitMinutes: 8,
        },
      ],
    },
    // 3. Sick child
    {
      slug: "calling-in-a-sick-child",
      kind: "roleplay",
      title: "Calling In a Sick Child",
      tagline: "Absence lines, sick bay phone calls and explaining days off without stress.",
      description:
        "This course is for parents who need to talk to the school about illness and absences, often over the phone and in a hurry. You'll practise leaving clear absence messages, describing symptoms in simple words, arranging pick-up and explaining days away. The first scenario is a short phone call to the attendance line to report that your child is home sick. In the second, the school calls you at work because your child is unwell in sick bay, and you can't get there straight away, so you'll need to work out who can collect them and when. The third is a follow-up meeting with an assistant principal about several unexplained absences, where you need to explain what's been happening, correct a misunderstanding and agree on a plan. Along the way you'll learn polite phrases for urgent calls and how to ask the school to repeat or confirm important details.",
      keywords: ["absence", "sick child", "school phone call", "attendance", "pick-up", "parents"],
      whatYouGet: [
        "Three phone and office conversations about illness and absence",
        "Simple ways to describe symptoms without medical jargon",
        "Phrases for arranging an urgent pick-up when you're at work",
        "Practice explaining absences and agreeing a plan with the school",
      ],
      audience: "Parents who need to report absences or deal with a sick child during the school day.",
      bannerBrief: "A crayon-drawn child tucked up on a couch with a thermometer and a parent on the phone beside them, wobbly amber and sky-blue lines on white paper.",
      scenarios: [
        {
          title: "Phoning the Absence Line",
          description: "You're calling the school to say your daughter is home sick today. Give her name, class and what's wrong, and say when you think she'll be back.",
          difficultyLevel: "beginner",
          character: {
            name: "Sharon Mitchell",
            role: "attendance officer at Rockingham Shores Primary",
            goal: "You're recording today's absences. Ask for the child's full name, year and class teacher, and the reason for the absence. Ask if it's a cold, a stomach bug or something else, because stomach bugs mean staying home until 24 hours after the last symptoms, which is the school's own rule. Ask when they expect the child back. Read the details back to confirm. If asked, explain that homework can be collected from the office after 3pm.",
            demeanor: "efficient, friendly, speaks slowly and reads details back",
            openingLine: "Rockingham Shores Primary, attendance, Sharon speaking.",
            endCondition: "the learner has given their child's name, class, reason for absence and expected return day, and Sharon has read it back",
            voice: "marin",
          },
          learnerRole: "parent reporting an absence",
          taskCard: "- Say your daughter is sick and won't be at school today\n- Give her full name, year and teacher's name\n- Describe what's wrong in simple words\n- Say when you think she'll be back",
          learnerOpens: false,
          timeLimitMinutes: 5,
        },
        {
          title: "Sick Bay Calls You at Work",
          description: "You're at work when the school's first aid officer calls to say your son has a temperature and needs to go home. You can't leave for an hour, so work out who can collect him.",
          difficultyLevel: "intermediate",
          character: {
            name: "Daniel Kim",
            role: "first aid officer at Scarborough Primary School",
            goal: "You're calling because Jayden, Year 2, has a high temperature and a headache and is lying down in sick bay. He needs to go home within the hour. You can only release him to a person on the emergency contact list, which shows his parent and a neighbour, Mrs Collins. You push back if the parent suggests a friend who isn't on the list. You ask about allergies and whether you can give him water. Only mention that you can update the contact list by email if asked.",
            demeanor: "calm, kind, a little urgent, clear about the rules",
            openingLine: "Hi, it's Daniel from the sick bay at Scarborough Primary. Jayden's okay, but he's not feeling well and needs to go home.",
            endCondition: "the learner has agreed who will collect the child and roughly when, and answered the questions about allergies",
            voice: "verse",
          },
          learnerRole: "working parent",
          taskCard: "- Ask what's wrong and how your son is now\n- Explain you can't leave work right away\n- Arrange for someone allowed to collect him\n- Answer questions about allergies and confirm a pick-up time",
          learnerOpens: false,
          timeLimitMinutes: 6,
        },
        {
          title: "Explaining Several Absences",
          description: "You're meeting the assistant principal because the school has recorded six unexplained absences for your daughter this term. Some were sick days you did report, so explain what happened and agree a plan.",
          difficultyLevel: "advanced",
          character: {
            name: "Fatima Haddad",
            role: "assistant principal at Fremantle Hills Primary",
            goal: "You're worried about Sara's attendance: six unexplained days this term. You want reasons, and you remind the parent that every absence needs a note or a call. You push back on vague answers. If the parent says they phoned for some days, check and admit that two calls were logged under the wrong student, so it's really four. If the parent mentions Sara is anxious about school, you soften and offer a meeting with the school psychologist, Mr Grey, next Wednesday.",
            demeanor: "professional, direct, concerned rather than angry, softens when trust is built",
            openingLine: "Thanks for coming in. I wanted to talk about Sara's attendance this term, because we've got six days with no explanation.",
            endCondition: "the learner has explained the absences, corrected the record and agreed a plan for future absences or support",
            voice: "coral",
          },
          learnerRole: "parent of a Year 5 student",
          taskCard: "- Explain the days your daughter was sick and that you did call\n- Ask the school to check its records\n- Give an honest reason for any other days\n- Agree how you'll report absences from now on\n- Ask what support is available if she's worried about school",
          learnerOpens: false,
          timeLimitMinutes: 8,
        },
      ],
    },
    // 4. Childcare
    {
      slug: "childcare-and-daycare-english",
      kind: "roleplay",
      title: "Childcare and Daycare Conversations",
      tagline: "Centre tours, pick-up handovers and sorting out fees and days.",
      description:
        "This course is for parents of babies and toddlers using, or about to use, a childcare centre. You'll practise the everyday language of daycare: asking about routines, meals and sleep, understanding an incident report at pick-up, and talking through fees, bookings and waitlists. In the first scenario, you take a relaxed tour of a centre and ask the director your questions. In the second, an educator tells you at pick-up that your toddler was bitten by another child, and you need to understand what happened and what the centre is doing about it. In the third, you sit down with the centre manager to change your booked days, question a charge on your statement and ask about the waitlist for an extra day. You'll need to be clear about what you want, check the numbers and negotiate a fair outcome without losing your place.",
      keywords: ["childcare", "daycare", "toddler", "centre tour", "incident report", "fees"],
      whatYouGet: [
        "Three daycare conversations from first visit to fee dispute",
        "Words for routines, sleep, meals, allergies and incidents",
        "Practice questioning a charge and changing booked days",
        "Phrases to stay friendly while you negotiate",
      ],
      audience: "Parents of babies and toddlers who are starting or already using childcare in Australia.",
      bannerBrief: "A crayon doodle of toddlers playing in a sandpit under a big amber sun with a parent waving at the gate, wobbly sky-blue lines on white paper.",
      scenarios: [
        {
          title: "Touring a Childcare Centre",
          description: "You're touring Little Gumnuts Early Learning with the centre director. Ask about the daily routine, meals, sleep and how they settle new children.",
          difficultyLevel: "beginner",
          character: {
            name: "Jessica Lam",
            role: "director at Little Gumnuts Early Learning in Subiaco",
            goal: "You're proud of your centre and want the family to enrol. The toddler room has 15 children and four educators. Doors open 6.30am to 6pm. A cook makes morning tea, lunch and afternoon tea on site, and you cater for allergies. Children sleep after lunch on their own bedding. New children do two short settling visits first. A day costs $142. Only mention there's a three-month waitlist for Mondays if asked about days.",
            demeanor: "bright, welcoming, talks with her hands, slows down when asked",
            openingLine: "Hi, welcome to Little Gumnuts! I'm Jessica. Come in and I'll show you around the toddler room.",
            endCondition: "the learner has asked about routine, meals, sleep and settling in, and said whether they'd like to enrol",
            voice: "sage",
          },
          learnerRole: "parent looking for childcare",
          taskCard: "- Ask about a normal day in the toddler room\n- Ask about meals and sleep\n- Ask how they help new children settle in\n- Ask the cost and which days are available",
          learnerOpens: false,
          timeLimitMinutes: 5,
        },
        {
          title: "Your Toddler Was Bitten Today",
          description: "You're collecting your two-year-old from daycare when an educator says another child bit her arm today. Find out what happened, what they did and how they'll stop it happening again.",
          difficultyLevel: "intermediate",
          character: {
            name: "Tevita Fifita",
            role: "educator in the toddler room at Little Gumnuts Early Learning",
            goal: "You need to tell the parent that Zara was bitten on her upper arm at 10.40am while playing with blocks. The skin wasn't broken. You washed it, put a cold pack on, and she settled in five minutes. You ask the parent to sign the incident report. You won't name the other child, because of privacy, and you gently push back if asked. You can explain that the room is watching that child closely and adding an extra educator in the block corner.",
            demeanor: "gentle, apologetic, calm, a little nervous about the parent's reaction",
            openingLine: "Hi, before you go, I just need to let you know about a small incident with Zara today.",
            endCondition: "the learner has heard what happened, asked about the follow-up, and signed or agreed to sign the incident report",
            voice: "ballad",
          },
          learnerRole: "parent at daycare pick-up",
          taskCard: "- Ask exactly what happened and when\n- Ask how your daughter was looked after\n- Ask what the centre will do to stop it happening again\n- Read and agree to sign the incident report",
          learnerOpens: false,
          timeLimitMinutes: 6,
        },
        {
          title: "Changing Days and Questioning a Charge",
          description: "You're meeting the centre manager to swap your booked days and ask about a charge on your statement for a day your son was sick. Negotiate a fair result without losing your spot.",
          difficultyLevel: "advanced",
          character: {
            name: "Rosa Esposito",
            role: "centre manager at Little Gumnuts Early Learning",
            goal: "You want to keep the family but follow centre policy. Booked days are charged even when a child is sick, so the $142 charge stands, but you'll waive it once if the parent shows a doctor's certificate. The parent wants to swap Wednesday for Monday; Monday has a three-month waitlist. You can offer Thursday now, or Monday from January. You push back if they ask to drop a day with less than two weeks' notice. Only mention the family referral discount if they mention a friend.",
            demeanor: "brisk, polite, numbers-focused, firm on policy but open to a deal",
            openingLine: "Come on in. I've got your statement here. What would you like to go through?",
            endCondition: "the learner has raised both issues, the charge has been resolved or explained, and new days have been agreed with a start date",
            voice: "shimmer",
          },
          learnerRole: "parent of a child in long day care",
          taskCard: "- Ask why you were charged for the day your son was sick\n- Ask if anything can be done about the charge\n- Ask to swap Wednesday for Monday\n- Choose between the options offered and confirm the start date",
          learnerOpens: false,
          timeLimitMinutes: 8,
        },
      ],
    },
    // 5. Pick-up chats, playdates, parties
    {
      slug: "pick-up-chats-playdates-and-parties",
      kind: "roleplay",
      title: "Pick-up Chats, Playdates and Parties",
      tagline: "Small talk at the school gate, birthday party RSVPs and saying no nicely.",
      description:
        "This course is for parents who want to feel at ease with the other mums and dads at school. You'll practise the social side of school life: small talk while you wait at the gate, setting up a playdate, replying to a birthday invitation and handling the awkward moments that come with kids' friendships. In the first scenario, a friendly parent chats with you at pick-up and suggests a playdate. In the second, you call a dad who is hosting a birthday party to RSVP late and explain your child's food allergy. In the third, a parent you know asks you to take on the class fete stall and mentions a falling-out between your kids. You'll practise saying no without causing offence, offering something smaller instead and repairing a friendship gently. Expect casual Aussie English, quick jokes and people who talk over each other a little.",
      keywords: ["small talk", "school pick-up", "playdate", "birthday party", "other parents", "making friends"],
      whatYouGet: [
        "Three social chats with other parents, from easy to awkward",
        "Natural small talk and casual Australian expressions",
        "Phrases for RSVPs, allergies and arranging playdates",
        "Ways to decline politely and smooth over kids' fallings-out",
      ],
      audience: "Parents who want to make friends and handle social chats with other school families.",
      bannerBrief: "A crayon drawing of parents chatting by a school fence with balloons and a lopsided birthday cake floating above them, amber and sky-blue scribbles on white paper.",
      scenarios: [
        {
          title: "Chatting at the School Gate",
          description: "You're waiting at the gate for the bell when another parent from your son's class says hello. Make small talk and set up a playdate for the weekend.",
          difficultyLevel: "beginner",
          character: {
            name: "Leilani Fonoti",
            role: "parent of a Year 2 student at Ellenbrook Primary",
            goal: "You're friendly and want your son Noah to have a playdate with the learner's child, because they play together every day. You chat about the weather, the long wait at pick-up and the school disco next Friday. You ask where the family lives and if they're new. You suggest Saturday morning at Lakeside Park, around 10am, near the big playground. You offer to swap phone numbers. If asked, you mention you work part-time at the library.",
            demeanor: "bubbly, chatty, laughs easily, uses casual Aussie English like 'heaps' and 'no worries'",
            openingLine: "Hi! You're Ethan's mum or dad, aren't you? Noah talks about him heaps!",
            endCondition: "the learner has made some small talk and agreed or politely declined a playdate time and place",
            voice: "coral",
          },
          learnerRole: "parent waiting at school pick-up",
          taskCard: "- Say hello and introduce yourself\n- Make some small talk about school or the weekend\n- Agree on a playdate day, time and place\n- Swap contact details",
          learnerOpens: false,
          timeLimitMinutes: 5,
        },
        {
          title: "Late RSVP and a Food Allergy",
          description: "You're phoning a dad to RSVP late to his daughter's birthday party and to explain that your child has a nut allergy. Check the plan and offer to help.",
          difficultyLevel: "intermediate",
          character: {
            name: "Arjun Mehta",
            role: "parent hosting his daughter's seventh birthday party",
            goal: "You're hosting Anika's party this Saturday, 2pm to 4pm, at Jumping Joeys trampoline centre in Malaga. RSVPs closed yesterday and you've already given numbers, but you can add one child for $25 if asked nicely. The party food is pizza, fairy bread and a chocolate cake from a local bakery; you don't know if it contains nuts. You're slightly stressed. You're happy for the parent to bring a safe snack and stay for the party. Socks are required on the trampolines.",
            demeanor: "friendly but distracted, slightly stressed, talks fast, relieved when someone offers help",
            openingLine: "Hello, Arjun speaking.",
            endCondition: "the learner has confirmed their child is coming, explained the allergy, and agreed a plan for the food",
            voice: "cedar",
          },
          learnerRole: "parent of an invited child",
          taskCard: "- Apologise for replying late and ask if your child can still come\n- Explain your child's nut allergy clearly\n- Ask what food there will be and offer a solution\n- Confirm the time, place and anything to bring",
          learnerOpens: true,
          timeLimitMinutes: 6,
        },
        {
          title: "Saying No to the Fete Stall",
          description: "You're at pick-up when a parent asks you to run the class stall at the school fete, then mentions your kids have fallen out. Decline the big job, offer something smaller and smooth things over.",
          difficultyLevel: "advanced",
          character: {
            name: "Angela Russo",
            role: "class parent rep for Year 3 at Kingsway Primary",
            goal: "You want the learner to run the cake stall at the school fete on Saturday 8 November, 9am to 1pm. You push hard twice: 'it's only one morning', 'everyone else has done one'. If they decline politely, you'll accept a smaller job like baking or one hour on the stall. Then you mention your daughter Chloe came home upset because the learner's child left her out at lunch. You want it sorted. If the learner listens and suggests a fix, you warm up.",
            demeanor: "energetic, persuasive, a bit pushy, quick to take things personally but forgives fast",
            openingLine: "Oh good, I was hoping I'd catch you! Have you got a sec? I need a huge favour for the fete.",
            endCondition: "the learner has declined the main job politely, offered an alternative, and responded kindly to the friendship problem",
            voice: "sage",
          },
          learnerRole: "parent at afternoon pick-up",
          taskCard: "- Politely decline running the fete stall and give a reason\n- Offer a smaller way you can help\n- Listen to the other parent's worry about your children\n- Suggest a way to fix things and keep the friendship",
          learnerOpens: false,
          timeLimitMinutes: 8,
        },
      ],
    },
    // 6. Junior sport
    {
      slug: "junior-sport-club-english",
      kind: "roleplay",
      title: "Talking to the Junior Sport Coach",
      tagline: "Sign-ups, game-time worries and club politics at the weekend oval.",
      description:
        "This course is for parents whose kids play junior sport on weekends, from footy and soccer to netball. You'll practise the language of the local club: signing up, asking about training times and gear, raising concerns with a coach and dealing with fees and volunteer rosters. In the first scenario, you meet a friendly junior footy coach at the first training session and ask the basic questions. In the second, you talk to a soccer coach after a game because your daughter has been sitting on the bench, and you need to raise it without sounding like an angry parent on the sideline. In the third, the club registrar chases you about unpaid fees and a missed canteen shift, and you need to explain your situation, ask about a payment plan and agree what you can realistically do. You'll learn to stay friendly and clear when emotions run high.",
      keywords: ["junior sport", "football club", "soccer coach", "training", "club fees", "volunteering"],
      whatYouGet: [
        "Three conversations at the club, from sign-up to fee trouble",
        "Words for training, gear, positions, rosters and registration",
        "Practice raising a concern with a coach calmly",
        "Phrases for asking about payment plans and volunteer swaps",
      ],
      audience: "Parents whose children play community sport and want to talk easily with coaches and clubs.",
      bannerBrief: "A crayon doodle of kids in amber jerseys chasing a wobbly ball on a sky-blue oval with a coach holding a clipboard, on white paper.",
      scenarios: [
        {
          title: "First Day at Junior Footy",
          description: "You're at your son's first junior footy training. Introduce yourself to the coach and ask about training times, gear and game days.",
          difficultyLevel: "beginner",
          character: {
            name: "Shane Walker",
            role: "Under 9s coach at Swan Valley Junior Football Club",
            goal: "You're pleased to have a new player. Training is Tuesday and Thursday, 4.30pm to 5.30pm, at Morrison Oval. Games are Sunday mornings, usually 9am, and the draw is posted on the club website each week. Kids need footy boots, a mouthguard, a water bottle and the club guernsey, which costs $45 from the canteen. Ask the boy's name, age and if he's played before. Only mention there's a sausage sizzle after the first game if asked.",
            demeanor: "laid-back, encouraging, very Aussie, uses words like 'footy', 'arvo' and 'mate'",
            endCondition: "the learner has introduced their child and knows the training times, game day and gear needed",
            voice: "ash",
          },
          learnerRole: "parent of a new junior footy player",
          taskCard: "- Say hello and introduce yourself and your son\n- Ask when training and games are\n- Ask what gear he needs and where to get it\n- Say thank you and confirm you'll be there on Thursday",
          learnerOpens: true,
          timeLimitMinutes: 5,
        },
        {
          title: "Not Enough Game Time",
          description: "You're catching the coach after a soccer game because your daughter has sat on the bench for most of the last three games. Raise your concern calmly and find out what she can work on.",
          difficultyLevel: "intermediate",
          character: {
            name: "Nikos Andreou",
            role: "Under 11 girls coach at Bayswater Soccer Club",
            goal: "You believe in fair game time but you've been short-handed and leaning on stronger players. At first you get a bit defensive: 'everyone gets a go'. If the parent stays calm and gives the numbers, you admit Isla has only played about 15 minutes a game. You explain she's missed two Wednesday trainings, which affects selection. You agree to give her at least half of each game if she comes to training, and suggest she try defence.",
            demeanor: "passionate, a bit defensive at first, fair once he feels respected, talks with lots of soccer words",
            openingLine: "Good game today, hey? Tough opposition. What can I do for you?",
            endCondition: "the learner has raised the game-time concern calmly and agreed a plan with the coach for the coming weeks",
            voice: "verse",
          },
          learnerRole: "parent of a junior soccer player",
          taskCard: "- Ask if the coach has a minute to talk\n- Explain your concern about game time with an example\n- Listen to the coach's reasons\n- Agree what your daughter can do and what the coach will do",
          learnerOpens: false,
          timeLimitMinutes: 6,
        },
        {
          title: "Unpaid Fees and a Missed Canteen Shift",
          description: "You're on the phone with the netball club registrar, who says your fees are overdue and you missed your canteen roster. Explain your situation, ask about a payment plan and agree what you can do.",
          difficultyLevel: "advanced",
          character: {
            name: "Rebecca Thornton",
            role: "registrar at Southern River Netball Club",
            goal: "Your records show the $260 season fee is three weeks overdue and the family missed their canteen shift last Saturday. Players can't take the court next week until fees are paid or a plan is agreed. You push back on 'I'll pay soon' and want a date. You can offer three payments of about $87 a fortnight. On the canteen, you're annoyed because you covered the shift yourself, but you'll accept a swap to 22 November if offered. Only mention the club's hardship support if the parent says money is tight.",
            demeanor: "tired volunteer, direct, a bit irritated at first, kind once she hears the full story",
            openingLine: "Hi, it's Bec from Southern River Netball. Look, I'm just chasing up a couple of things on Grace's registration.",
            endCondition: "the learner has explained their situation, agreed a payment plan or date, and sorted out a new canteen shift",
            voice: "sage",
          },
          learnerRole: "parent of a junior netball player",
          taskCard: "- Apologise and explain why the fees are late\n- Ask if you can pay in instalments\n- Explain why you missed the canteen shift\n- Agree a new shift and a payment date, and confirm your daughter can play",
          learnerOpens: false,
          timeLimitMinutes: 8,
        },
      ],
    },
    // 7. Excursions and forms
    {
      slug: "school-excursions-and-forms",
      kind: "roleplay",
      title: "School Excursions, Camps and Forms",
      tagline: "Permission slips, medical forms and camp questions, explained out loud.",
      description:
        "This course is for parents who feel buried in school paperwork and want to ask questions about excursions and camps with confidence. You'll practise asking what a permission form means, explaining your child's medical and dietary needs, and talking about costs and worries. In the first scenario, a teacher explains an upcoming excursion to the zoo and what you need to sign. In the second, the camp coordinator calls because your child's medical form is incomplete, and you need to give clear details about an asthma plan and dietary needs. In the third, you meet the teacher because you're unsure about letting your child go on a three-night camp: the cost is high, there's an ocean swimming activity, and your child is nervous. You'll need to ask detailed questions, explain your concerns and negotiate what works for your family.",
      keywords: ["excursion", "permission form", "school camp", "medical form", "school fees", "parents"],
      whatYouGet: [
        "Three conversations about excursions, camps and paperwork",
        "Words for consent, medical plans, dietary needs and payments",
        "Practice describing your child's needs clearly and calmly",
        "Phrases to raise worries and ask for options on costs",
      ],
      audience: "Parents who want to understand school forms and talk confidently about excursions and camps.",
      bannerBrief: "A crayon doodle of a school bus full of waving kids heading to a camp tent under amber gum trees, wobbly sky-blue outlines on white paper.",
      scenarios: [
        {
          title: "What Is This Permission Form?",
          description: "You're asking your son's teacher about a permission form for a class trip to the zoo. Find out what it involves and what you need to sign and send back.",
          difficultyLevel: "beginner",
          character: {
            name: "Joanne Pham",
            role: "Year 2 teacher at Lakeview Primary in Ballajura",
            goal: "You're explaining the class excursion to the zoo on Thursday 30 October. The bus leaves at 9am and returns by 2.30pm. Students wear full school uniform and a hat, and bring a packed lunch and water bottle. The cost is $28, paid at the office or online. The form needs a signature, a medical section and an emergency phone number by Friday. If asked, you mention you need two parent helpers.",
            demeanor: "patient, clear, organised, explains each part of the form step by step",
            endCondition: "the learner understands the excursion details, the cost and what to sign and return by Friday",
            voice: "shimmer",
          },
          learnerRole: "parent with a permission form",
          taskCard: "- Ask what the excursion is and when it is\n- Ask what your child needs to wear and bring\n- Ask how much it costs and how to pay\n- Check which parts of the form you must fill in and the due date",
          learnerOpens: true,
          timeLimitMinutes: 5,
        },
        {
          title: "The Camp Medical Form Is Incomplete",
          description: "You're on the phone with the Year 5 camp coordinator, who says your daughter's medical form is missing details. Explain her asthma plan and dietary needs clearly.",
          difficultyLevel: "intermediate",
          character: {
            name: "Vikram Iyer",
            role: "Year 5 camp coordinator at Kalamunda Primary",
            goal: "Camp is at Bickley Bush Camp, 12 to 14 November. The form for Amira says 'asthma' but has no action plan and no dietary details. You need a copy of her asthma action plan from her doctor, the name of her reliever puffer and how often she uses it, and any food needs. You ask if she can manage her own puffer. You push back if the parent wants to skip the plan: without it she can't attend. Only mention staff are first-aid trained if asked.",
            demeanor: "organised, polite, a bit hurried, checks each item off a list",
            openingLine: "Hi, it's Vikram from Kalamunda Primary. I'm calling about Amira's camp medical form. There are a few gaps.",
            endCondition: "the learner has given the asthma and dietary details and agreed when they will send the action plan",
            voice: "ballad",
          },
          learnerRole: "parent of a Year 5 student going on camp",
          taskCard: "- Ask what's missing from the form\n- Describe your daughter's asthma and puffer use in simple words\n- Explain her food needs\n- Agree when you will send the asthma plan",
          learnerOpens: false,
          timeLimitMinutes: 6,
        },
        {
          title: "Worried About the Three-Night Camp",
          description: "You're meeting the teacher because you're not sure about your son going on the Year 6 camp. Raise your concerns about the cost, the ocean swim and his nerves, and decide what will work.",
          difficultyLevel: "advanced",
          character: {
            name: "Siobhan Kelly",
            role: "Year 6 teacher leading the camp to Rottnest Island",
            goal: "You really want every child to go to camp. It costs $395 for three nights. You push back gently on 'he'll stay home'. The ocean swim is in a shallow bay with lifeguards and is optional. If the parent mentions money, you mention the school can split payments over the term and the principal can consider help privately. If the parent mentions nerves, offer for him to choose two friends for his cabin. You need a decision by 31 October.",
            demeanor: "warm, persuasive, reassuring, doesn't give up easily but respects a firm decision",
            openingLine: "Thanks for coming in. I know camp can feel like a big deal, so tell me what's on your mind.",
            endCondition: "the learner has raised their concerns, heard the options, and given a decision or agreed a date to decide",
            voice: "marin",
          },
          learnerRole: "parent of a Year 6 student",
          taskCard: "- Explain your concerns about the cost, the swimming and your son's nerves\n- Ask detailed questions about safety and supervision\n- Ask about payment options\n- Make a decision or agree when you will decide",
          learnerOpens: false,
          timeLimitMinutes: 8,
        },
      ],
    },
    // 8. Uniform shop
    {
      slug: "at-the-school-uniform-shop",
      kind: "roleplay",
      title: "At the School Uniform Shop",
      tagline: "Sizes, sold-out items and swapping the wrong polo shirt.",
      description:
        "This course is for parents buying school uniforms, often in a short opening window with a queue behind them. You'll practise asking for sizes and prices, understanding which items are compulsory, ordering things that are out of stock and returning the wrong item. In the first scenario, a friendly volunteer helps you buy a basic uniform for your child's first year. In the second, the size you need is sold out the week before term, and you need to order, ask about second-hand options and find a short-term fix. In the third, you try to return a jumper that has been worn and washed once, and the manager says it's against the returns policy. You'll need to explain what happened, ask for an exchange and stay polite while you negotiate. Along the way you'll learn clothing words like polo, skort, jumper and broad-brimmed hat.",
      keywords: ["school uniform", "uniform shop", "sizes", "returns", "second-hand", "shopping"],
      whatYouGet: [
        "Three uniform shop conversations with a growing challenge",
        "Clothing and size words you'll actually hear at school",
        "Practice ordering out-of-stock items and asking about second-hand",
        "Phrases for returns and exchanges when policy says no",
      ],
      audience: "Parents buying school uniforms who want to get the right items without stress.",
      bannerBrief: "A crayon doodle of a little shop counter with amber polo shirts and sky-blue hats hanging on wobbly racks and a parent holding up a tiny jumper, on white paper.",
      scenarios: [
        {
          title: "Buying a First School Uniform",
          description: "You're at the uniform shop buying your daughter's first uniform for Pre-primary. Ask what she needs, find the right sizes and pay.",
          difficultyLevel: "beginner",
          character: {
            name: "Margaret Doyle",
            role: "volunteer at the Banksia Grove Primary uniform shop",
            goal: "You're helping a parent buy a Pre-primary uniform. The essentials are an amber polo shirt ($24), navy shorts or a skort ($22), a navy jumper for winter ($38) and a broad-brimmed hat ($15); the school rule is 'no hat, play in the shade'. Ask the child's age and height to suggest a size, usually size 6. You take card or cash. Only mention the second-hand rack if asked about cheaper options.",
            demeanor: "grandmotherly, chatty, slow and kind, loves helping first-time parents",
            endCondition: "the learner has chosen the items and sizes, heard the total and paid",
            voice: "shimmer",
          },
          learnerRole: "parent buying a school uniform",
          taskCard: "- Say your daughter is starting Pre-primary and ask what she needs\n- Ask for help with sizes\n- Ask the price of each item and the total\n- Pay and say thank you",
          learnerOpens: true,
          timeLimitMinutes: 5,
        },
        {
          title: "Sold Out the Week Before Term",
          description: "You're at the uniform shop the week before term, and the polo shirt in your son's size is sold out. Order it, ask about second-hand options and find a short-term solution.",
          difficultyLevel: "intermediate",
          character: {
            name: "Hamid Rahimi",
            role: "manager of the Hillcrest Primary uniform shop",
            goal: "Size 10 polos are sold out. A new delivery is due in about three weeks, but you can't promise a date. You can take an order and phone when it arrives. The second-hand rack has a size 12 polo for $8, a bit big. You suggest a plain amber polo from any shop is fine for the first few weeks, but you say you'll need to check with the office before promising. You push back if asked to hold stock from someone else's order.",
            demeanor: "busy, apologetic, practical, juggling a queue behind the parent",
            openingLine: "Sorry about the wait, it's mad this week. What can I get you?",
            endCondition: "the learner has placed an order, chosen a short-term option and given a phone number for when stock arrives",
            voice: "ash",
          },
          learnerRole: "parent buying a school uniform",
          taskCard: "- Ask for a size 10 polo shirt\n- Ask when more will arrive and if you can order one\n- Ask about second-hand or other short-term options\n- Leave your contact details for when stock arrives",
          learnerOpens: true,
          timeLimitMinutes: 6,
        },
        {
          title: "Returning a Washed Jumper",
          description: "You're returning a school jumper that shrank after one wash. The shop policy says no returns on worn items, so explain what happened and negotiate an exchange.",
          difficultyLevel: "advanced",
          character: {
            name: "Christine Yeo",
            role: "uniform shop coordinator at Riverside Primary",
            goal: "The policy sign says returns only within 14 days, unworn, with tags. The jumper ($42) was bought 10 days ago and washed once. You push back twice and point to the sign. If the parent explains they followed the care label and shows it shrank a full size, you check the batch and admit two other parents complained. Then you offer an exchange for the next size up, or a credit note. You won't give a cash refund.",
            demeanor: "polite, rule-focused, slightly guarded, becomes helpful once the facts are clear",
            openingLine: "Hi there. Is that a return? I'll just need to have a look at it and the receipt.",
            endCondition: "the learner has explained the problem, pushed for a fair outcome and accepted an exchange or credit note",
            voice: "marin",
          },
          learnerRole: "parent returning a uniform item",
          taskCard: "- Explain when you bought the jumper and what happened\n- Say that you followed the washing instructions\n- Politely push back on the 'no returns' policy\n- Accept an exchange or credit and confirm the details",
          learnerOpens: true,
          timeLimitMinutes: 8,
        },
      ],
    },
    // 9. Homework help / tutor
    {
      slug: "homework-help-and-tutors",
      kind: "roleplay",
      title: "Finding Homework Help and a Tutor",
      tagline: "Ask the right questions, compare options and avoid a contract you don't want.",
      description:
        "This course is for parents looking for extra help with homework, reading or maths, whether through a tutoring centre or a private tutor. You'll practise describing what your child needs, asking about qualifications, times and costs, and comparing what's on offer. In the first scenario, you visit a tutoring centre's front desk to ask simple questions about how it works. In the second, you phone a private tutor whose times and price don't quite match what you need, so you'll need to find a workable compromise. In the third, a tutoring centre director tries to sign you up to a long contract after a free assessment, and you need to ask hard questions, decline the pressure and leave with only what you want. Along the way you'll practise numbers, days and times, and polite ways to say 'I need to think about it'.",
      keywords: ["tutor", "homework help", "tutoring centre", "maths", "reading", "contracts"],
      whatYouGet: [
        "Three conversations about tutoring, from simple to high-pressure",
        "Words for subjects, levels, sessions, terms and assessments",
        "Practice comparing prices and negotiating times",
        "Polite phrases to resist a hard sell and leave without signing",
      ],
      audience: "Parents looking for homework or tutoring support for their school-aged child.",
      bannerBrief: "A crayon drawing of a child and a tutor at a desk with a wobbly maths sum and a big amber pencil, scribbled in sky blue on white paper.",
      scenarios: [
        {
          title: "Asking at a Tutoring Centre",
          description: "You're at the front desk of a tutoring centre to ask about maths help for your Year 4 son. Find out how it works, when sessions are and what it costs.",
          difficultyLevel: "beginner",
          character: {
            name: "Kevin Zhou",
            role: "front desk coordinator at Bright Sparks Learning in Willetton",
            goal: "You're helping a parent with questions. Sessions are one hour, in groups of four, for Years 1 to 10. Maths runs Monday and Wednesday at 4pm and 5pm, and Saturday at 10am. It costs $55 a session, paid by the term. All tutors are university students or qualified teachers. New students do a free 30-minute assessment first. Ask the child's name and year. Only mention the sibling discount if asked.",
            demeanor: "friendly, upbeat, clear, happy to repeat numbers",
            endCondition: "the learner knows the session times, cost and how to start, and has booked or declined the free assessment",
            voice: "verse",
          },
          learnerRole: "parent looking for maths help",
          taskCard: "- Say your son is in Year 4 and needs help with maths\n- Ask how the sessions work and when they are\n- Ask how much it costs\n- Book or decline the free assessment",
          learnerOpens: true,
          timeLimitMinutes: 5,
        },
        {
          title: "Booking a Private Tutor",
          description: "You're phoning a private tutor about reading help for your daughter in Year 3. Her times and price don't quite suit you, so find a compromise that works.",
          difficultyLevel: "intermediate",
          character: {
            name: "Olivia Grant",
            role: "private reading tutor and retired primary teacher",
            goal: "You tutor from home in Applecross. You charge $70 an hour and are only free Tuesday 5pm and Saturday 9am. The parent may want Wednesday or a lower price. You won't go below $60, but you'll offer 45-minute sessions for $55, or a home visit for $10 extra. Ask about the child's reading and what the teacher has said. If asked, you can give a reference from another family.",
            demeanor: "kind, experienced, a little formal, firm on price but flexible on format",
            openingLine: "Hello, Olivia Grant speaking.",
            endCondition: "the learner has described their child's needs and agreed a day, time, length and price, or politely said no",
            voice: "coral",
          },
          learnerRole: "parent looking for a reading tutor",
          taskCard: "- Explain your daughter's reading needs\n- Ask when the tutor is available and the price\n- Try to get a day, time or price that suits you better\n- Agree a plan or politely say you'll keep looking",
          learnerOpens: true,
          timeLimitMinutes: 6,
        },
        {
          title: "Pressure to Sign a Year-Long Contract",
          description: "You're meeting the director of a tutoring centre after your son's free assessment. She wants you to sign a 12-month contract today, so ask hard questions and only agree to what you want.",
          difficultyLevel: "advanced",
          character: {
            name: "Jae-won Park",
            role: "director at Top Marks Tutoring in Cannington",
            goal: "You want the parent to sign a 12-month program today: two sessions a week, $3,900 a year, with a 'today only' 10% discount. You say the assessment shows the boy is 'well behind'. You push back twice on 'I'll think about it'. If asked, admit the cancellation fee is $400, and that he's about six months behind in fractions only. If the parent holds firm, you'll offer a one-term trial at $1,050 with no lock-in.",
            demeanor: "smooth, confident salesperson, friendly but pushy, uses urgency and big claims",
            openingLine: "Great news, we've finished the assessment. Have a seat and I'll show you exactly how we can help.",
            endCondition: "the learner has asked about the results, cost and cancellation terms and has either declined or agreed only to the option they chose",
            voice: "ballad",
          },
          learnerRole: "parent after a free tutoring assessment",
          taskCard: "- Ask exactly what the assessment showed\n- Ask about the total cost and cancellation fees\n- Say you won't sign today without thinking it over\n- Leave with no deal or only the option you choose",
          learnerOpens: false,
          timeLimitMinutes: 8,
        },
      ],
    },
    // 10. Interpreting
    {
      slug: "interpreting-parent-teacher-interviews",
      kind: "interpreting",
      title: "Interpreting Parent-Teacher Interviews",
      tagline: "Interpret between a teacher and a parent, from settling in to a serious concern.",
      description:
        "This course is for community interpreters and bilingual helpers who interpret at school meetings between English-speaking teachers and parents. You'll practise interpreting both ways, keeping the meaning accurate, handling school terms like reading level, learning plan and behaviour support, and staying neutral when the conversation gets emotional. In the first scenario, a Kindy teacher and a parent talk calmly about how a child is settling in. In the second, a Year 3 teacher explains that a child needs extra literacy support, and the parent has questions and worries about labels. In the third, a Year 6 teacher raises a bullying incident, the parent is upset and defensive, and both people sometimes talk too long or too fast. You'll need to interrupt politely, ask for repetition, check terms and keep both sides speaking to each other, not to you.",
      keywords: ["interpreting", "parent-teacher interview", "community interpreting", "school", "education terms", "ccl practice"],
      whatYouGet: [
        "Three school interviews to interpret, from calm to heated",
        "Practice with education terms like learning plan and reading level",
        "Experience managing long turns, interruptions and emotion",
        "A safe place to practise staying neutral and accurate",
      ],
      audience: "Interpreters and bilingual community members who interpret at school meetings for parents.",
      bannerBrief: "A crayon doodle of a teacher and a parent at a small table with an interpreter between them and wobbly speech bubbles in amber and sky blue, on white paper.",
      scenarios: [
        {
          title: "Kindy Settling-In Chat",
          description: "You're interpreting between a Kindy teacher and a parent at a short meeting about how the child is settling in. Interpret everything both ways, accurately and in the first person.",
          difficultyLevel: "beginner",
          character: {
            name: "Susan Fraser",
            role: "Kindy teacher at Wattle Grove Primary",
            goal: "You want to tell the parent that Theo is settling in well. He cried at drop-off for the first two weeks but now waves goodbye. He loves the sandpit and puzzles but doesn't speak much in class yet. You ask what he likes at home, his sleep and eating, and which language he mostly speaks at home. You suggest a short, cheerful goodbye at drop-off. Kindy days are Monday, Tuesday and alternate Wednesdays.",
            demeanor: "gentle, encouraging, speaks in short clear sentences and pauses for the interpreter",
            openingLine: "Thanks for coming in. I just wanted to have a quick chat about how Theo's settling in. He's doing really well.",
            endCondition: "how Theo is at drop-off, what he enjoys at home, his sleep and eating, and the main language spoken at home",
            voice: "sage",
          },
          client: {
            name: "Lina Moreno",
            role: "parent of a Kindy student",
            goal: "You're Theo's mother and you're a little worried. At home Theo talks a lot, loves building blocks and drawing, and sleeps from 7.30pm to 6.30am. He eats well but won't eat sandwiches. You want to know if he talks to other children and if he eats his lunch. You ask what you can do to help him make friends. You're relieved when you hear good news.",
            demeanor: "soft-spoken, polite, slightly anxious, says thank you often",
            voice: "coral",
          },
          timeLimitMinutes: 5,
        },
        {
          title: "Extra Support for Literacy",
          description: "You're interpreting at a Year 3 interview where the teacher recommends extra literacy support. The parent has questions and worries, so interpret accurately and ask for clarification when a term is unclear.",
          difficultyLevel: "intermediate",
          character: {
            name: "Peter Lambros",
            role: "Year 3 teacher at Girrawheen Primary",
            goal: "You need to explain that Mina is reading at about a Year 1 level and finds spelling hard. You recommend a small-group literacy program four mornings a week and an individual education plan, or IEP, reviewed each term. You want permission for a speech and language assessment by the school's visiting specialist. You stress this isn't a punishment and won't appear on her report as a 'label'. You use some jargon like 'phonics' and 'decoding' unless asked to explain.",
            demeanor: "kind, thorough, talks in longer turns, uses school jargon without noticing",
            openingLine: "Thanks so much for coming in. I'd like to talk about Mina's reading and some extra support we think would really help her.",
            endCondition: "the parent's understanding of the reading concern, their questions answered, and their decision about the support program and the speech and language assessment",
            voice: "cedar",
          },
          client: {
            name: "Adam Kassi",
            role: "parent of a Year 3 student",
            goal: "You're Mina's father. You worry she'll be seen as 'slow' and teased. You ask what an IEP is, whether it goes on her record, and if she'll miss other lessons. At home she reads picture books with you most nights. You want to know if the assessment costs anything. You agree to the program but want to think about the assessment, unless the teacher explains it clearly.",
            demeanor: "concerned, a bit defensive at first, asks direct questions, warms up when reassured",
            voice: "verse",
          },
          timeLimitMinutes: 7,
        },
        {
          title: "A Bullying Incident in Year 6",
          description: "You're interpreting a tense meeting where a Year 6 teacher reports that the parent's son was involved in bullying. Both people talk fast and get emotional, so manage the flow and stay neutral.",
          difficultyLevel: "advanced",
          character: {
            name: "Natalie Brooks",
            role: "Year 6 teacher at Thornlie Primary",
            goal: "You must report that Omar and two boys sent unkind messages about a classmate in a group chat and excluded him at lunch for two weeks. The school's response is a restorative meeting and losing break-time privileges for one week. You want the parent to talk to Omar and check his device use. You push back on 'he's just joking'. If the parent says Omar was also bullied earlier, you take it seriously and offer a follow-up meeting.",
            demeanor: "firm, serious, speaks quickly and in long turns when challenged, but fair",
            openingLine: "Thanks for coming in. I'm afraid this is a serious conversation. Omar has been involved in some bullying of another student, and I need to go through what happened and what happens next.",
            endCondition: "the parent's response to the incident, any information about Omar being bullied himself, their agreement to the consequences and the follow-up plan",
            voice: "shimmer",
          },
          client: {
            name: "Nora Salem",
            role: "parent of a Year 6 student",
            goal: "You're Omar's mother and you're shocked and upset. You think the school is blaming only your son. You ask to see the messages and ask about the other two boys. You reveal that last term Omar came home crying because older kids called him names, and nobody helped. You talk in long, emotional turns. You'll accept the consequences only if the school also looks into what happened to Omar.",
            demeanor: "upset, emotional, speaks fast and interrupts, protective of her son, calms down when listened to",
            voice: "marin",
          },
          timeLimitMinutes: 8,
        },
      ],
    },
  ],
};

