import type { Metadata } from "next";
import Link from "next/link";
import { LegalDocument, type LegalSection } from "@/components/marketing/legal/legal-document";
import { LEGAL_CONTACT_EMAIL } from "@/lib/legal";
import { MAX_ATTEMPT_MINUTES, packList, plans } from "@/lib/plans";
import { pageMetadata } from "@/lib/seo-metadata";

export const metadata: Metadata = pageMetadata({
  title: "Terms of Service",
  description: "The terms for using XINGO: accounts, practice minutes, subscriptions and packs, refunds, AI practice, acceptable use and your rights.",
  path: "/terms",
});

const mail = <a href={`mailto:${LEGAL_CONTACT_EMAIL}`}>{LEGAL_CONTACT_EMAIL}</a>;

const sections: LegalSection[] = [
  {
    id: "about",
    heading: "About these terms",
    body: (
      <>
        <p>
          These terms are an agreement between you and XINGO (&ldquo;XINGO&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;), which
          operates the website at xingo.ai and the XINGO practice app (together, the &ldquo;Service&rdquo;). By creating an
          account or using the Service you agree to these terms and to our <Link href="/privacy">Privacy Policy</Link>. If you
          publish courses on the marketplace, our <Link href="/creator-terms">Creator Terms</Link> also apply.
        </p>
        <p>
          Nothing in these terms excludes, restricts or modifies any right or remedy you have under the Australian Consumer Law or
          any other law that cannot be excluded.
        </p>
      </>
    ),
  },
  {
    id: "service",
    heading: "What XINGO is (and isn't)",
    body: (
      <>
        <p>
          XINGO lets you practise spoken conversations with AI voice role-players, including interpreting dialogues and speaking
          exam role-plays, and gives you scores and feedback generated by AI.
        </p>
        <ul>
          <li>
            The people you talk to in XINGO are AI characters, not real people. They can make mistakes, and their medical, legal or
            other content is for practice only. It is not advice.
          </li>
          <li>
            Scores and feedback are estimates designed to help you practise. They are not official results and don&apos;t predict or
            guarantee any result in a real test.
          </li>
          <li>
            XINGO is independent. We are not affiliated with, endorsed by or acting for NAATI, OET, IELTS, the AMC, the NMBA or any
            other exam or registration body. Exam names are used only to describe what you can practise for.
          </li>
          <li>
            Practising on XINGO doesn&apos;t award any credential, certification or registration, or guarantee employment.
          </li>
        </ul>
      </>
    ),
  },
  {
    id: "account",
    heading: "Your account",
    body: (
      <ul>
        <li>You must be at least 16 years old, or have your parent or guardian&apos;s permission, to use XINGO.</li>
        <li>Give accurate details, keep your sign-in secure, and tell us promptly if you think someone else has used your account.</li>
        <li>Accounts are personal. Don&apos;t share your account or let others practise on it.</li>
        <li>You&apos;re responsible for what happens on your account, unless it&apos;s caused by our failure to keep the Service secure.</li>
      </ul>
    ),
  },
  {
    id: "minutes",
    heading: "Practice minutes",
    body: (
      <>
        <p>
          Practice is measured in practice minutes: the time a live practice session is running, measured by our servers from the
          moment a session starts until it ends. Scoring, feedback and transcripts are included. Partial minutes are rounded up, and
          a single session is capped at {MAX_ATTEMPT_MINUTES} minutes.
        </p>
        <ul>
          <li>
            The Free plan includes {plans.free.monthlyMinutes} practice minutes each calendar month, and the{" "}
            {plans.professional.label} plan includes {plans.professional.monthlyMinutes}. Monthly minutes don&apos;t roll over.
          </li>
          <li>Minute packs add minutes that don&apos;t expire. Monthly minutes are used before pack minutes.</li>
          <li>When you run out of minutes, a session in progress ends and you can&apos;t start a new one until you have more.</li>
          <li>
            Sessions where the voice connection never started aren&apos;t charged. Sessions you leave early still use the minutes
            that ran.
          </li>
        </ul>
      </>
    ),
  },
  {
    id: "payments",
    heading: "Subscriptions, packs and payment",
    body: (
      <>
        <ul>
          <li>
            Prices are in Australian dollars and include GST where it applies. Current prices are on our{" "}
            <Link href="/pricing">pricing page</Link>: {plans.professional.label} is {plans.professional.priceLabel}; packs are{" "}
            {packList.map((pack) => `${pack.label} (${pack.minutes} minutes, ${pack.priceLabel})`).join(", ")}.
          </li>
          <li>
            Payments are processed by Stripe. We don&apos;t see or store your full card details.
          </li>
          <li>
            The {plans.professional.label} plan renews automatically each month and is charged to your payment method until you
            cancel. You can cancel at any time from Plan &amp; minutes → Invoices &amp; payment. Cancelling stops the next renewal; you
            keep {plans.professional.label} until the end of the period you&apos;ve paid for.
          </li>
          <li>
            If a renewal payment fails, we may keep your plan active for a short time while Stripe retries, then move you to the Free
            plan.
          </li>
          <li>
            We may change prices or plan inclusions. We&apos;ll tell you at least 30 days before a change affects your subscription,
            and you can cancel before it applies. Pack minutes you&apos;ve already bought are not reduced.
          </li>
        </ul>
      </>
    ),
  },
  {
    id: "refunds",
    heading: "Refunds",
    body: (
      <>
        <p>
          Our services come with guarantees that cannot be excluded under the Australian Consumer Law. If the Service has a major
          failure, you&apos;re entitled to cancel and to a refund for the unused portion, or to compensation for its reduced value. For
          a failure that isn&apos;t major, we&apos;ll fix it within a reasonable time, or you can ask for a refund.
        </p>
        <p>
          Beyond those rights, if something went wrong (for example a session dropped because of a fault on our side), email us at{" "}
          {mail} within 30 days and we&apos;ll look at it fairly, usually by restoring minutes or refunding.
        </p>
      </>
    ),
  },
  {
    id: "acceptable-use",
    heading: "Acceptable use",
    body: (
      <>
        <p>You agree not to:</p>
        <ul>
          <li>use XINGO for anything unlawful, harmful, harassing, hateful or sexual, or to impersonate a real person;</li>
          <li>try to make the AI produce harmful content, or use the Service as a general-purpose AI assistant;</li>
          <li>interfere with the Service, get around limits on minutes or access, or access it by automated means;</li>
          <li>copy, scrape, resell or reverse-engineer the Service or its content, except as the law allows; or</li>
          <li>upload content you don&apos;t have the rights to, or that includes other people&apos;s personal information without permission.</li>
        </ul>
      </>
    ),
  },
  {
    id: "content",
    heading: "Your content and ours",
    body: (
      <ul>
        <li>
          What you say in sessions, and the transcripts and results that come from it, are yours. You let us process them to run the
          Service, show you your results and progress, and improve XINGO, as described in our{" "}
          <Link href="/privacy">Privacy Policy</Link>.
        </li>
        <li>
          XINGO&apos;s courses, scenarios, software, design and branding belong to us or our licensors. You may use them only to practise
          through the Service.
        </li>
        <li>
          Marketplace courses are created by independent creators, who are responsible for them. Courses aren&apos;t reviewed before
          publishing, but you can report any course and we&apos;ll review it. Creators&apos; obligations are in the{" "}
          <Link href="/creator-terms">Creator Terms</Link>.
        </li>
      </ul>
    ),
  },
  {
    id: "availability",
    heading: "Availability and changes",
    body: (
      <p>
        We work to keep XINGO available and accurate, but it relies on internet connections and third-party services (including AI
        providers), so it may sometimes be unavailable or make mistakes. We may change or stop features. If we stop the Service
        entirely, we&apos;ll give reasonable notice and refund unused pack minutes and any prepaid subscription period.
      </p>
    ),
  },
  {
    id: "liability",
    heading: "Liability",
    body: (
      <>
        <p>
          Subject to your rights under the Australian Consumer Law, we aren&apos;t liable for indirect or consequential loss, or for
          decisions you make based on AI practice content or scores, including decisions about exams, visas, registration or
          employment.
        </p>
        <p>
          Where our liability for failing to meet a consumer guarantee can be limited, it is limited (at our option) to supplying the
          services again or paying the cost of having them supplied again.
        </p>
      </>
    ),
  },
  {
    id: "ending",
    heading: "Ending your account",
    body: (
      <p>
        You can stop using XINGO at any time and ask us to delete your account by emailing {mail}. We may suspend or close an
        account that seriously or repeatedly breaks these terms; where reasonable we&apos;ll warn you first. If we close your account
        without you having broken these terms, we&apos;ll refund unused pack minutes.
      </p>
    ),
  },
  {
    id: "general",
    heading: "Changes and general terms",
    body: (
      <ul>
        <li>
          We may update these terms. For material changes we&apos;ll tell you in the app or by email, and ask you to accept them
          before you continue. If you don&apos;t agree, you can stop using XINGO and cancel any subscription.
        </li>
        <li>These terms are governed by the laws of Australia and the state or territory you live in.</li>
        <li>If part of these terms can&apos;t be enforced, the rest still applies.</li>
        <li>Contact us at {mail} with questions or complaints. We aim to respond within 5 business days.</li>
      </ul>
    ),
  },
];

export default function TermsPage() {
  return (
    <LegalDocument
      title="Terms of Service"
      current="/terms"
      sections={sections}
      summary={
        <>
          <p className="font-semibold">The short version</p>
          <ul className="mt-2 list-disc space-y-1 pl-5">
            <li>XINGO is practice with AI role-players. Scores are estimates, not official results, and we&apos;re not linked to any exam body.</li>
            <li>You pay for practice minutes through a plan or packs. Pack minutes never expire; you can cancel Pro any time.</li>
            <li>Your Australian Consumer Law rights always apply.</li>
            <li>Be respectful, don&apos;t misuse the AI, and only upload content you have the rights to.</li>
          </ul>
        </>
      }
    />
  );
}
