/**
 * Exam content pack (Oct 2026): practice modules for interpreting and
 * English-speaking exams. Research briefs: docs/research/exams-2026-10.md.
 *
 * All scenarios are original — nothing is copied from official sample papers.
 * Seed: `npx convex run content:seedExamPack '{"dryRun":true}'` (insert-only).
 */

type Difficulty = "beginner" | "intermediate" | "advanced";

type RoleplayInput = {
  id: string;
  moduleId: string;
  title: string;
  description: string;
  difficultyLevel: Difficulty;
  isFreePreview?: boolean;
  learnerRole: string;
  /** Candidate card, shown before and during the session. */
  taskCard: string;
  learnerOpens: boolean;
  timeLimitMinutes: number;
  briefing: string;
  assessmentFocus: string[];
  expectedSkills: string[];
  other: {
    name: string;
    role: string;
    voice: string;
    goal: string;
    demeanor: string;
    /** Interlocutor card: facts to reveal when asked, questions to ask, behaviour. */
    card: string;
    openingLine?: string;
    endCondition?: string;
  };
};

/** English-only role-play: the learner plays themselves, the AI plays the other person. */
function roleplay(input: RoleplayInput) {
  return {
    id: input.id,
    moduleId: input.moduleId,
    title: input.title,
    description: input.description,
    agentCount: 1 as const,
    difficultyLevel: input.difficultyLevel,
    isFreePreview: input.isFreePreview ?? false,
    expectedSkills: input.expectedSkills,
    aiAgentA: {
      name: input.other.name,
      role: input.other.role,
      voice: input.other.voice,
      goal: input.other.goal,
      language: "English",
      demeanor: input.other.demeanor,
      instructions: input.other.card,
      openingLine: input.other.openingLine,
      endCondition: input.other.endCondition,
    },
    practiceRuntime: {
      interpreterRole: input.learnerRole,
      sourceLanguage: "English",
      targetLanguage: "English",
      openingSpeaker: "agent_a" as const,
      briefing: input.briefing,
      assessmentFocus: input.assessmentFocus,
      practiceType: "roleplay" as const,
      learnerRole: input.learnerRole,
      taskCard: input.taskCard,
      learnerOpens: input.learnerOpens,
      timeLimitMinutes: input.timeLimitMinutes,
    },
  };
}

type InterpretingInput = {
  id: string;
  moduleId: string;
  title: string;
  description: string;
  difficultyLevel: Difficulty;
  isFreePreview?: boolean;
  interpreterRole: string;
  briefing: string;
  assessmentFocus: string[];
  expectedSkills: string[];
  timeLimitMinutes?: number;
  clinician: { name: string; role: string; voice: string; goal: string; demeanor: string; openingLine: string; endCondition: string; context: string };
  patient: { name: string; role: string; voice: string; goal: string; demeanor: string; openingLine: string; context: string };
};

/** Exam-style consecutive interpreting: short turns, both directions. */
function interpreting(input: InterpretingInput) {
  const shortTurns =
    "Keep every turn short — one to three sentences, under 35 words — like an oral exam segment. Include precise details (numbers, doses, dates, drug names).";

  return {
    id: input.id,
    moduleId: input.moduleId,
    title: input.title,
    description: input.description,
    agentCount: 2 as const,
    difficultyLevel: input.difficultyLevel,
    isFreePreview: input.isFreePreview ?? false,
    expectedSkills: input.expectedSkills,
    aiAgentA: {
      name: input.clinician.name,
      role: input.clinician.role,
      voice: input.clinician.voice,
      goal: input.clinician.goal,
      language: "English",
      demeanor: input.clinician.demeanor,
      openingLine: input.clinician.openingLine,
      endCondition: input.clinician.endCondition,
      instructions: `You are ${input.clinician.name}, ${input.clinician.role} in a US healthcare setting, speaking through a medical interpreter. ${input.clinician.context} ${shortTurns}`,
    },
    aiAgentB: {
      name: input.patient.name,
      role: input.patient.role,
      voice: input.patient.voice,
      goal: input.patient.goal,
      language: "Spanish",
      demeanor: input.patient.demeanor,
      openingLine: input.patient.openingLine,
      instructions: `You are ${input.patient.name}, the ${input.patient.role}. You don't speak English. ${input.patient.context} ${shortTurns} Occasionally use an everyday or colloquial expression. Never translate for anyone.`,
    },
    practiceRuntime: {
      interpreterRole: input.interpreterRole,
      sourceLanguage: "English",
      targetLanguage: "Spanish",
      openingSpeaker: "agent_a" as const,
      briefing: input.briefing,
      assessmentFocus: input.assessmentFocus,
      timeLimitMinutes: input.timeLimitMinutes,
    },
  };
}

const created = (n: number) => `2026-10-02T01:00:0${n}Z`;

export const examModules = [
  {
    id: "oet-speaking-nursing",
    title: "OET Speaking — Nursing",
    description:
      "Five-minute OET-style role-plays with a patient or relative. Work through the task card, explain in plain English and build rapport — scored on OET's clinical communication and language criteria.",
    industryCategory: "medical" as const,
    durationMinutes: 10,
    difficultyLevel: "intermediate" as const,
    learningObjectives: [
      "Open, structure and close a five-minute role-play using every task on the card",
      "Explain care in lay language and check understanding (teach-back)",
      "Respond to a patient's concerns, fears and reluctance without lecturing",
    ],
    isFree: false,
    isAccredited: false,
    badgeIcon: "OET",
    createdAt: created(0),
  },
  {
    id: "oet-speaking-medicine",
    title: "OET Speaking — Medicine",
    description:
      "OET-style doctor–patient role-plays: histories, explanations and negotiating plans with reluctant or worried patients, in five minutes.",
    industryCategory: "medical" as const,
    durationMinutes: 10,
    difficultyLevel: "intermediate" as const,
    learningObjectives: [
      "Gather a focused history with open-then-closed questions",
      "Explain diagnoses and plans without jargon",
      "Negotiate with patients who want something different",
    ],
    isFree: false,
    isAccredited: false,
    badgeIcon: "OET",
    createdAt: created(1),
  },
  {
    id: "ielts-speaking",
    title: "IELTS Speaking Mock Tests",
    description:
      "Full three-part IELTS Speaking practice with an AI examiner: interview, cue-card talk and discussion, timed like the real test, with an estimated band.",
    industryCategory: "community" as const,
    durationMinutes: 14,
    difficultyLevel: "intermediate" as const,
    learningObjectives: [
      "Give developed Part 1 answers with reasons and examples",
      "Speak for the full two minutes in Part 2, covering every prompt",
      "Discuss abstract ideas in Part 3 with a range of vocabulary and grammar",
    ],
    isFree: false,
    isAccredited: false,
    badgeIcon: "IELTS",
    createdAt: created(2),
  },
  {
    id: "amc-clinical-exam",
    title: "AMC Clinical Exam Stations",
    description:
      "Eight-minute AMC-style stations with a simulated patient or relative: focused histories, explaining diagnoses, counselling and breaking bad news.",
    industryCategory: "medical" as const,
    durationMinutes: 10,
    difficultyLevel: "advanced" as const,
    learningObjectives: [
      "Complete every task in the stem within eight minutes",
      "Take a focused history that catches the red flags",
      "Explain, counsel and safety-net using Australian practice",
    ],
    isFree: false,
    isAccredited: false,
    badgeIcon: "AMC",
    createdAt: created(3),
  },
  {
    id: "nmba-osce-nursing",
    title: "NMBA OSCE — Communication Stations",
    description:
      "Eight-minute OSCE-style stations for internationally qualified nurses: ISBAR calls, handover, patient education, consent and difficult conversations.",
    industryCategory: "medical" as const,
    durationMinutes: 10,
    difficultyLevel: "intermediate" as const,
    learningObjectives: [
      "Escalate a deteriorating patient with a clear ISBAR and a specific request",
      "Educate patients using teach-back",
      "De-escalate anxious or angry relatives while keeping the patient safe",
    ],
    isFree: false,
    isAccredited: false,
    badgeIcon: "OSCE",
    createdAt: created(4),
  },
  {
    id: "us-medical-interpreter-oral",
    title: "Medical Interpreter Oral Exam (CMI & CHI)",
    description:
      "Short, fast, exam-style consecutive role-plays across US clinical specialties — the format of the NBCMI CMI and CCHI CHI oral exams.",
    industryCategory: "medical" as const,
    durationMinutes: 15,
    difficultyLevel: "advanced" as const,
    learningObjectives: [
      "Render short turns completely in both directions, in the first person",
      "Carry doses, numbers and drug names exactly",
      "Keep register without adding, omitting or summarising",
    ],
    isFree: false,
    isAccredited: false,
    badgeIcon: "CMI",
    createdAt: created(5),
  },
] as const;

// ---- OET Nursing ----------------------------------------------------------------
const oetNursing = [
  roleplay({
    id: "oet-nursing-hip-mobilisation",
    moduleId: "oet-speaking-nursing",
    title: "Post-op Mobilisation",
    description: "A patient the day after a hip replacement refuses to get out of bed.",
    difficultyLevel: "intermediate",
    isFreePreview: true,
    learnerRole: "Registered nurse on an orthopaedic ward",
    learnerOpens: true,
    timeLimitMinutes: 5,
    taskCard: [
      "Setting: Orthopaedic ward",
      "Patient: Mrs Joan Lee, 68, day 1 after a right total hip replacement. Physio wants her sitting out of bed this morning. She has refused.",
      "",
      "Task:",
      "• Find out why she doesn't want to get up",
      "• Explain why moving early matters (blood clots, chest infection, recovery)",
      "• Explain how her pain will be managed before she moves",
      "• Reassure her about the support she'll have (two staff, frame)",
    ].join("\n"),
    briefing: "OET Nursing role-play. Five minutes. You lead the conversation and cover every task.",
    assessmentFocus: ["Exploring the patient's concerns", "Lay explanations", "Structure across all four tasks"],
    expectedSkills: ["Relationship building", "Information-giving", "Providing structure"],
    other: {
      name: "Joan Lee",
      role: "a 68-year-old patient the day after hip replacement surgery",
      voice: "sage",
      goal: "Avoid getting up today because of pain and fear of falling, unless properly reassured.",
      demeanor: "Polite but frightened; gradually more willing if the nurse listens",
      card: [
        "You had your hip replaced yesterday. Your pain is 6/10 and you're scared the new hip will dislocate or you'll fall.",
        "Your neighbour fell after surgery and 'was never the same'. Only mention this if asked why you're worried.",
        "Ask: 'Can't I just rest today and start tomorrow?' and 'What if it pops out?'",
        "If the nurse explains pain relief first and that two people will help, agree to try sitting out for a short time.",
      ].join("\n"),
    },
  }),
  roleplay({
    id: "oet-nursing-new-diabetes",
    moduleId: "oet-speaking-nursing",
    title: "Newly Diagnosed Diabetes",
    description: "A man with new type 2 diabetes feels overwhelmed at a community clinic.",
    difficultyLevel: "intermediate",
    learnerRole: "Practice nurse in a community health clinic",
    learnerOpens: true,
    timeLimitMinutes: 5,
    taskCard: [
      "Setting: Community health clinic",
      "Patient: Mr Raj Patel, 55, diagnosed with type 2 diabetes last week. Started metformin. Here for his first education session.",
      "",
      "Task:",
      "• Find out what he already knows about diabetes",
      "• Explain how and when to check his blood glucose",
      "• Give two or three simple food tips",
      "• Arrange follow-up and tell him who to contact with questions",
    ].join("\n"),
    briefing: "OET Nursing role-play. Avoid information overload — check what he knows first.",
    assessmentFocus: ["Checking prior knowledge", "Chunking information", "Teach-back"],
    expectedSkills: ["Information-giving", "Patient perspective", "Lay language"],
    other: {
      name: "Raj Patel",
      role: "a 55-year-old man newly diagnosed with type 2 diabetes",
      voice: "cedar",
      goal: "Understand what he needs to do without feeling lectured.",
      demeanor: "Overwhelmed, a bit defensive about his diet",
      card: [
        "You think diabetes means you can never eat rice or sweets again. You drive a taxi and eat irregularly.",
        "You've never used a glucose meter and are worried about the needle.",
        "Ask: 'Will I have to inject insulin?' and 'Can I still eat rice?'",
        "If the nurse talks for a long time without checking in, say 'Sorry, that's a lot.'",
      ].join("\n"),
    },
  }),
  roleplay({
    id: "oet-nursing-gastro-child",
    moduleId: "oet-speaking-nursing",
    title: "Child with Gastroenteritis",
    description: "An anxious father of a four-year-old with vomiting and diarrhoea.",
    difficultyLevel: "beginner",
    learnerRole: "Registered nurse on a paediatric ward",
    learnerOpens: true,
    timeLimitMinutes: 5,
    taskCard: [
      "Setting: Paediatric ward",
      "Patient: Leo, 4, admitted with gastroenteritis. You are speaking to his father.",
      "",
      "Task:",
      "• Ask about Leo's fluid intake and wet nappies/toilet visits today",
      "• Explain the signs of dehydration to watch for",
      "• Explain the oral rehydration plan (small sips often)",
      "• Tell the father when to call a nurse",
    ].join("\n"),
    briefing: "OET Nursing role-play with a parent. Reassure without dismissing his worry.",
    assessmentFocus: ["Gathering information", "Clear instructions", "Reassurance"],
    expectedSkills: ["Information-gathering", "Information-giving", "Relationship building"],
    other: {
      name: "Daniel Murphy",
      role: "the father of a four-year-old with gastroenteritis",
      voice: "ash",
      goal: "Get his son better quickly; wants a drip because he thinks it's faster.",
      demeanor: "Anxious, talks fast, interrupts once",
      card: [
        "Leo vomited twice this morning, kept down half a cup of juice, and has had one wee since breakfast.",
        "Ask: 'Why can't he just have a drip?' Accept the plan if the nurse explains why sips are better.",
        "You're worried because Leo is 'floppy' — only say this if asked how he seems.",
      ].join("\n"),
    },
  }),
  roleplay({
    id: "oet-nursing-warfarin-discharge",
    moduleId: "oet-speaking-nursing",
    title: "Warfarin Discharge",
    description: "An older woman starting warfarin doubts she needs it.",
    difficultyLevel: "intermediate",
    learnerRole: "Registered nurse preparing a patient for discharge",
    learnerOpens: true,
    timeLimitMinutes: 5,
    taskCard: [
      "Setting: Medical ward, discharge",
      "Patient: Ms Margaret Brown, 72, new atrial fibrillation, starting warfarin.",
      "",
      "Task:",
      "• Find out how she feels about the new medicine",
      "• Explain why she needs warfarin (stroke prevention) in simple terms",
      "• Explain bleeding signs to report",
      "• Explain INR blood tests and that some foods and medicines interact",
    ].join("\n"),
    briefing: "OET Nursing role-play. Negotiate, don't argue.",
    assessmentFocus: ["Handling reluctance", "Safety information", "Plain language"],
    expectedSkills: ["Patient perspective", "Information-giving", "Negotiation"],
    other: {
      name: "Margaret Brown",
      role: "a 72-year-old woman starting warfarin",
      voice: "shimmer",
      goal: "Avoid a medicine she thinks is 'rat poison'.",
      demeanor: "Sceptical, sharp, softens if treated with respect",
      card: [
        "Your friend told you warfarin is rat poison. You feel fine and don't see the point.",
        "You take fish oil and turmeric every day — mention only if asked about other medicines.",
        "Ask: 'How often do I need blood tests?'",
      ].join("\n"),
    },
  }),
  roleplay({
    id: "oet-nursing-angry-daughter-ed",
    moduleId: "oet-speaking-nursing",
    title: "Angry Relative in ED",
    description: "The daughter of a confused 80-year-old is angry about the wait.",
    difficultyLevel: "advanced",
    learnerRole: "Registered nurse in the emergency department",
    learnerOpens: true,
    timeLimitMinutes: 5,
    taskCard: [
      "Setting: Emergency department",
      "Patient: Mr Frank Rossi, 80, brought in confused. His daughter has been waiting three hours.",
      "",
      "Task:",
      "• Acknowledge her frustration",
      "• Find out how her father's confusion started and how he normally is",
      "• Explain how triage works and what happens next",
      "• Agree when you will update her",
    ].join("\n"),
    briefing: "OET Nursing role-play with a frustrated relative.",
    assessmentFocus: ["De-escalation", "Gathering collateral history", "Clear next steps"],
    expectedSkills: ["Relationship building", "Information-gathering", "Providing structure"],
    other: {
      name: "Sofia Rossi",
      role: "the daughter of an 80-year-old man waiting in ED",
      voice: "coral",
      goal: "Get her father seen now and be kept informed.",
      demeanor: "Angry at first; calms if genuinely acknowledged",
      card: [
        "Open angrily: 'We've been here three hours and nobody has told us anything!'",
        "Your father was normal two days ago, lives alone, and has been drinking very little. He started burning with urine yesterday — only mention if asked about other symptoms.",
        "If the nurse just says 'I understand', say 'No, you don't.'",
      ].join("\n"),
      openingLine: "We've been here three hours and nobody has told us anything!",
    },
  }),
  roleplay({
    id: "oet-nursing-smoking-pregnancy",
    moduleId: "oet-speaking-nursing",
    title: "Smoking in Pregnancy",
    description: "A reluctant smoker who is twelve weeks pregnant.",
    difficultyLevel: "intermediate",
    learnerRole: "Antenatal clinic nurse",
    learnerOpens: true,
    timeLimitMinutes: 5,
    taskCard: [
      "Setting: Antenatal clinic",
      "Patient: Ms Chloe Martin, 34, 12 weeks pregnant, smokes about ten cigarettes a day.",
      "",
      "Task:",
      "• Ask about her smoking and previous attempts to quit",
      "• Explain the risks to the baby without judgement",
      "• Discuss options (Quitline, nicotine replacement after checking with the doctor)",
      "• Agree a realistic goal",
    ].join("\n"),
    briefing: "OET Nursing role-play. Motivate without lecturing.",
    assessmentFocus: ["Non-judgemental language", "Shared goal-setting", "Risk explanation"],
    expectedSkills: ["Patient perspective", "Relationship building", "Information-giving"],
    other: {
      name: "Chloe Martin",
      role: "a 34-year-old woman who is 12 weeks pregnant and smokes",
      voice: "marin",
      goal: "Avoid being judged; open to cutting down if treated kindly.",
      demeanor: "Defensive, then honest",
      card: [
        "Your mum smoked through all her pregnancies 'and we were fine'. Say this if the nurse lists risks too bluntly.",
        "You tried quitting last year but got very stressed at work.",
        "Ask: 'Is it safe to use patches when pregnant?'",
      ].join("\n"),
    },
  }),
];

// ---- OET Medicine -----------------------------------------------------------------
const oetMedicine = [
  roleplay({
    id: "oet-medicine-headache-scan",
    moduleId: "oet-speaking-medicine",
    title: "Headaches — Wants a Scan",
    description: "An office worker with recurring headaches demands a brain scan.",
    difficultyLevel: "intermediate",
    isFreePreview: true,
    learnerRole: "General practitioner",
    learnerOpens: true,
    timeLimitMinutes: 5,
    taskCard: [
      "Setting: General practice",
      "Patient: Ms Aisha Khan, 45, office manager, headaches for two months.",
      "",
      "Task:",
      "• Take a focused history including red-flag questions",
      "• Explain that this sounds like tension-type headache",
      "• Explain why a scan isn't needed now",
      "• Agree a management plan and when to come back",
    ].join("\n"),
    briefing: "OET Medicine role-play. Address her fear of a tumour directly.",
    assessmentFocus: ["Red-flag questioning", "Explaining without jargon", "Negotiating the plan"],
    expectedSkills: ["Information-gathering", "Patient perspective", "Information-giving"],
    other: {
      name: "Aisha Khan",
      role: "a 45-year-old office manager with recurring headaches",
      voice: "coral",
      goal: "Get a brain scan to rule out a tumour.",
      demeanor: "Worried, insistent",
      card: [
        "Headaches are band-like, worse late in the day, no vomiting, no weakness, no vision change. Long hours at a screen, poor sleep, lots of coffee.",
        "A colleague's sister had a brain tumour — mention only if asked why you want a scan.",
        "Ask: 'Can't you just send me for a scan to be safe?'",
      ].join("\n"),
    },
  }),
  roleplay({
    id: "oet-medicine-hypertension",
    moduleId: "oet-speaking-medicine",
    title: "New Hypertension",
    description: "A man with new high blood pressure doesn't want tablets.",
    difficultyLevel: "intermediate",
    learnerRole: "General practitioner",
    learnerOpens: true,
    timeLimitMinutes: 5,
    taskCard: [
      "Setting: General practice, follow-up",
      "Patient: Mr George Wilson, 60. Three readings average 158/96.",
      "",
      "Task:",
      "• Explore his concerns about medication",
      "• Explain the risks of untreated high blood pressure",
      "• Discuss lifestyle changes and a medication option",
      "• Arrange monitoring",
    ].join("\n"),
    briefing: "OET Medicine role-play. Shared decision-making.",
    assessmentFocus: ["Exploring beliefs", "Risk explanation", "Shared plan"],
    expectedSkills: ["Patient perspective", "Information-giving", "Negotiation"],
    other: {
      name: "George Wilson",
      role: "a 60-year-old man with newly diagnosed high blood pressure",
      voice: "cedar",
      goal: "Try lifestyle changes before tablets.",
      demeanor: "Friendly but stubborn",
      card: [
        "You feel perfectly well. Your brother got dizzy and impotent on blood pressure tablets — mention when asked about concerns.",
        "You drink about four beers most nights and walk the dog twice a week.",
      ].join("\n"),
    },
  }),
  roleplay({
    id: "oet-medicine-pneumonia-son",
    moduleId: "oet-speaking-medicine",
    title: "Worsening Pneumonia",
    description: "The son of an elderly patient whose pneumonia is getting worse.",
    difficultyLevel: "advanced",
    learnerRole: "Hospital doctor (medical registrar)",
    learnerOpens: true,
    timeLimitMinutes: 5,
    taskCard: [
      "Setting: Medical ward",
      "Patient: Mrs Elena Novak, 78, admitted two days ago with pneumonia. Oxygen needs have increased overnight. You are speaking to her son.",
      "",
      "Task:",
      "• Find out what he already understands",
      "• Explain what has changed and the plan (IV antibiotics, more oxygen)",
      "• Respond to his distress",
      "• Discuss what happens if she doesn't improve",
    ].join("\n"),
    briefing: "OET Medicine role-play. Sensitive update to a relative.",
    assessmentFocus: ["Checking understanding first", "Responding to emotion", "Honest, clear explanation"],
    expectedSkills: ["Relationship building", "Information-giving", "Providing structure"],
    other: {
      name: "Peter Novak",
      role: "the son of a 78-year-old woman with pneumonia",
      voice: "ash",
      goal: "Understand whether his mother will be okay.",
      demeanor: "Upset, quiet, then asks direct questions",
      card: [
        "You thought she was getting better yesterday. You live interstate and fly home tomorrow.",
        "Ask: 'Is she going to die?' and 'Should I cancel my flight?'",
      ].join("\n"),
    },
  }),
  roleplay({
    id: "oet-medicine-ankle-xray",
    moduleId: "oet-speaking-medicine",
    title: "Ankle Sprain — Wants an X-ray",
    description: "A young man with an ankle sprain demands an X-ray and strong painkillers.",
    difficultyLevel: "beginner",
    learnerRole: "Emergency department doctor",
    learnerOpens: true,
    timeLimitMinutes: 5,
    taskCard: [
      "Setting: Emergency department",
      "Patient: Mr Josh Taylor, 25, twisted his ankle at football. Can walk four steps; no bone tenderness on examination.",
      "",
      "Task:",
      "• Confirm how the injury happened",
      "• Explain why an X-ray isn't needed (in lay terms)",
      "• Explain RICE and simple pain relief",
      "• Explain when he should come back",
    ].join("\n"),
    briefing: "OET Medicine role-play. Decline the request while keeping rapport.",
    assessmentFocus: ["Explaining a 'no'", "Lay terms", "Safety-netting"],
    expectedSkills: ["Information-giving", "Relationship building", "Negotiation"],
    other: {
      name: "Josh Taylor",
      role: "a 25-year-old man with a sprained ankle",
      voice: "verse",
      goal: "Get an X-ray and something strong for the pain; has a work shift tomorrow.",
      demeanor: "Impatient, a little rude at first",
      card: ["Ask: 'How do you know it's not broken without an X-ray?' and 'Can I get some Endone?'", "You're a delivery driver and worried about work."].join("\n"),
    },
  }),
];

// ---- IELTS Speaking -----------------------------------------------------------------
type IeltsTest = { id: string; title: string; part1Topic: string; part1: string[]; cueCard: string; part3: string[]; free?: boolean };

const ieltsTests: IeltsTest[] = [
  {
    id: "ielts-mock-neighbourhood",
    title: "Mock Test 1 — Neighbourhoods & Public Places",
    part1Topic: "your neighbourhood",
    part1: ["What's your neighbourhood like?", "Has it changed in recent years?", "Would you like to move somewhere else?"],
    cueCard: "Describe a public place you enjoy visiting. You should say: where it is, how often you go there, what you do there, and explain why you like it.",
    part3: ["Should governments spend more on parks or on roads?", "How do public spaces affect a community?", "Will cities become more crowded in the future?"],
    free: true,
  },
  {
    id: "ielts-mock-learning",
    title: "Mock Test 2 — Routines & Learning",
    part1Topic: "mornings",
    part1: ["Are you a morning person?", "What do you usually have for breakfast?", "Has your morning routine changed since you were at school?"],
    cueCard: "Describe a skill you learned as an adult. You should say: what the skill was, how you learned it, how long it took, and explain how you feel about it now.",
    part3: ["Is it harder to learn new things as we get older?", "Should employers pay for staff training?", "How has online learning changed education?"],
  },
  {
    id: "ielts-mock-kindness",
    title: "Mock Test 3 — Weather & Helping Others",
    part1Topic: "the weather",
    part1: ["What kind of weather do you like?", "Does the weather affect your mood?", "What do you usually do on rainy days?"],
    cueCard: "Describe a time you helped a stranger. You should say: when and where it happened, what the situation was, what you did, and explain how you felt afterwards.",
    part3: ["Are people less helpful in big cities?", "Should kindness be taught in schools?", "Has technology made people less connected to their neighbours?"],
  },
  {
    id: "ielts-mock-celebrations",
    title: "Mock Test 4 — Food & Celebrations",
    part1Topic: "food shopping",
    part1: ["Where do you usually buy groceries?", "How often do you cook at home?", "Has online shopping changed the way you buy food?"],
    cueCard: "Describe a family celebration you remember well. You should say: what the celebration was, who was there, what you did, and explain why it stood out for you.",
    part3: ["How are traditional celebrations changing?", "Do people spend too much money on celebrations?", "Should governments help protect cultural events?"],
  },
  {
    id: "ielts-mock-decisions",
    title: "Mock Test 5 — Technology & Big Decisions",
    part1Topic: "mobile phones",
    part1: ["How much do you use your phone each day?", "Which app do you use most?", "Could you go a whole day without your phone?"],
    cueCard: "Describe an important decision you made. You should say: what the decision was, when you made it, who influenced you, and explain what the result was.",
    part3: ["Do young people today have too many choices?", "Should parents choose their children's careers?", "How do people make big decisions differently today compared with the past?"],
  },
  {
    id: "ielts-mock-work",
    title: "Mock Test 6 — Transport & Work",
    part1Topic: "getting around",
    part1: ["How do you usually get to work or study?", "Do you like using public transport?", "Would you cycle more if it were safer?"],
    cueCard: "Describe a job you would like to try for a week. You should say: what the job is, what it involves, why it appeals to you, and explain what you would find difficult about it.",
    part3: ["Which jobs deserve higher pay?", "Will automation remove jobs or create new ones?", "Is job satisfaction more important than salary?"],
  },
];

const ielts = ieltsTests.map((test) =>
  roleplay({
    id: test.id,
    moduleId: "ielts-speaking",
    title: test.title,
    description: `Three-part IELTS Speaking practice. Part 1: ${test.part1Topic}. Part 2 cue card and Part 3 discussion.`,
    difficultyLevel: "intermediate",
    isFreePreview: test.free,
    learnerRole: "IELTS Speaking candidate",
    learnerOpens: false,
    timeLimitMinutes: 14,
    taskCard: [
      "The examiner will lead you through three parts:",
      "Part 1 (4–5 min): questions about you and familiar topics.",
      "Part 2 (3–4 min): you'll be given a topic. You have 1 minute to think, then speak for 1–2 minutes.",
      "Part 3 (4–5 min): a discussion of wider issues linked to your Part 2 topic.",
      "",
      `Your Part 2 topic: ${test.cueCard}`,
      "",
      "Tip: extend your answers with reasons and examples. The examiner won't give feedback during the test.",
    ].join("\n"),
    briefing: "IELTS Speaking mock test, 11–14 minutes. Answer fully; you'll get an estimated band afterwards.",
    assessmentFocus: ["Fluency & coherence", "Lexical resource", "Grammatical range & accuracy", "Developing answers"],
    expectedSkills: ["Extended speaking", "Paraphrasing", "Complex sentences"],
    other: {
      name: "The examiner",
      role: "a certified IELTS Speaking examiner",
      voice: "marin",
      goal: "Run a standard three-part IELTS Speaking test fairly and on time.",
      demeanor: "Neutral, polite, professional; never gives feedback or opinions",
      openingLine: "Good morning. My name is Sarah and I'll be your examiner today. Can you tell me your full name, please?",
      endCondition: "you have finished Part 3 (or about 13 minutes have passed)",
      card: [
        "Follow the IELTS Speaking structure exactly and keep your own turns brief and scripted-sounding.",
        `Part 1: after the name, ask 'Do you work or are you a student?' and one follow-up. Then say 'Now let's talk about ${test.part1Topic}.' and ask these one at a time: ${test.part1.join(" | ")}`,
        `Part 2: say 'Now I'm going to give you a topic and I'd like you to talk about it for one to two minutes. You have one minute to think about what you're going to say. Your topic is: ${test.cueCard}' Then say 'Your one minute starts now' and stay silent until the candidate starts speaking. Let them talk for up to two minutes without interrupting; if they stop early, ask one short rounding-off question.`,
        `Part 3: say 'We've been talking about this topic. Now I'd like to discuss some more general questions.' Then ask, one at a time, adding a short follow-up such as 'Why do you think that is?': ${test.part3.join(" | ")}`,
        "Close with: 'Thank you. That is the end of the speaking test.'",
        "Never correct the candidate, praise them, or comment on their English.",
      ].join("\n"),
    },
  }),
);

// ---- AMC Clinical ----------------------------------------------------------------------
const amc = [
  roleplay({
    id: "amc-fatigue-history",
    moduleId: "amc-clinical-exam",
    title: "Fatigue in a 58-Year-Old",
    description: "Focused history and differentials for three weeks of tiredness.",
    difficultyLevel: "advanced",
    isFreePreview: true,
    learnerRole: "Doctor (AMC candidate) in general practice",
    learnerOpens: true,
    timeLimitMinutes: 8,
    taskCard: [
      "Setting: General practice",
      "Mr Graham Hughes, 58, presents with three weeks of tiredness.",
      "",
      "Your tasks:",
      "1. Take a focused history (no more than 5 minutes).",
      "2. Explain your most likely diagnoses to the patient.",
      "3. Outline the investigations you would arrange.",
      "",
      "Examination findings are not required for this station.",
    ].join("\n"),
    briefing: "AMC-style history station. Eight minutes. Complete all three tasks.",
    assessmentFocus: ["Red flags (weight loss, bowel change, melaena)", "Organised history", "Clear explanation of next steps"],
    expectedSkills: ["Focused history", "Diagnostic reasoning", "Explanation"],
    other: {
      name: "Graham Hughes",
      role: "a 58-year-old man with three weeks of tiredness",
      voice: "cedar",
      goal: "Find out why he's so tired; secretly worried about cancer.",
      demeanor: "Tired, cooperative, anxious underneath",
      openingLine: "I've just been so tired the last few weeks, doc. I can barely get through work.",
      endCondition: "the doctor has explained the likely causes and the tests",
      card: [
        "Reveal only when asked directly: you've lost about 5 kg without trying; your bowels have been looser for two months; stools have been very dark a few times; you've never done the bowel screening kit; your father had 'bowel trouble'.",
        "No chest pain, no fevers, appetite a bit down. You take nothing regularly. Non-smoker, two beers a night.",
        "If the doctor uses jargon (e.g. 'melaena', 'colonoscopy'), ask what that means.",
        "Ask near the end: 'Is it cancer, doctor?'",
      ].join("\n"),
    },
  }),
  roleplay({
    id: "amc-febrile-toddler-rash",
    moduleId: "amc-clinical-exam",
    title: "Toddler with Fever and Rash",
    description: "Third-party history from a frantic mother in ED; explain urgent management.",
    difficultyLevel: "advanced",
    learnerRole: "Emergency department doctor (AMC candidate)",
    learnerOpens: true,
    timeLimitMinutes: 8,
    taskCard: [
      "Setting: Emergency department",
      "Lily, 18 months, is brought in by her mother with fever since last night and a new rash.",
      "",
      "Your tasks:",
      "1. Take a focused history from the mother.",
      "2. Explain your main concern and what will happen next.",
      "3. Answer her questions.",
    ].join("\n"),
    briefing: "AMC-style paediatric station with a third-party history. Time-critical.",
    assessmentFocus: ["Meningococcal red flags", "Urgency communicated calmly", "Immunisation history"],
    expectedSkills: ["Third-party history", "Breaking urgent news", "Calm communication"],
    other: {
      name: "Mia Thompson",
      role: "the mother of an 18-month-old with fever and rash",
      voice: "shimmer",
      goal: "Get help for her daughter and understand what's happening.",
      demeanor: "Frantic, interrupts, calms slightly if the doctor is clear and kind",
      openingLine: "She's burning up and there's this rash — please, can someone look at her?",
      endCondition: "the doctor has explained the urgent plan and answered your questions",
      card: [
        "Reveal when asked: the rash is purple spots that don't fade when you pressed a glass on them; Lily has been very sleepy since this morning; fewer wet nappies; she's not immunised ('we were going to catch up').",
        "Ask: 'Is it meningitis?' and 'Did I do something wrong?'",
      ].join("\n"),
    },
  }),
  roleplay({
    id: "amc-valproate-pregnancy",
    moduleId: "amc-clinical-exam",
    title: "Pregnant on Valproate",
    description: "Counsel a woman with epilepsy who has a positive pregnancy test.",
    difficultyLevel: "advanced",
    learnerRole: "General practitioner (AMC candidate)",
    learnerOpens: true,
    timeLimitMinutes: 8,
    taskCard: [
      "Setting: General practice",
      "Ms Hannah Clarke, 34, has epilepsy controlled on sodium valproate. Her home pregnancy test is positive (about 6 weeks).",
      "",
      "Your tasks:",
      "1. Explore her situation and concerns.",
      "2. Counsel her about the medication and the pregnancy.",
      "3. Explain the next steps.",
    ].join("\n"),
    briefing: "AMC-style counselling station. Safety first, without blame.",
    assessmentFocus: ["Do not stop medication abruptly", "Urgent specialist review", "High-dose folic acid", "Non-judgemental counselling"],
    expectedSkills: ["Counselling", "Risk communication", "Management planning"],
    other: {
      name: "Hannah Clarke",
      role: "a 34-year-old woman with epilepsy and a positive pregnancy test",
      voice: "coral",
      goal: "Protect her baby; she's thinking of stopping her tablets today.",
      demeanor: "Shocked, tearful, guilty",
      openingLine: "I did a test this morning and it's positive. We weren't planning it yet.",
      endCondition: "the doctor has explained the plan and next steps",
      card: [
        "Reveal when asked: last seizure two years ago; she drives to work; not taking folic acid; partner is supportive.",
        "Ask: 'Should I just stop my tablets now?' and 'Have I already hurt the baby?'",
      ].join("\n"),
    },
  }),
  roleplay({
    id: "amc-delirium-daughter",
    moduleId: "amc-clinical-exam",
    title: "Post-op Delirium",
    description: "Explain new confusion after hip surgery to an angry daughter.",
    difficultyLevel: "intermediate",
    learnerRole: "Hospital doctor (AMC candidate)",
    learnerOpens: true,
    timeLimitMinutes: 8,
    taskCard: [
      "Setting: Orthopaedic ward",
      "Mr Alan Price, 79, is day 2 after hip fracture surgery and has become confused overnight. His daughter has asked to speak to a doctor.",
      "",
      "Your tasks:",
      "1. Explain what delirium is and its likely causes here.",
      "2. Explain how it will be managed.",
      "3. Address her concerns.",
    ].join("\n"),
    briefing: "AMC-style explanation station with an upset relative.",
    assessmentFocus: ["Explaining delirium vs dementia", "Causes (pain, opioids, retention, infection)", "Family involvement"],
    expectedSkills: ["Explanation", "Empathy", "Management planning"],
    other: {
      name: "Karen Price",
      role: "the daughter of a 79-year-old man with post-operative confusion",
      voice: "marin",
      goal: "Understand what's happened to her father and whether it's permanent.",
      demeanor: "Angry, then frightened",
      openingLine: "He was completely fine before the operation. What have you done to him?",
      endCondition: "the doctor has explained delirium and the plan",
      card: ["Ask: 'Is this dementia now?' and 'Can I stay with him overnight?'", "Mention only if asked: he's been on strong painkillers and hasn't passed much urine today."].join("\n"),
    },
  }),
  roleplay({
    id: "amc-breaking-bad-news",
    moduleId: "amc-clinical-exam",
    title: "Breaking Bad News",
    description: "Tell a patient his CT shows a likely pancreatic mass.",
    difficultyLevel: "advanced",
    learnerRole: "General practitioner (AMC candidate)",
    learnerOpens: true,
    timeLimitMinutes: 8,
    taskCard: [
      "Setting: General practice",
      "Mr David Brooks, 45, had a CT scan for upper abdominal pain and weight loss. The report shows a mass in the pancreas suspicious of cancer. He has come for his results alone.",
      "",
      "Your tasks:",
      "1. Explain the result.",
      "2. Respond to his reaction and questions.",
      "3. Explain the next steps.",
    ].join("\n"),
    briefing: "AMC-style breaking bad news station. Use a structured approach.",
    assessmentFocus: ["Warning shot and checking understanding", "Silence and empathy", "No false precision", "Clear next steps and support"],
    expectedSkills: ["Breaking bad news", "Empathy", "Planning"],
    other: {
      name: "David Brooks",
      role: "a 45-year-old man receiving CT results",
      voice: "ash",
      goal: "Find out what the scan showed.",
      demeanor: "Quiet, goes silent after the news, then direct",
      openingLine: "So, what did the scan show?",
      endCondition: "the doctor has explained next steps and support",
      card: [
        "You have two children aged 8 and 11. Mention only if the doctor asks about support or what matters to you.",
        "After the news, say nothing for a few seconds. Then ask: 'How long have I got?' and 'Should I tell my kids?'",
      ].join("\n"),
    },
  }),
  roleplay({
    id: "amc-low-mood-risk",
    moduleId: "amc-clinical-exam",
    title: "Low Mood — Risk Assessment",
    description: "Risk-focused mental health history and safety plan.",
    difficultyLevel: "advanced",
    learnerRole: "General practitioner (AMC candidate)",
    learnerOpens: true,
    timeLimitMinutes: 8,
    taskCard: [
      "Setting: General practice",
      "Ms Ella Morgan, 26, says she has been feeling 'flat' for two months.",
      "",
      "Your tasks:",
      "1. Take a focused mental health history including a risk assessment.",
      "2. Explain your assessment.",
      "3. Agree a safety plan and follow-up.",
    ].join("\n"),
    briefing: "AMC-style mental health station. Ask about suicide directly and compassionately.",
    assessmentFocus: ["Direct suicide risk questions", "Means restriction", "Crisis contacts", "Follow-up within days"],
    expectedSkills: ["Risk assessment", "Empathy", "Safety planning"],
    other: {
      name: "Ella Morgan",
      role: "a 26-year-old woman with two months of low mood",
      voice: "sage",
      goal: "Feel understood; unsure whether she wants help.",
      demeanor: "Flat, short answers, opens up if the doctor is warm",
      openingLine: "I've just been feeling flat. My housemate made me come.",
      endCondition: "a safety plan and follow-up have been agreed",
      card: [
        "Reveal only if asked directly: you sometimes think everyone would be better off without you; you have a large stash of paracetamol in your drawer; you've been drinking most nights; no previous attempts.",
        "You broke up with your partner three months ago and lost your job last month.",
        "If asked about safety plans, agree to remove the tablets and to a review in two days.",
      ].join("\n"),
    },
  }),
];

// ---- NMBA OSCE -----------------------------------------------------------------------
const osce = [
  roleplay({
    id: "osce-isbar-deteriorating",
    moduleId: "nmba-osce-nursing",
    title: "ISBAR Call — Deteriorating Patient",
    description: "Phone the after-hours doctor about a confused, hypoxic patient after hip surgery.",
    difficultyLevel: "intermediate",
    isFreePreview: true,
    learnerRole: "Registered nurse on an orthopaedic ward (night shift)",
    learnerOpens: true,
    timeLimitMinutes: 8,
    taskCard: [
      "Setting: Orthopaedic ward, 2 am. Telephone call.",
      "Patient: Mrs Betty Walsh, 74, day 2 after right hip replacement. Newly confused.",
      "Observations: RR 26, SpO2 89% on room air, HR 118, BP 98/60, temp 38.1°C.",
      "",
      "Your task:",
      "• Call the after-hours doctor and escalate using ISBAR",
      "• Make a clear, specific request",
      "• Read back any orders",
      "• State what you'll do while waiting",
    ].join("\n"),
    briefing: "OSCE-style escalation station. Clear, concise ISBAR with a specific request.",
    assessmentFocus: ["Complete ISBAR", "Specific request with timeframe", "Read-back of orders", "Interim actions"],
    expectedSkills: ["Escalation", "ISBAR", "Clinical communication"],
    other: {
      name: "Dr Tom Reid",
      role: "the after-hours resident doctor, answering the phone",
      voice: "ash",
      goal: "Deal with the call quickly; you're busy with another patient.",
      demeanor: "Rushed, slightly impatient",
      openingLine: "Hi, Tom here, after-hours. What's up?",
      endCondition: "the nurse has made a clear request and read back your orders",
      card: [
        "You're in the middle of another review. If the nurse is vague, ask: 'So what do you want me to do?'",
        "If the ISBAR is clear, give orders: oxygen to keep sats above 94%, blood cultures and a full blood count, and you'll review within 30 minutes. Ask the nurse to call back if BP drops below 90.",
        "Expect the nurse to read your orders back; if they don't, ask 'Did you get all that?'",
      ].join("\n"),
    },
  }),
  roleplay({
    id: "osce-apixaban-education",
    moduleId: "nmba-osce-nursing",
    title: "New Anticoagulant Education",
    description: "Educate an anxious patient starting apixaban for atrial fibrillation.",
    difficultyLevel: "beginner",
    learnerRole: "Registered nurse in a general practice clinic",
    learnerOpens: true,
    timeLimitMinutes: 8,
    taskCard: [
      "Setting: General practice",
      "Patient: Mr Ken Davies, 66, newly diagnosed atrial fibrillation, started on apixaban 5 mg twice daily.",
      "",
      "Your task:",
      "• Identify the patient and gain consent for the education",
      "• Explain the purpose of the medicine and how to take it",
      "• Explain bleeding signs and when to seek help",
      "• Advise about other medicines and supplements",
      "• Check understanding (teach-back)",
    ].join("\n"),
    briefing: "OSCE-style medication education station.",
    assessmentFocus: ["Patient identification", "Bleeding signs and 000", "Avoiding NSAIDs/supplements", "Teach-back"],
    expectedSkills: ["Medication education", "Teach-back", "Safety"],
    other: {
      name: "Ken Davies",
      role: "a 66-year-old man starting apixaban",
      voice: "cedar",
      goal: "Understand the new tablet; worried about bleeding.",
      demeanor: "Anxious, asks practical questions",
      card: [
        "Give your full name and date of birth (12 March 1960) if asked to confirm identity.",
        "You take fish oil and ibuprofen for your back — mention only if asked about other medicines.",
        "Ask: 'What if I forget a dose?' and 'Can I still go to the dentist?'",
        "If the nurse asks you to repeat back what you'll do, give a partly correct answer (forget the bleeding signs) so they have to clarify.",
      ].join("\n"),
    },
  }),
  roleplay({
    id: "osce-falls-daughter-aged-care",
    moduleId: "nmba-osce-nursing",
    title: "Falls — Angry Daughter",
    description: "An angry daughter in aged care after her mother's second fall.",
    difficultyLevel: "intermediate",
    learnerRole: "Registered nurse in residential aged care",
    learnerOpens: true,
    timeLimitMinutes: 8,
    taskCard: [
      "Setting: Residential aged care facility",
      "Resident: Mrs Rose Allen, 86, fell for the second time this week (no injury). Her daughter has arrived and wants to speak to the nurse.",
      "",
      "Your task:",
      "• Acknowledge the daughter's concerns",
      "• Explain the falls-risk plan",
      "• Involve her in care decisions",
      "• Explain how her concerns will be documented and escalated",
    ].join("\n"),
    briefing: "OSCE-style communication station. De-escalate, don't get defensive.",
    assessmentFocus: ["De-escalation", "Falls prevention plan", "Partnership with family"],
    expectedSkills: ["De-escalation", "Person-centred care", "Communication"],
    other: {
      name: "Linda Allen",
      role: "the daughter of an 86-year-old resident who has fallen twice",
      voice: "coral",
      goal: "Make sure her mother is safe; considering a formal complaint.",
      demeanor: "Angry, threatens to complain, calms if listened to",
      openingLine: "That's twice this week. What exactly are you people doing to keep her safe?",
      endCondition: "the nurse has agreed a plan with you",
      card: ["Your mother gets up at night to use the toilet and won't use the call bell. Mention if asked.", "Ask: 'Why can't someone just sit with her at night?'"].join("\n"),
    },
  }),
  roleplay({
    id: "osce-pain-reassessment",
    moduleId: "nmba-osce-nursing",
    title: "Pain Reassessment",
    description: "A post-op patient downplays pain because he fears addiction.",
    difficultyLevel: "beginner",
    learnerRole: "Registered nurse on a surgical ward",
    learnerOpens: true,
    timeLimitMinutes: 8,
    taskCard: [
      "Setting: Surgical ward",
      "Patient: Mr Sam Nguyen, 52, day 1 after a laparotomy. He was given oxycodone 5 mg PRN 45 minutes ago.",
      "",
      "Your task:",
      "• Reassess his pain using a structured approach (e.g. PQRST)",
      "• Check for side effects (sedation, breathing, nausea)",
      "• Address his concerns about the medicine",
      "• Offer non-drug comfort measures",
    ].join("\n"),
    briefing: "OSCE-style pain assessment station.",
    assessmentFocus: ["Structured pain assessment", "Sedation and RR check", "Correcting misconceptions"],
    expectedSkills: ["Pain assessment", "Patient education", "Safety checks"],
    other: {
      name: "Sam Nguyen",
      role: "a 52-year-old man after abdominal surgery",
      voice: "verse",
      goal: "Avoid 'too many' painkillers.",
      demeanor: "Stoic, understates his pain",
      card: [
        "Say your pain is 'fine, maybe a 3'. If the nurse asks more carefully (movement, coughing), admit it's 7 when you cough.",
        "Your brother had a drug problem — mention if asked why you don't want painkillers.",
        "You feel a bit drowsy but are breathing normally.",
      ].join("\n"),
    },
  }),
  roleplay({
    id: "osce-transfusion-consent",
    moduleId: "nmba-osce-nursing",
    title: "Blood Transfusion — Consent",
    description: "A patient with concerns about a recommended blood transfusion.",
    difficultyLevel: "advanced",
    learnerRole: "Registered nurse on a medical ward",
    learnerOpens: true,
    timeLimitMinutes: 8,
    taskCard: [
      "Setting: Medical ward",
      "Patient: Mrs Grace Okafor, 61, haemoglobin 68 g/L. The doctor has prescribed a transfusion of one unit of red cells.",
      "",
      "Your task:",
      "• Explore her understanding and any concerns or beliefs",
      "• Explain the reason, benefits and risks in plain language",
      "• Explain what will be monitored and which symptoms to report",
      "• Confirm consent or escalate appropriately",
    ].join("\n"),
    briefing: "OSCE-style consent station. Respect autonomy; escalate if unsure.",
    assessmentFocus: ["Exploring beliefs", "Informed consent", "Reaction symptoms", "Escalation"],
    expectedSkills: ["Consent", "Patient education", "Escalation"],
    other: {
      name: "Grace Okafor",
      role: "a 61-year-old woman offered a blood transfusion",
      voice: "sage",
      goal: "Understand the risks; unsure because of a past experience and her faith.",
      demeanor: "Calm, careful, asks many questions",
      card: [
        "You refused blood once before. Your faith is important to you but you're not sure it forbids blood — mention only if asked about beliefs.",
        "Ask: 'What could go wrong?' and 'Are there any alternatives?'",
        "If the nurse offers for the doctor to discuss alternatives, accept.",
      ].join("\n"),
    },
  }),
  roleplay({
    id: "osce-bedside-handover-hypo",
    moduleId: "nmba-osce-nursing",
    title: "Bedside Handover — Hypoglycaemia",
    description: "Hand over a diabetic patient after a hypo to the oncoming nurse.",
    difficultyLevel: "intermediate",
    learnerRole: "Registered nurse finishing a morning shift",
    learnerOpens: true,
    timeLimitMinutes: 8,
    taskCard: [
      "Setting: Medical ward, end of shift",
      "Patient: Mr Victor Hall, 70, type 2 diabetes on insulin. At 11:30 his BGL was 3.2 mmol/L; treated with 15 g glucose and a sandwich. BGL at 11:45 was 5.8. Lunchtime insulin withheld per protocol; doctor informed.",
      "",
      "Your task:",
      "• Give a clear ISBAR handover to the oncoming nurse",
      "• State what is outstanding and when the next BGL is due",
      "• Answer your colleague's questions",
    ].join("\n"),
    briefing: "OSCE-style handover station.",
    assessmentFocus: ["Accurate ISBAR", "Outstanding tasks", "Numbers and times"],
    expectedSkills: ["Handover", "ISBAR", "Accuracy"],
    other: {
      name: "Priya Shah",
      role: "the oncoming registered nurse taking handover",
      voice: "marin",
      goal: "Get a safe, complete handover.",
      demeanor: "Professional, asks clarifying questions",
      openingLine: "Hi, I'm taking over Mr Hall. What do I need to know?",
      endCondition: "you're satisfied with the handover",
      card: [
        "Ask: 'When's the next BGL due?', 'Has the doctor changed the insulin dose?' and 'Is he eating normally?'",
        "If something is missing (e.g. what the doctor said), ask about it.",
      ].join("\n"),
    },
  }),
];

// ---- US medical interpreter oral (CMI / CHI) ------------------------------------------------
const usOral = [
  interpreting({
    id: "us-oral-diabetes-endocrine",
    moduleId: "us-medical-interpreter-oral",
    title: "Endocrinology — New Type 2 Diabetes",
    description: "HbA1c, metformin dosing and hypoglycaemia symptoms in short, exam-style turns.",
    difficultyLevel: "advanced",
    isFreePreview: true,
    interpreterRole: "Medical interpreter (oral exam practice)",
    briefing: "Oral-exam style: short turns both ways, first person, every number and drug name exact.",
    assessmentFocus: ["Doses and numbers", "Drug names", "Completeness without summarising"],
    expectedSkills: ["Short-term memory", "Terminology", "First-person rendition"],
    timeLimitMinutes: 12,
    clinician: {
      name: "Dr Emily Carter",
      role: "an endocrinologist",
      voice: "coral",
      goal: "Explain the diagnosis, start metformin and teach hypoglycaemia warning signs.",
      demeanor: "Efficient and kind",
      openingLine: "Your HbA1c came back at 8.4 percent, which confirms type 2 diabetes.",
      endCondition: "the medication plan, hypoglycaemia signs and follow-up are covered",
      context: "Start metformin 500 mg once daily with dinner, increasing to twice daily after two weeks. Mention foot checks and a follow-up in three months.",
    },
    patient: {
      name: "Rosa Delgado",
      role: "patient newly diagnosed with type 2 diabetes",
      voice: "sage",
      goal: "Understand the medicine and whether she can still eat normally.",
      demeanor: "Worried, practical",
      openingLine: "My mother had diabetes and lost a toe. Is that going to happen to me?",
      context: "You work night shifts at a hospital laundry and eat at irregular times.",
    },
  }),
  interpreting({
    id: "us-oral-prenatal",
    moduleId: "us-medical-interpreter-oral",
    title: "OB/GYN — 28-Week Prenatal Visit",
    description: "Glucose tolerance test, swollen ankles and fetal movements.",
    difficultyLevel: "intermediate",
    interpreterRole: "Medical interpreter (oral exam practice)",
    briefing: "Oral-exam style prenatal visit. Keep register and every detail.",
    assessmentFocus: ["Test names and timings", "Symptom descriptions", "Register"],
    expectedSkills: ["Terminology", "Accuracy", "Both directions"],
    timeLimitMinutes: 12,
    clinician: {
      name: "Nurse Practitioner Lisa Grant",
      role: "a women's health nurse practitioner",
      voice: "marin",
      goal: "Arrange the glucose test, assess swelling and review fetal movements.",
      demeanor: "Warm and thorough",
      openingLine: "You're 28 weeks today. We need to schedule your glucose tolerance test.",
      endCondition: "the glucose test, swelling advice and kick counts are covered",
      context: "The test is a 1-hour glucose challenge after a sweet drink. Ask about headaches and vision changes because of the swelling. Teach kick counts: 10 movements in 2 hours.",
    },
    patient: {
      name: "Ana Morales",
      role: "patient 28 weeks pregnant",
      voice: "shimmer",
      goal: "Ask about her swollen feet and whether the baby is moving enough.",
      demeanor: "Chatty, a little anxious",
      openingLine: "My feet are so swollen by the evening that my shoes don't fit.",
      context: "The baby seems quieter in the mornings. No headaches.",
    },
  }),
  interpreting({
    id: "us-oral-chest-pain-er",
    moduleId: "us-medical-interpreter-oral",
    title: "Emergency — Chest Pain",
    description: "Onset, radiation, aspirin, ECG and troponin in fast turns.",
    difficultyLevel: "advanced",
    interpreterRole: "Medical interpreter (oral exam practice)",
    briefing: "Oral-exam style emergency encounter. Fast, short turns.",
    assessmentFocus: ["Symptom chronology", "Test names", "Urgent register"],
    expectedSkills: ["Speed", "Accuracy", "Terminology"],
    timeLimitMinutes: 12,
    clinician: {
      name: "Dr Michael Brooks",
      role: "an emergency physician",
      voice: "ash",
      goal: "Characterise the chest pain and explain the ECG, troponin and aspirin.",
      demeanor: "Brisk, focused",
      openingLine: "When did the pain start, and does it spread anywhere?",
      endCondition: "you've explained the tests and given aspirin instructions",
      context: "Give 325 mg chewable aspirin. Explain a repeat troponin in three hours.",
    },
    patient: {
      name: "Luis Herrera",
      role: "patient with chest pain",
      voice: "cedar",
      goal: "Understand whether he's having a heart attack.",
      demeanor: "Frightened, sweaty, short answers",
      openingLine: "It started about an hour ago, like an elephant on my chest, and it goes down my left arm.",
      context: "You take lisinopril for blood pressure. You're allergic to penicillin.",
    },
  }),
  interpreting({
    id: "us-oral-paeds-ear",
    moduleId: "us-medical-interpreter-oral",
    title: "Pediatrics — Fever and Ear Pain",
    description: "Weight-based dosing and an amoxicillin course with a worried parent.",
    difficultyLevel: "intermediate",
    interpreterRole: "Medical interpreter (oral exam practice)",
    briefing: "Oral-exam style paediatric visit. Doses by weight must be exact.",
    assessmentFocus: ["Weight-based doses", "Course length", "Warning signs"],
    expectedSkills: ["Numbers", "Instructions", "Accuracy"],
    timeLimitMinutes: 12,
    clinician: {
      name: "Dr Hannah Lee",
      role: "a pediatrician",
      voice: "coral",
      goal: "Explain the ear infection, dosing and when to come back.",
      demeanor: "Friendly, clear",
      openingLine: "Her right eardrum is red and bulging, so this is an ear infection.",
      endCondition: "dosing, course length and return precautions are covered",
      context: "Amoxicillin 400 mg per 5 mL, give 7.5 mL twice a day for 10 days. Children's acetaminophen 7.5 mL every 6 hours as needed. Return if fever lasts more than 48 hours.",
    },
    patient: {
      name: "Carmen Ruiz",
      role: "mother of a three-year-old",
      voice: "sage",
      goal: "Understand the medicine and whether it's contagious.",
      demeanor: "Tired, asks practical questions",
      openingLine: "She's been pulling at her ear and crying all night, and she won't eat.",
      context: "Your daughter weighs 15 kilos. She goes to daycare.",
    },
  }),
  interpreting({
    id: "us-oral-tia-neuro",
    moduleId: "us-medical-interpreter-oral",
    title: "Neurology — Possible TIA",
    description: "Facial droop, slurred speech, MRI and blood thinners.",
    difficultyLevel: "advanced",
    interpreterRole: "Medical interpreter (oral exam practice)",
    briefing: "Oral-exam style neurology encounter. Dense terminology.",
    assessmentFocus: ["Neurological symptoms", "Test and drug names", "Completeness"],
    expectedSkills: ["Terminology", "Memory", "Accuracy"],
    timeLimitMinutes: 12,
    clinician: {
      name: "Dr Robert Kim",
      role: "a neurologist",
      voice: "cedar",
      goal: "Explain a likely transient ischemic attack, the MRI and starting clopidogrel.",
      demeanor: "Calm, precise",
      openingLine: "What you describe sounds like a transient ischemic attack, a warning sign for stroke.",
      endCondition: "the MRI, medication and stroke warning signs are covered",
      context: "Order an MRI of the brain and carotid ultrasound. Start clopidogrel 75 mg daily. Teach BE-FAST warning signs and calling 911.",
    },
    patient: {
      name: "Elena Vargas",
      role: "patient after a brief episode of facial droop",
      voice: "shimmer",
      goal: "Find out if she had a stroke and whether it will happen again.",
      demeanor: "Scared, asks directly",
      openingLine: "My face went numb on one side and I couldn't get my words out for about ten minutes.",
      context: "It happened yesterday at 4 pm while cooking. You smoke half a pack a day.",
    },
  }),
  interpreting({
    id: "us-oral-warfarin-pharmacy",
    moduleId: "us-medical-interpreter-oral",
    title: "Pharmacy — Warfarin Discharge",
    description: "Dose schedule, INR checks and food interactions.",
    difficultyLevel: "intermediate",
    interpreterRole: "Medical interpreter (oral exam practice)",
    briefing: "Oral-exam style pharmacy counselling.",
    assessmentFocus: ["Dose schedule", "INR monitoring", "Interactions"],
    expectedSkills: ["Instructions", "Numbers", "Terminology"],
    timeLimitMinutes: 12,
    clinician: {
      name: "Pharmacist James O'Neil",
      role: "a hospital pharmacist",
      voice: "ash",
      goal: "Counsel on warfarin dosing, INR tests, bleeding signs and diet.",
      demeanor: "Methodical",
      openingLine: "You'll take warfarin 5 milligrams every evening at the same time.",
      endCondition: "dosing, INR, bleeding signs and diet are covered",
      context: "First INR check in 3 days; target INR 2 to 3. Keep vitamin K foods steady rather than avoiding them. Avoid aspirin and ibuprofen.",
    },
    patient: {
      name: "Jorge Castillo",
      role: "patient going home on warfarin",
      voice: "verse",
      goal: "Know what to avoid and what to do if he misses a dose.",
      demeanor: "Polite, a bit confused",
      openingLine: "Can I still eat salad? My wife makes one every night.",
      context: "You also take an herbal tea for sleep.",
    },
  }),
];

export const examScenarios = [...oetNursing, ...oetMedicine, ...ielts, ...amc, ...osce, ...usOral];
